window.ATLAS = {
tops: [
 {id:'frontal',name:'Frontal lobe',kind:'Cerebral cortex · Lobe',group:'surface',color:'#5B8DEF',aka:['frontal lobe','frontal lobes'],
  where:'The front of each hemisphere, behind the forehead, ending at the central sulcus.',
  summary:"The frontal lobe is the largest lobe of the cerebral cortex and the brain's planning center. Its prefrontal cortex supports executive function: setting goals, weighing choices, holding facts in working memory and holding back impulses. Along its back edge, the primary motor cortex sends the signals that start voluntary movement.",
  does:['Planning, judgment and decision-making','Working memory and attention','Starting voluntary movement',"Producing speech through Broca's area, usually in the left hemisphere",'Personality and social behavior'],
  damage:"Damage can change personality, judgment and self-control. In 1848 an iron rod passed through the frontal lobe of railroad foreman Phineas Gage. He survived, but people who knew him said he was no longer the same man. Damage to Broca's area causes a kind of aphasia where speech is slow and effortful while understanding stays mostly intact.",
  fact:'The prefrontal cortex is one of the last brain areas to finish maturing, usually in the mid-20s.'},
 {id:'parietal',name:'Parietal lobe',kind:'Cerebral cortex · Lobe',group:'surface',color:'#E6B547',aka:['parietal lobe','parietal lobes'],
  where:'The top and upper back of each hemisphere, between the central sulcus and the occipital lobe.',
  summary:'The parietal lobe turns raw sensation into a sense of your body and the space around it. The somatosensory cortex receives touch, temperature, pain and proprioception signals from across the body. Areas behind it combine those signals with vision and hearing so you can reach for objects, judge distances and find your way.',
  does:['Touch, temperature and pain perception','Proprioception, your sense of body position','Spatial awareness and navigation','Guiding reaching and grasping','Reading, writing and arithmetic'],
  damage:'Damage to the right parietal lobe can cause hemispatial neglect: a person may eat food from only the right side of the plate or shave only half of their face. Damage on the left can disrupt reading, writing and calculation.',
  fact:"The dorsal stream of vision runs up into the parietal lobe, which is why it's called the brain's \"where\" pathway."},
 {id:'temporal',name:'Temporal lobe',kind:'Cerebral cortex · Lobe',group:'surface',color:'#4CB286',aka:['temporal lobe','temporal lobes'],
  where:'The lower side of each hemisphere, beneath the lateral sulcus, roughly behind your temples and ears.',
  summary:"The temporal lobe handles sound, language and memory. The auditory cortex picks out pitch, rhythm and speech sounds, and Wernicke's area helps you understand what words mean. Along its underside, the fusiform gyrus recognizes faces and objects, and tucked into its inner side are the hippocampus and amygdala of the limbic system.",
  does:['Hearing and sound processing',"Understanding language through Wernicke's area",'Recognizing faces and objects','Forming new memories, with the hippocampus','Emotional reactions, with the amygdala'],
  damage:"Temporal lobe epilepsy is the most common type of focal epilepsy, and its seizures can bring déjà vu, odd smells or sudden intense emotion. Damage to Wernicke's area causes an aphasia where speech flows easily but makes little sense.",
  fact:"Some people with fusiform damage develop face blindness: they see a face clearly but can't tell whose it is."},
 {id:'occipital',name:'Occipital lobe',kind:'Cerebral cortex · Lobe',group:'surface',color:'#E0798B',aka:['occipital lobe','occipital lobes'],
  where:'The very back of the brain, above the cerebellum.',
  summary:'The occipital lobe is devoted almost entirely to vision. Signals from the eyes travel through the thalamus to the primary visual cortex, which detects edges, angles and contrast. Neighboring areas add color, motion and shape, then send results forward along the dorsal stream, which works out where things are, and the ventral stream, which works out what they are.',
  does:['Receiving visual input from the eyes','Detecting edges, lines and contrast','Processing color and motion','Passing visual information to other lobes'],
  damage:'Damage to the primary visual cortex causes blindness in part of the visual field even when the eyes are healthy. Some patients show blindsight, pointing correctly at objects they say they cannot see.',
  fact:'Each hemisphere sees the opposite half of the world: your left occipital lobe handles everything to the right of where you are looking.'},
 {id:'cingulate',name:'Cingulate cortex',kind:'Limbic cortex · Inner surface',group:'surface',color:'#A3D16B',aka:['cingulate cortex','cingulate gyrus','cingulate'],
  where:'On the inner (medial) wall of each hemisphere, wrapping around the top of the corpus callosum like a belt. The Midline cut view shows it.',
  summary:'The cingulate cortex is a curved band of cortex that links emotion, motivation, pain and attention with action. Its front part, the anterior cingulate cortex, notices conflicts and errors and helps decide how much effort a task is worth. Its back part, the posterior cingulate cortex, is a core hub of the default mode network, which is active when you daydream, remember your past or think about yourself.',
  does:['Detecting errors and conflicting goals','Emotional awareness and regulation','The unpleasant feeling of pain','Motivation and effort','Self-reflection and autobiographical memory'],
  damage:'Damage to the anterior cingulate on both sides can cause severe apathy, and in extreme cases akinetic mutism, where a person is awake but rarely moves or speaks. Abnormal cingulate activity appears in depression, OCD, chronic pain and PTSD. A small number of centers still use surgical cingulotomy for severe, treatment-resistant OCD and pain.',
  fact:'Its name comes from the Latin cingulum, meaning "belt" or "girdle".'},
 {id:'insula',name:'Insula',kind:'Cerebral cortex · Hidden lobe',group:'deep',color:'#8FD694',aka:['insula','insular cortex','insulae'],
  where:'Folded deep inside the lateral sulcus, covered by parts of the frontal, parietal and temporal lobes.',
  summary:'The insula, sometimes called the fifth lobe, is a hidden island of cortex. It is the main hub for interoception, your sense of what is happening inside your body: heartbeat, breathing, hunger, nausea and pain. It combines those signals with emotion, which is why feelings like disgust, anxiety and craving are felt in the body. It also holds the primary taste cortex.',
  does:['Interoception, sensing your internal body state','Taste','Feeling disgust','Emotional awareness and empathy','Craving and urges','Part of the salience network'],
  damage:'A 2007 study found that smokers whose strokes damaged the insula were far more likely to quit easily, often saying the urge to smoke simply vanished. Insula damage can also impair taste and the recognition of disgust. Overactivity is linked with anxiety disorders.',
  fact:'It is also called the island of Reil, after the anatomist Johann Christian Reil who described it in 1809.'},
 {id:'cerebellum',name:'Cerebellum',kind:'Hindbrain',group:'surface',color:'#9C80D6',aka:['cerebellum','cerebella'],
  where:'Below the occipital lobe at the back of the skull, behind the brainstem.',
  summary:'The cerebellum, Latin for "little brain," fine-tunes movement. It compares what you meant to do with what your body is actually doing and corrects errors as you go, which gives you smooth coordination, balance and timing. It also drives motor learning, which is why practice makes a skill automatic, and it supports attention, language and emotion through loops with the cortex.',
  does:['Coordination and accuracy of movement','Balance and posture','Timing and rhythm','Motor learning','Supporting attention and language'],
  damage:'Damage causes ataxia: unsteady walking, shaky reaching and slurred speech. Unlike the cerebrum, each half of the cerebellum controls the same side of the body. Alcohol temporarily impairs the cerebellum, which is why roadside sobriety tests ask people to walk a straight line.',
  fact:"It makes up about 10% of the brain's volume but holds roughly 80% of its neurons, most of them tiny granule cells."},
 {id:'brainstem',name:'Brainstem',kind:'Midbrain & hindbrain',group:'surface',color:'#D98E52',aka:['brainstem','brain stem'],
  where:'The stalk at the base of the brain that connects it to the spinal cord.',
  summary:'The brainstem keeps you alive. Its three parts, the midbrain, pons and medulla oblongata, run autonomic functions like breathing, heart rate and blood pressure. Nearly every signal between brain and body passes through it, and 10 of the 12 pairs of cranial nerves start here. Small nuclei inside it supply the whole brain with dopamine, norepinephrine and serotonin, and its reticular formation keeps you awake and alert.',
  does:['Breathing, heart rate and blood pressure','Relaying signals between brain and spinal cord','Sleep, wakefulness and alertness','Reflexes like swallowing, coughing and blinking','Producing the brain\'s main neuromodulators'],
  damage:'Brainstem damage is often life-threatening because it controls breathing and heartbeat. A stroke in the pons can cause locked-in syndrome, in which a person is fully conscious but can communicate only by moving the eyes.',
  fact:'Swallowing, coughing, sneezing and gagging are all coordinated by the medulla.'},
 {id:'basalganglia',name:'Basal ganglia',kind:'Deep structure · Subcortical nuclei',group:'deep',color:'#FFD166',aka:['basal ganglia','basal nuclei'],
  where:'A group of nuclei deep in each hemisphere, wrapped around the thalamus, with the substantia nigra down in the midbrain.',
  summary:'The basal ganglia are connected nuclei that act like a gatekeeper for action. They receive input from almost the whole cortex, choose which movements, thoughts or habits to allow and suppress the rest, then send the result back to the cortex through the thalamus. Dopamine from the substantia nigra and the ventral tegmental area tunes this system, which makes it central to movement, habits, reward and motivation.',
  does:['Starting wanted movements and stopping unwanted ones','Forming habits and routines','Reward, motivation and reinforcement learning','Procedural learning','Controlling the speed and vigor of movement'],
  damage:"Loss of dopamine neurons in the substantia nigra causes Parkinson's disease, with slowness, stiffness and tremor. Loss of neurons in the caudate and putamen causes Huntington's disease, with uncontrolled movements. Basal ganglia circuits are also involved in OCD, Tourette's syndrome and addiction.",
  fact:'The striatum gets its name, "striped body", from bands of white matter running through it.'},
 {id:'thalamus',name:'Thalamus',kind:'Deep structure · Diencephalon',group:'deep',color:'#4FB4CA',aka:['thalamus','thalami'],
  where:'The center of the brain: one egg-shaped mass on each side of the midline, above the brainstem.',
  summary:"The thalamus is the brain's main relay. Information from every sense except smell stops here before reaching the cortex, and each of its nuclei passes signals to a matching cortical area. It also relays motor loops from the basal ganglia and cerebellum, and helps control attention, sleep and consciousness.",
  does:['Relaying vision, hearing, touch and taste to the cortex','Filtering what reaches awareness','Sleep and alertness','Linking the cerebellum and basal ganglia to the motor cortex'],
  damage:'A stroke in the thalamus can cause numbness, long-lasting pain or memory problems. Damage to both sides can cause coma, because it disrupts consciousness.',
  fact:'During deep sleep the thalamus produces bursts called sleep spindles, which help with memory consolidation.'},
 {id:'hypothalamus',name:'Hypothalamus',kind:'Deep structure · Diencephalon',group:'deep',color:'#F06C4B',aka:['hypothalamus','hypothalamic'],
  where:'Just below the thalamus at the base of the brain, directly above the pituitary gland.',
  summary:'About the size of an almond, the hypothalamus is the control center for homeostasis. It sets body temperature, hunger, thirst and sleep timing, and it commands the pituitary gland, which runs much of the endocrine system through hormones. It also sets off the fight-or-flight response.',
  does:['Body temperature','Hunger and thirst','Sleep and circadian rhythm','Controlling the pituitary gland and hormones','Stress responses'],
  damage:'Damage can cause runaway hunger, disrupted sleep, trouble controlling body temperature, or hormone problems such as diabetes insipidus, where the body cannot hold on to water.',
  fact:"It makes up less than 1% of the brain's weight."},
 {id:'hippocampus',name:'Hippocampus',kind:'Deep structure · Limbic system',group:'deep',color:'#C76BD1',aka:['hippocampus','hippocampi','hippocampal formation'],
  where:'Inside the inner (medial) temporal lobe; one curved structure in each hemisphere.',
  summary:'Named after the Greek word for seahorse because of its shape, the hippocampus turns everyday experiences into long-term memory. It is essential for declarative memory, such as what you ate this morning, and for memory consolidation during sleep. Its place cells also build a mental map that helps you navigate. Its output travels through an arching bundle called the fornix.',
  does:['Forming new memories of facts and events','Memory consolidation','Spatial memory and navigation','Linking memories to where and when they happened'],
  damage:"It is one of the first areas affected by Alzheimer's disease. A patient known as H.M. had both hippocampi removed in 1953 to treat epilepsy. Afterward he could not form new declarative memories, though he could still learn new motor skills.",
  fact:'London taxi drivers, who memorize thousands of streets, were found to have a larger rear hippocampus than average.'},
 {id:'amygdala',name:'Amygdala',kind:'Deep structure · Limbic system',group:'deep',color:'#E54C6B',aka:['amygdala','amygdalae'],
  where:'Deep in the front of the temporal lobe, just in front of the hippocampus; one in each hemisphere.',
  summary:'The amygdala, Greek for "almond," is the brain\'s threat detector. It quickly judges whether something is dangerous or important and launches the fight-or-flight response through the hypothalamus and brainstem. It also tags memories with emotion, which is why frightening events are remembered so vividly.',
  does:['Detecting threats and producing fear','Starting the fight-or-flight response','Emotional memory','Reading emotion in faces'],
  damage:'People with damage to both amygdalae may feel little fear and struggle to recognize fear in other faces. An overactive amygdala is linked to anxiety disorders and PTSD.',
  fact:'It can react to a threat before you are consciously aware of seeing it.'},
 {id:'callosum',name:'Corpus callosum',kind:'Deep structure · White matter',group:'deep',color:'#EDE6D6',aka:['corpus callosum'],
  where:'Deep in the middle of the brain, arching across the midline beneath the cortex.',
  summary:'The corpus callosum is the largest bundle of white matter in the brain, made of about 200 million axons. It links matching areas of the left and right hemispheres so they can share information and work as one.',
  does:['Sharing information between hemispheres','Coordinating movements of both hands','Joining the two halves of the visual field'],
  damage:'Surgeons sometimes cut it to stop severe epilepsy from spreading. Studies of these split-brain patients showed that one hemisphere can know things the other does not. Some people are born without one and adapt surprisingly well.',
  fact:'Its name is Latin for "tough body."'},
 {id:'ventricles',name:'Ventricles',kind:'Deep structure · Fluid system',group:'deep',color:'#5DA9E9',aka:['ventricles','ventricular system'],
  where:'Four connected, fluid-filled spaces in the middle of the brain: two lateral ventricles, the third ventricle and the fourth ventricle.',
  summary:'The ventricles are hollow chambers filled with cerebrospinal fluid (CSF). The choroid plexus lining them makes about half a liter of CSF a day. It flows from the lateral ventricles through the third and fourth ventricles and out around the brain and spinal cord, where it cushions the brain, carries away waste and keeps its chemical environment stable.',
  does:['Producing and circulating cerebrospinal fluid','Cushioning the brain against impact','Removing waste products',"Letting the brain float, reducing its effective weight"],
  damage:"If CSF flow is blocked or not absorbed, the ventricles swell, a condition called hydrocephalus. Enlarged ventricles are also a common finding in schizophrenia and in diseases that shrink brain tissue, such as Alzheimer's.",
  fact:'Total CSF volume is only about 150 mL, so it is replaced roughly three to four times a day.'}
],
subs: [
 /* ---------- Frontal ---------- */
 {id:'m1',parent:'frontal',name:'Primary motor cortex',short:'Motor cortex (M1)',aka:['primary motor cortex','motor cortex','m1'],
  where:'The precentral gyrus, the strip directly in front of the central sulcus.',
  summary:'M1 sends commands down the corticospinal tract to the spinal cord to move muscles on the opposite side of the body. It is laid out as a motor homunculus: legs near the top midline, then trunk, arms and hands, with the face lowest. The hands, lips and tongue get oversized areas because they need fine control.',
  does:['Executing voluntary movement','Controlling the force and direction of movement','Fine finger, lip and tongue movements'],
  clinical:'A stroke here causes weakness or paralysis on the opposite side of the body (hemiparesis). Its upper motor neurons degenerate in ALS.',
  fact:'Wilder Penfield mapped the motor homunculus by gently stimulating the cortex of awake patients during epilepsy surgery.'},
 {id:'premotor',parent:'frontal',name:'Premotor cortex',short:'Premotor cortex',aka:['premotor cortex','frontal eye fields'],
  where:'Just in front of the primary motor cortex on the outer surface of the frontal lobe.',
  summary:"The premotor cortex plans and prepares movements before they happen, especially movements guided by what you see or hear, like reaching for a ball. It contains the frontal eye fields, which steer voluntary eye movements, and mirror neurons, which fire both when you act and when you watch someone else do the same action.",
  does:['Planning and preparing movement','Movements guided by sight and sound','Voluntary eye movements (frontal eye fields)',"Understanding others' actions"],
  clinical:'Damage can cause apraxia, trouble carrying out skilled movements even though strength is normal.'},
 {id:'sma',parent:'frontal',name:'Supplementary motor area',short:'SMA',aka:['supplementary motor area','sma'],
  where:'On the inner wall of the frontal lobe, in front of the leg area of the motor cortex. The Midline cut view shows it.',
  summary:'The SMA plans movements you start from within, rather than in response to the world, and sequences of movements such as a practiced piano passage. It also coordinates the two sides of the body. Its activity rises before people report deciding to move, a signal called the readiness potential.',
  does:['Self-started movements','Sequencing movements','Coordinating both hands','Preparing to move'],
  clinical:"Damage can cause SMA syndrome, a temporary difficulty starting movement or speech that often recovers within weeks. It is also involved in the urge before tics in Tourette's syndrome.",
  fact:"Benjamin Libet's 1983 experiments on the readiness potential sparked decades of debate about free will."},
 {id:'dlpfc',parent:'frontal',name:'Dorsolateral prefrontal cortex',short:'DLPFC',aka:['dorsolateral prefrontal cortex','dlpfc'],
  where:'The upper outer surface of the front of the frontal lobe.',
  summary:'The DLPFC is the core of executive function. It holds and manipulates information in working memory, plans steps toward a goal, switches strategies when rules change and exerts top-down control over attention and emotion. It is one of the slowest regions to mature and one of the most expanded in humans.',
  does:['Working memory','Planning and organizing','Cognitive flexibility','Abstract reasoning','Top-down control of attention'],
  clinical:'Reduced DLPFC activity is linked to depression, schizophrenia and ADHD. Transcranial magnetic stimulation (TMS) for depression is usually aimed at the left DLPFC.',
  fact:'The Wisconsin Card Sorting Test, where the sorting rule secretly changes, is a classic test of DLPFC function.'},
 {id:'vlpfc',parent:'frontal',name:'Ventrolateral prefrontal cortex',short:'VLPFC',aka:['ventrolateral prefrontal cortex','vlpfc','inferior frontal gyrus'],
  where:"The lower outer surface of the frontal lobe, in front of and around Broca's area (the inferior frontal gyrus).",
  summary:'The VLPFC helps you stop actions and thoughts that are no longer appropriate, a skill called response inhibition, especially in the right hemisphere. It also helps select word meanings, retrieve memories on purpose and reappraise emotional situations, such as reframing a setback so it feels less upsetting.',
  does:['Stopping an action (response inhibition)','Choosing among competing words or ideas','Reappraising emotions','Retrieving memories on purpose'],
  clinical:'Weaker VLPFC control is linked to impulsivity in ADHD, borderline personality disorder and addiction.'},
 {id:'broca',parent:'frontal',name:"Broca's area",short:"Broca's area",aka:["broca's area",'broca'],
  where:'The back of the inferior frontal gyrus, just in front of the motor area for the face. Language-dominant in the left hemisphere for most people.',
  summary:"Broca's area helps turn ideas into fluent speech. It organizes grammar and word order and works with the motor cortex to plan movements of the lips, tongue and larynx. It also helps understand complex sentences. A fiber bundle called the arcuate fasciculus links it with Wernicke's area.",
  does:['Producing fluent speech','Grammar and sentence structure','Planning speech movements','Understanding complex sentences'],
  clinical:"Damage causes Broca's (expressive) aphasia: slow, effortful speech with missing small words, while understanding stays relatively good. People are usually aware of their errors.",
  fact:'It is named after Paul Broca, who in 1861 studied a patient nicknamed "Tan" because it was nearly the only syllable he could say.'},
 {id:'ofc',parent:'frontal',name:'Orbitofrontal cortex',short:'OFC',aka:['orbitofrontal cortex','ofc','orbitofrontal'],
  where:'The underside of the frontal lobe, just above the eye sockets (orbits).',
  summary:'The OFC works out how valuable something is right now, combining taste, smell, sight and past experience. It updates those values when outcomes change, such as when a favorite food stops being rewarding once you are full. This makes it important for flexible decisions, learning from rewards and punishments, and social behavior.',
  does:['Judging reward value','Updating choices when outcomes change','Combining smell and taste into flavor','Social and emotional decision-making'],
  clinical:'Damage can cause impulsive, socially inappropriate behavior and poor decisions despite intact intelligence. Overactivity in OFC–striatal circuits is one of the most consistent findings in OCD.'},
 {id:'vmpfc',parent:'frontal',name:'Ventromedial prefrontal cortex',short:'vmPFC',aka:['ventromedial prefrontal cortex','vmpfc'],
  where:'The lower part of the inner wall at the front of the frontal lobe. The Midline cut view shows it.',
  summary:"The vmPFC links emotion to decision-making. It represents how good or bad options feel, helps quiet the amygdala during fear extinction, and supports moral and social judgment. Antonio Damasio's somatic marker hypothesis proposes that it uses bodily emotional signals to guide choices.",
  does:['Emotion-based decision-making','Calming fear responses','Moral and social judgment','Thinking about yourself'],
  clinical:"Phineas Gage's injury mostly damaged this area. People with vmPFC damage often make risky, harmful choices in real life even though they can reason through problems in tests. Weaker vmPFC control of the amygdala is linked to PTSD and anxiety.",
  fact:'In the Iowa Gambling Task, people with vmPFC damage keep choosing from risky card decks even after losing repeatedly.'},
 {id:'dmpfc',parent:'frontal',name:'Dorsomedial prefrontal cortex',short:'dmPFC',aka:['dorsomedial prefrontal cortex','dmpfc','medial prefrontal cortex'],
  where:'The upper inner wall of the frontal lobe, in front of the supplementary motor area.',
  summary:"The dmPFC helps you think about other people's minds, called theory of mind, and about yourself. It is part of the default mode network and works with the anterior cingulate to monitor conflict and adjust behavior.",
  does:["Theory of mind: understanding others' beliefs and intentions",'Self-reflection','Social judgment','Monitoring and adjusting behavior'],
  clinical:'Differences in dmPFC activity during social tasks are reported in autism and schizophrenia.'},
 {id:'fpole',parent:'frontal',name:'Frontal pole',short:'Frontal pole',aka:['frontal pole'],
  where:'The very front tip of the frontal lobe (Brodmann area 10).',
  summary:'The frontal pole is one of the most recently evolved parts of the human brain. It lets you keep a main goal in mind while working on a sub-goal, compare several plans and think about your own thinking (metacognition).',
  does:['Juggling several goals at once','Exploring new options instead of familiar ones','Metacognition','Planning for the future'],
  fact:'Area 10 is proportionally larger in humans than in other apes.'},
 {id:'olfactory',parent:'frontal',name:'Olfactory bulb',short:'Olfactory bulb',aka:['olfactory bulb','olfactory bulbs'],
  where:'A small bulb under each frontal lobe, resting on a thin plate of bone above the nose.',
  summary:'The olfactory bulbs are the first relay for smell. Smell receptors in the nose send axons through tiny holes in the skull to the bulbs, which pass signals straight to smell cortex, the amygdala and the entorhinal cortex. Smell is the only sense that does not pass through the thalamus first, which may be why smells trigger such strong emotional memories.',
  does:['Receiving smell signals from the nose','Sorting odors into patterns','Sending smell information to emotion and memory areas'],
  clinical:"Loss of smell often appears years before the movement symptoms of Parkinson's disease and is an early sign in Alzheimer's disease. A blow to the head can tear the smell fibers and cause permanent loss of smell.",
  fact:'The nerve fibers that feed it make up cranial nerve I, the olfactory nerve.'},
 /* ---------- Parietal ---------- */
 {id:'s1',parent:'parietal',name:'Primary somatosensory cortex',short:'Somatosensory (S1)',aka:['primary somatosensory cortex','somatosensory cortex','s1'],
  where:'The postcentral gyrus, the strip directly behind the central sulcus.',
  summary:'S1 receives touch, pressure, vibration, temperature, pain and body-position signals from the opposite side of the body, relayed through the thalamus. It is arranged as a sensory homunculus that mirrors the motor strip in front of it. Areas with dense receptors, like the fingertips and lips, get the most space.',
  does:['Touch and texture','Locating pain and temperature','Proprioception','Recognizing objects by touch'],
  clinical:'Damage causes numbness or loss of fine touch on the opposite side. After amputation the body map reorganizes, which may contribute to phantom limb sensations.',
  fact:"Touching the face of some amputees produces sensations in the missing hand, because the face and hand areas are neighbors on the map."},
 {id:'spl',parent:'parietal',name:'Superior parietal lobule',short:'Superior parietal',aka:['superior parietal lobule'],
  where:'The upper part of the parietal lobe, above the intraparietal sulcus.',
  summary:'The superior parietal lobule builds a sense of where your body is in space and uses vision to guide reaching and grasping. It sits in the dorsal "where/how" visual stream and helps shift spatial attention.',
  does:['Visually guided reaching','Body schema','Spatial attention','Mental rotation'],
  clinical:'Damage can cause optic ataxia: missing targets when reaching even though vision and strength are fine.'},
 {id:'supramarginal',parent:'parietal',name:'Supramarginal gyrus',short:'Supramarginal',aka:['supramarginal gyrus'],
  where:'The lower parietal lobe, curving around the back end of the lateral sulcus.',
  summary:"Part of the inferior parietal lobule, the supramarginal gyrus links sounds with spelling, supports phonological working memory (repeating a phone number to yourself) and helps plan tool use and gestures. It also helps you tell your own emotions apart from other people's.",
  does:['Processing speech sounds','Verbal working memory','Planning skilled gestures','Separating self from others in empathy'],
  clinical:'Damage, especially on the left, can cause conduction aphasia (trouble repeating words) and ideomotor apraxia.'},
 {id:'angular',parent:'parietal',name:'Angular gyrus',short:'Angular gyrus',aka:['angular gyrus','temporoparietal junction'],
  where:'The lower back of the parietal lobe, near where the parietal, temporal and occipital lobes meet.',
  summary:'The angular gyrus is a hub connecting language, numbers, space and memory. It helps map written words to meaning, retrieve math facts, understand metaphors and recall rich details of past events. Together with nearby cortex it forms the temporoparietal junction, important for body ownership and understanding other minds.',
  does:['Reading and word meaning','Arithmetic facts','Metaphor and combining concepts','Recalling past events'],
  clinical:'Damage on the left can cause Gerstmann syndrome: trouble writing, doing arithmetic, telling left from right and naming fingers. Electrical stimulation near the right angular gyrus has triggered out-of-body experiences.'},
 {id:'precuneus',parent:'parietal',name:'Precuneus',short:'Precuneus',aka:['precuneus'],
  where:'The inner wall of the parietal lobe, just in front of the occipital lobe. The Midline cut view shows it.',
  summary:'The precuneus is one of the most connected and energy-hungry regions of the cortex. It supports visual imagery, recalling personal memories and self-awareness, and is a core node of the default mode network.',
  does:['Mental imagery','Autobiographical memory','Self-awareness','Shifting spatial attention'],
  clinical:"It is one of the first cortical areas to show reduced metabolism and amyloid buildup in Alzheimer's disease. Its activity drops in deep sleep and under anesthesia.",
  fact:'It is sometimes called the "mind\'s eye" of the brain.'},
 /* ---------- Temporal ---------- */
 {id:'a1',parent:'temporal',name:'Primary auditory cortex',short:'Auditory cortex (A1)',aka:['primary auditory cortex','auditory cortex','a1',"heschl's gyrus"],
  where:"On Heschl's gyrus, on the upper surface of the temporal lobe tucked inside the lateral sulcus.",
  summary:'A1 receives sound information from the medial geniculate nucleus of the thalamus. Its neurons are arranged by frequency (tonotopically), like a piano keyboard. It detects pitch, loudness and timing and passes results to surrounding areas that recognize speech, music and everyday sounds.',
  does:['Pitch and frequency analysis','Sound timing and rhythm','Locating sounds, with the other hemisphere','Early speech sound processing'],
  clinical:'Because each ear sends signals to both hemispheres, damage on one side rarely causes deafness. Damage on both sides can cause cortical deafness. It is also implicated in tinnitus and auditory hallucinations.'},
 {id:'stg',parent:'temporal',name:'Superior temporal gyrus',short:'Superior temporal',aka:['superior temporal gyrus','stg','superior temporal sulcus'],
  where:'The top gyrus of the temporal lobe, running along the lateral sulcus.',
  summary:'The superior temporal gyrus holds the auditory cortex and the areas around it. It recognizes speech sounds and music, and the groove below it, the superior temporal sulcus, responds to faces, eye gaze, voices and body movement, which makes it important for social perception.',
  does:['Recognizing speech sounds','Music perception','Perceiving gaze, faces and voices','Social perception'],
  clinical:'Reduced volume and abnormal activity in the left STG are among the most replicated findings in schizophrenia and are linked to auditory hallucinations. Differences in the superior temporal sulcus are reported in autism.'},
 {id:'wernicke',parent:'temporal',name:"Wernicke's area",short:"Wernicke's area",aka:["wernicke's area",'wernicke'],
  where:'The back part of the superior temporal gyrus, usually in the left hemisphere.',
  summary:"Wernicke's area connects the sounds of words with their meanings. It is essential for understanding spoken and written language and for choosing the right words when you speak.",
  does:['Understanding spoken language','Understanding written language','Choosing words','Monitoring your own speech'],
  clinical:"Damage causes Wernicke's (receptive) aphasia. Speech is fluent and grammatical but full of wrong or made-up words, and the person often does not realize anything is wrong.",
  fact:'Carl Wernicke described it in 1874, when he was 26.'},
 {id:'mtg',parent:'temporal',name:'Middle temporal gyrus',short:'Middle temporal',aka:['middle temporal gyrus'],
  where:'The middle band of the outer temporal lobe.',
  summary:'The middle temporal gyrus stores and retrieves word meanings and general knowledge about the world. It also helps understand actions, and its back end works with the motion area V5.',
  does:['Word meaning','Semantic memory','Understanding actions','Reading comprehension'],
  clinical:'It is affected in semantic dementia, a form of frontotemporal dementia, along with the temporal pole.'},
 {id:'itg',parent:'temporal',name:'Inferior temporal gyrus',short:'Inferior temporal',aka:['inferior temporal gyrus','inferior temporal cortex'],
  where:'The lowest band of the outer temporal lobe.',
  summary:'The inferior temporal gyrus is the end of the ventral "what" visual stream. Its neurons respond to whole objects and categories, regardless of size or viewing angle.',
  does:['Object recognition','Visual memory','Recognizing categories'],
  clinical:'Damage can cause visual agnosia: seeing an object clearly but being unable to recognize it.'},
 {id:'fusiform',parent:'temporal',name:'Fusiform gyrus',short:'Fusiform gyrus',aka:['fusiform gyrus','fusiform face area','visual word form area'],
  where:'The underside of the temporal and occipital lobes.',
  summary:'The fusiform gyrus contains specialized patches: the fusiform face area responds strongly to faces, and the visual word form area in the left hemisphere responds to written words. It also helps experts distinguish fine differences within a category, such as bird species or car models.',
  does:['Face recognition','Reading written words','Expert visual recognition'],
  clinical:'Damage causes prosopagnosia (face blindness). Some people are born with developmental prosopagnosia, estimated at around 2% of the population.'},
 {id:'tpole',parent:'temporal',name:'Temporal pole',short:'Temporal pole',aka:['temporal pole','temporal poles'],
  where:'The front tip of the temporal lobe.',
  summary:'The temporal pole links knowledge about people and things with emotion. It helps recognize familiar people, recall their names, and supports social and emotional understanding.',
  does:['Recognizing familiar people','Naming','Social and emotional knowledge'],
  clinical:'Shrinkage of the temporal poles is a hallmark of semantic dementia, in which people gradually lose the meaning of words and objects.'},
 {id:'parahippocampal',parent:'temporal',name:'Parahippocampal gyrus',short:'Parahippocampal',aka:['parahippocampal gyrus','parahippocampal place area'],
  where:'The inner underside of the temporal lobe, next to the hippocampus.',
  summary:'The parahippocampal gyrus surrounds the hippocampus and helps recognize scenes and places. Its parahippocampal place area responds strongly to pictures of buildings, rooms and landscapes. It also feeds context into the hippocampus for memory.',
  does:['Recognizing scenes and places','Navigation','Memory for context'],
  clinical:'Damage can cause topographic disorientation, getting lost in familiar places.'},
 {id:'entorhinal',parent:'temporal',name:'Entorhinal cortex',short:'Entorhinal cortex',aka:['entorhinal cortex','entorhinal'],
  where:'The front part of the parahippocampal gyrus, on the inner surface of the temporal lobe.',
  summary:"The entorhinal cortex is the main gateway into and out of the hippocampus. It contains grid cells, which fire in a hexagonal pattern as you move and act like the brain's coordinate system. Together with place cells in the hippocampus they form the brain's navigation system.",
  does:['Main input to the hippocampus','Grid cells for navigation','Memory formation','Sense of time within experiences'],
  clinical:"It is one of the very first areas where tau tangles appear in Alzheimer's disease, which may help explain why getting lost is an early symptom.",
  fact:"May-Britt and Edvard Moser shared the 2014 Nobel Prize in Physiology or Medicine with John O'Keefe for discovering grid and place cells."},
 /* ---------- Occipital ---------- */
 {id:'v1',parent:'occipital',name:'Primary visual cortex',short:'Visual cortex (V1)',aka:['primary visual cortex','visual cortex','v1','striate cortex'],
  where:'Along the calcarine sulcus on the inner wall of the occipital lobe, wrapping around the occipital pole.',
  summary:'V1 is the first cortical stop for vision, receiving input from the lateral geniculate nucleus of the thalamus. It holds a precise map of the opposite visual field, with the center of vision taking a large share. Its neurons detect edges at particular orientations, contrast and which eye a signal came from.',
  does:['Detecting edges and orientation','Mapping the visual field','Contrast and fine detail','Combining input from both eyes'],
  clinical:'Damage causes blindness in the matching part of the visual field, such as homonymous hemianopia after a stroke. Migraine aura is thought to come from a slow wave of activity spreading across visual cortex.',
  fact:'It is also called striate cortex because of a visible white stripe, the line of Gennari.'},
 {id:'cuneus',parent:'occipital',name:'Cuneus',short:'Cuneus',aka:['cuneus'],
  where:'The wedge-shaped area above the calcarine sulcus on the inner occipital lobe.',
  summary:'The cuneus holds the parts of V1 and V2 that represent the lower half of the visual field, and contributes to basic visual processing and attention.',
  does:['Lower visual field','Basic visual processing','Visual attention'],
  clinical:'Damage causes loss of the lower quarter of the visual field on the opposite side (quadrantanopia).'},
 {id:'lingual',parent:'occipital',name:'Lingual gyrus',short:'Lingual gyrus',aka:['lingual gyrus'],
  where:'Below the calcarine sulcus on the inner and lower occipital lobe.',
  summary:'The lingual gyrus processes the upper half of the visual field and contributes to recognizing letters and storing visual memories.',
  does:['Upper visual field','Letter and word processing','Visual memory'],
  clinical:'Damage causes loss of the upper quarter of the visual field on the opposite side.'},
 {id:'v2v3',parent:'occipital',name:'Visual association cortex',short:'V2 / V3',aka:['visual association cortex','extrastriate cortex','v2','v3'],
  where:'The outer surface of the occipital lobe, surrounding V1.',
  summary:"These areas take V1's edges and build them into contours, textures, depth and figure-versus-background. They send results into the dorsal stream toward the parietal lobe and the ventral stream toward the temporal lobe.",
  does:['Contours and shapes','Depth from both eyes','Texture','Separating objects from their background'],
  clinical:'Abnormal activity in visual association cortex is linked to visual hallucinations, such as those in Lewy body dementia and Charles Bonnet syndrome.'},
 {id:'v4',parent:'occipital',name:'V4 (color area)',short:'V4',aka:['v4'],
  where:'The underside of the occipital lobe, next to the fusiform gyrus.',
  summary:'V4 is part of the ventral stream and specializes in color and shape. It is responsible for color constancy, which keeps a banana looking yellow in sunlight or in shade.',
  does:['Color perception','Color constancy','Shape and curvature','Attention to visual features'],
  clinical:'Damage causes cerebral achromatopsia: the world appears in shades of gray.'},
 {id:'v5',parent:'occipital',name:'V5/MT (motion area)',short:'V5/MT',aka:['v5'],
  where:'The outer surface near where the occipital and temporal lobes meet.',
  summary:'V5, also called MT, specializes in motion. Its neurons respond to the direction and speed of movement, letting you track moving objects and judge how fast things approach. It is part of the dorsal stream.',
  does:['Motion direction and speed','Tracking moving objects','Guiding eye movements to follow motion'],
  clinical:'Damage on both sides causes akinetopsia, motion blindness. One famous patient said pouring tea looked like a frozen glacier, so she could not tell when the cup was full.',
  fact:'The "waterfall illusion", where still rocks seem to drift upward after you watch a waterfall, is thought to come from adapted motion neurons.'},
 /* ---------- Cingulate ---------- */
 {id:'acc',parent:'cingulate',name:'Anterior cingulate cortex',short:'ACC',aka:['anterior cingulate cortex','anterior cingulate','acc','subgenual acc','subgenual cingulate'],
  where:'The front part of the cingulate gyrus, curving around the front of the corpus callosum.',
  summary:'The ACC monitors performance, notices errors and conflict between competing responses, and signals when more control is needed. It also handles the emotional, unpleasant side of pain and weighs whether a reward is worth the effort. Its lowest part, the subgenual ACC under the front of the corpus callosum, is closely tied to mood.',
  does:['Detecting errors and conflict','The emotional side of pain','Effort and motivation','Emotion regulation','Feeling social rejection'],
  clinical:'Overactivity of the subgenual ACC is linked to depression, and it has been a target for deep brain stimulation in treatment-resistant depression. ACC abnormalities are also linked to OCD, PTSD and chronic pain.',
  fact:'Imaging studies found that being left out of a simple ball-tossing game activates the ACC, suggesting overlap between social and physical pain.'},
 {id:'pcc',parent:'cingulate',name:'Posterior cingulate cortex',short:'PCC',aka:['posterior cingulate cortex','posterior cingulate','pcc'],
  where:'The back part of the cingulate gyrus, above the back of the corpus callosum.',
  summary:'The PCC is a central hub of the default mode network. It is most active during rest, mind-wandering, recalling personal memories and imagining the future, and it quiets down when you focus on a demanding task.',
  does:['Mind-wandering and daydreaming','Autobiographical memory','Thinking about yourself','Monitoring the environment'],
  clinical:"Reduced metabolism in the PCC is an early sign of Alzheimer's disease on PET scans. Altered connectivity is reported in depression, ADHD and autism."},
 /* ---------- Insula ---------- */
 {id:'antinsula',parent:'insula',name:'Anterior insula',short:'Anterior insula',aka:['anterior insula'],
  where:'The front half of the insula, under the frontal operculum.',
  summary:'The anterior insula turns body signals into feelings. It is a key hub of the salience network, which decides what deserves attention and switches the brain between inward-focused thought and outward-focused tasks. It is active in disgust, empathy, uncertainty and craving.',
  does:['Emotional awareness','Disgust','Empathy','Switching attention to what matters','Craving'],
  clinical:'An overactive anterior insula is linked to anxiety and panic. Changes are reported in addiction, eating disorders and frontotemporal dementia.'},
 {id:'postinsula',parent:'insula',name:'Posterior insula',short:'Posterior insula',aka:['posterior insula'],
  where:'The back half of the insula, under the parietal and temporal operculum.',
  summary:'The posterior insula receives raw signals about the body: temperature, pain, itch, heartbeat, the state of the gut and gentle touch. It also contains much of the primary taste cortex.',
  does:['Interoception','Taste','Intensity of pain and temperature','Sensations from internal organs'],
  clinical:'Damage can disturb pain, temperature and taste sensation. Seizures starting here can cause choking sensations or tingling.'},
 /* ---------- Cerebellum ---------- */
 {id:'vermis',parent:'cerebellum',name:'Vermis',short:'Vermis',aka:['vermis','cerebellar vermis'],
  where:'The narrow middle strip joining the two halves of the cerebellum.',
  summary:"The vermis controls the body's midline: posture, balance, walking and eye movements. It also connects with limbic areas and may play a role in emotion.",
  does:['Posture and balance','Walking','Eye movements'],
  clinical:'Damage causes truncal ataxia: a wide, unsteady walk and swaying when sitting or standing. Long-term heavy alcohol use often damages the front of the vermis first.'},
 {id:'cerebhemi',parent:'cerebellum',name:'Cerebellar hemispheres',short:'Hemispheres',aka:['cerebellar hemispheres','cerebellar hemisphere'],
  where:'The two large side parts of the cerebellum.',
  summary:'The cerebellar hemispheres coordinate limb movements on the same side of the body. Their outer parts loop with the prefrontal and parietal cortex through the thalamus and help with timing, planning, language and working memory, not only movement.',
  does:['Coordinating arms and legs','Planning multi-joint movements','Timing','Supporting thinking and language'],
  clinical:'Damage causes clumsiness on the same side as the injury, intention tremor and dysmetria (overshooting or undershooting a target). Cerebellar cognitive affective syndrome can bring problems with planning, language and emotion.'},
 {id:'flocculo',parent:'cerebellum',name:'Flocculonodular lobe',short:'Flocculonodular',aka:['flocculonodular lobe','flocculus'],
  where:'The small lobes on the underside of the cerebellum, facing the brainstem.',
  summary:'The oldest part of the cerebellum, connected to the balance organs of the inner ear. It keeps you balanced and keeps your gaze steady while your head moves (the vestibulo-ocular reflex).',
  does:['Balance','Steady gaze during head movement','Eye movement control'],
  clinical:'Damage causes vertigo, an unsteady stance and nystagmus (involuntary jerking eye movements).'},
 {id:'dentate',parent:'cerebellum',name:'Dentate nucleus',short:'Dentate nucleus',aka:['dentate nucleus','deep cerebellar nuclei'],
  where:'Buried deep inside each cerebellar hemisphere.',
  summary:'The largest of the deep cerebellar nuclei and the main output of the cerebellar hemispheres. It sends signals through the thalamus to the motor and prefrontal cortex to plan and time movements and to support thinking.',
  does:['Main output of the cerebellar hemispheres','Movement planning and timing','Supporting cognition'],
  clinical:"Damage contributes to tremor and ataxia. It is affected in Friedreich's ataxia, some spinocerebellar ataxias and progressive supranuclear palsy."},
 /* ---------- Brainstem ---------- */
 {id:'midbrain',parent:'brainstem',name:'Midbrain',short:'Midbrain',aka:['midbrain','mesencephalon','periaqueductal gray'],
  where:'The top section of the brainstem, just below the thalamus.',
  summary:'The midbrain holds the superior colliculi for visual reflexes and the inferior colliculi for hearing on its back, and large motor tracts from the cortex in front. The periaqueductal gray around its central canal controls pain and defensive reactions like freezing. Cranial nerves III and IV, which move the eyes, start here.',
  does:['Eye movements and pupil reflexes','Turning toward sights and sounds','Pain control and defensive reactions','Relaying motor tracts'],
  clinical:'Damage can cause problems with eye movement and double vision. Midbrain shrinkage is a hallmark of progressive supranuclear palsy.'},
 {id:'pons',parent:'brainstem',name:'Pons',short:'Pons',aka:['pons'],
  where:'The bulging middle section of the brainstem, in front of the cerebellum.',
  summary:'The pons ("bridge") relays signals from the cortex to the cerebellum and holds nuclei for cranial nerves V to VIII: face sensation, chewing, facial expression, eye movement and hearing. It helps set breathing rhythm and plays a central role in REM sleep, including the muscle paralysis that stops you acting out dreams.',
  does:['Relaying cortex to cerebellum','Face sensation and chewing','REM sleep','Breathing rhythm'],
  clinical:'A stroke in the front of the pons can cause locked-in syndrome. Correcting very low blood sodium too quickly can damage it (osmotic demyelination).'},
 {id:'medulla',parent:'brainstem',name:'Medulla oblongata',short:'Medulla',aka:['medulla oblongata','medulla'],
  where:'The lowest part of the brainstem, joining the spinal cord.',
  summary:'The medulla contains the centers that control heart rate, blood pressure and breathing, plus reflexes like swallowing, coughing, sneezing and vomiting. Most motor fibers cross to the other side here, at the pyramidal decussation, which is why each side of the brain controls the opposite side of the body.',
  does:['Heart rate and blood pressure','Breathing','Swallowing, coughing and vomiting reflexes','Crossing of motor tracts'],
  clinical:"Opioid overdose kills mainly by suppressing the breathing centers here. Lateral medullary (Wallenberg) syndrome after a stroke causes vertigo, swallowing trouble and crossed loss of pain sensation."},
 {id:'vta',parent:'brainstem',name:'Ventral tegmental area',short:'VTA',aka:['ventral tegmental area','vta'],
  where:'A small cluster in the front of the midbrain, near the midline.',
  summary:'The VTA is a group of dopamine neurons in the midbrain. It sends dopamine to the nucleus accumbens (the mesolimbic pathway) and the prefrontal cortex (the mesocortical pathway). Its neurons signal reward prediction errors: they fire more when things turn out better than expected and less when they turn out worse.',
  does:['Reward and motivation','Learning from rewards','Dopamine supply to the prefrontal cortex'],
  clinical:'Nearly all addictive drugs increase dopamine released from VTA neurons into the nucleus accumbens. Altered mesolimbic dopamine is linked to psychosis in schizophrenia.'},
 {id:'lc',parent:'brainstem',name:'Locus coeruleus',short:'Locus coeruleus',aka:['locus coeruleus'],
  where:'A tiny paired nucleus in the back of the pons.',
  summary:"The locus coeruleus (\"blue spot\") is the brain's main source of norepinephrine. It sends fibers to almost the entire brain, adjusting arousal, alertness and focus, and it drives the stress response.",
  does:['Arousal and wakefulness','Attention and vigilance','Stress and alarm responses'],
  clinical:"It is overactive in panic and PTSD and during opioid withdrawal. It is one of the earliest sites to show tau buildup, years before Alzheimer's symptoms, and loses neurons in Parkinson's disease.",
  fact:'It looks blue-black in brain tissue because of neuromelanin pigment.'},
 {id:'raphe',parent:'brainstem',name:'Raphe nuclei',short:'Raphe nuclei',aka:['raphe nuclei','raphe'],
  where:'A column of nuclei along the midline of the brainstem.',
  summary:'The raphe nuclei are the main source of serotonin for the brain and spinal cord. Serotonin from the raphe influences mood, sleep, appetite, pain and impulse control.',
  does:['Serotonin production','Mood regulation','Sleep–wake cycles','Pain control'],
  clinical:'SSRIs, the most common antidepressants, act on serotonin released by raphe neurons.'},
 /* ---------- Basal ganglia ---------- */
 {id:'caudate',parent:'basalganglia',name:'Caudate nucleus',short:'Caudate',aka:['caudate nucleus','caudate'],
  where:'A C-shaped nucleus curving along the wall of the lateral ventricle, with a large head at the front.',
  summary:'Part of the striatum, the caudate connects mainly with the prefrontal cortex and supports goal-directed learning, planning and learning from feedback.',
  does:['Goal-directed behavior','Learning from feedback','Planning','Working memory support'],
  clinical:"It shrinks early and severely in Huntington's disease, which makes the nearby lateral ventricles look enlarged on scans. Caudate overactivity is linked to OCD."},
 {id:'putamen',parent:'basalganglia',name:'Putamen',short:'Putamen',aka:['putamen'],
  where:'A large, rounded nucleus on the outer side of the basal ganglia, beneath the insula.',
  summary:'Part of the striatum, the putamen connects mainly with motor and premotor cortex. It helps control movement and is central to motor learning and habits.',
  does:['Movement control','Motor learning','Habits'],
  clinical:"It loses its dopamine input in Parkinson's disease and is damaged in Huntington's and Wilson's disease. It is a common site of bleeding from high blood pressure."},
 {id:'gp',parent:'basalganglia',name:'Globus pallidus',short:'Globus pallidus',aka:['globus pallidus','pallidum'],
  where:'Just inside the putamen, toward the midline.',
  summary:'The globus pallidus is the main output station of the basal ganglia. Its internal part constantly inhibits the thalamus; when the striatum quiets it, the thalamus is released and movement can happen. Its external part helps fine-tune this balance.',
  does:['Main output of the basal ganglia','Releasing or holding back movement','Regulating movement amplitude'],
  clinical:"Deep brain stimulation of the internal globus pallidus treats Parkinson's disease and dystonia. It is often damaged in carbon monoxide poisoning."},
 {id:'nacc',parent:'basalganglia',name:'Nucleus accumbens',short:'Nucleus accumbens',aka:['nucleus accumbens','accumbens','ventral striatum'],
  where:'At the front and bottom of the striatum, where the caudate and putamen meet.',
  summary:'The nucleus accumbens is the hub of the reward circuit. It receives dopamine from the VTA and input from the prefrontal cortex, amygdala and hippocampus, and turns motivation into action. It responds to food, social connection, music, money and drugs.',
  does:['Reward and pleasure anticipation','Motivation','Reinforcement learning'],
  clinical:'Changes here are central to addiction. A blunted reward response is linked to anhedonia in depression.'},
 {id:'stn',parent:'basalganglia',name:'Subthalamic nucleus',short:'STN',aka:['subthalamic nucleus','stn'],
  where:'A small lens-shaped nucleus just below the thalamus.',
  summary:'The subthalamic nucleus acts as a brake, helping stop actions and pause before acting when a decision is difficult.',
  does:['Stopping actions','Pausing during difficult decisions','Regulating basal ganglia output'],
  clinical:"Damage can cause hemiballismus, wild flinging movements of the limbs on the opposite side. It is the most common deep brain stimulation target in Parkinson's disease."},
 {id:'sn',parent:'basalganglia',name:'Substantia nigra',short:'Substantia nigra',aka:['substantia nigra'],
  where:'A dark band in the front of the midbrain.',
  summary:'Its pars compacta contains dopamine neurons that project to the striatum (the nigrostriatal pathway), enabling smooth, well-scaled movement. Its pars reticulata is an output station similar to the internal globus pallidus.',
  does:['Dopamine supply to the striatum','Starting and scaling movement','Reward learning'],
  clinical:"Parkinson's movement symptoms usually appear only after a large share of these dopamine neurons, often estimated at 50–80%, has been lost.",
  fact:'Its name means "black substance", from the neuromelanin pigment in its neurons.'},
 /* ---------- Thalamus ---------- */
 {id:'antthal',parent:'thalamus',name:'Anterior nucleus',short:'Anterior nucleus',aka:['anterior nucleus','anterior thalamic nucleus','anterior thalamus'],
  where:'The front tip of the thalamus.',
  summary:'Part of the Papez circuit for memory. It receives input from the mammillary bodies and sends it to the cingulate cortex. It also contains head-direction cells that track which way you are facing.',
  does:['Episodic memory','Sense of direction'],
  clinical:'It is damaged in Korsakoff syndrome. It is a deep brain stimulation target for drug-resistant epilepsy.'},
 {id:'mdthal',parent:'thalamus',name:'Mediodorsal nucleus',short:'Mediodorsal',aka:['mediodorsal nucleus','mediodorsal thalamus'],
  where:'The upper inner part of the thalamus.',
  summary:'The mediodorsal nucleus is heavily connected with the prefrontal cortex and supports working memory, decision-making and emotional regulation.',
  does:['Prefrontal communication','Working memory','Decision-making'],
  clinical:'Reduced volume and connectivity are reported in schizophrenia. Damage contributes to memory loss in Korsakoff syndrome.'},
 {id:'ventthal',parent:'thalamus',name:'Ventral nuclear group',short:'Ventral nuclei',aka:['ventral nuclear group','ventral posterior nucleus','ventral lateral nucleus','vim'],
  where:'The lower outer part of the thalamus.',
  summary:'This group includes the ventral anterior and ventral lateral nuclei, which relay motor loops from the basal ganglia and cerebellum to the motor cortex, and the ventral posterior nuclei, which relay touch, pain and temperature from the body and face to the somatosensory cortex.',
  does:['Relaying motor loops to the cortex','Relaying touch, pain and temperature'],
  clinical:'Strokes here can cause Dejerine-Roussy syndrome, severe pain on the opposite side of the body. The ventral intermediate nucleus (VIM) is a treatment target for essential tremor.'},
 {id:'pulvinar',parent:'thalamus',name:'Pulvinar',short:'Pulvinar',aka:['pulvinar'],
  where:'The large rounded back end of the thalamus.',
  summary:'The pulvinar links visual areas with the parietal and frontal cortex and helps direct visual attention and filter out distractions.',
  does:['Visual attention','Filtering distractions','Linking visual and association cortex'],
  clinical:'Damage can cause attention problems for the opposite side of space.'},
 {id:'lgn',parent:'thalamus',name:'Lateral geniculate nucleus',short:'LGN',aka:['lateral geniculate nucleus','lgn'],
  where:'A small bump on the lower back of the thalamus.',
  summary:'The relay station for vision. It receives signals from the optic tract and sends them to the primary visual cortex through the optic radiations. Each LGN carries the opposite half of the visual field from both eyes, organized in six layers.',
  does:['Relaying vision to V1','Keeping signals from each eye separate']},
 {id:'mgn',parent:'thalamus',name:'Medial geniculate nucleus',short:'MGN',aka:['medial geniculate nucleus','mgn'],
  where:'A small bump on the lower back of the thalamus, inside the LGN.',
  summary:'The relay station for hearing, sending sound information from the inferior colliculus of the midbrain to the primary auditory cortex.',
  does:['Relaying sound to the auditory cortex']},
 {id:'pineal',parent:'thalamus',name:'Pineal gland',short:'Pineal gland',aka:['pineal gland','pineal','epithalamus'],
  where:'A tiny pinecone-shaped gland on the midline just behind the thalamus, part of the epithalamus.',
  summary:'The pineal gland releases melatonin, mostly at night. Light information reaches it indirectly from the suprachiasmatic nucleus, so darkness raises melatonin and light suppresses it, helping set the sleep–wake cycle.',
  does:['Releasing melatonin','Signaling night to the body'],
  clinical:'Pineal tumors can block CSF flow and cause hydrocephalus, or press on the midbrain and impair upward gaze (Parinaud syndrome).',
  fact:'René Descartes called it the principal seat of the soul.'},
 /* ---------- Hypothalamus ---------- */
 {id:'scn',parent:'hypothalamus',name:'Suprachiasmatic nucleus',short:'SCN',aka:['suprachiasmatic nucleus','scn'],
  where:'At the front of the hypothalamus, just above the optic chiasm.',
  summary:"The body's master clock. Special light-sensitive cells in the retina tell it about daylight, and it keeps the body's other clocks in sync on a roughly 24-hour cycle.",
  does:['Setting circadian rhythms','Timing melatonin release','Syncing body clocks to daylight'],
  clinical:'Disrupted clock signaling contributes to jet lag, shift-work sleep problems and circadian rhythm disorders, and may play a role in seasonal depression.'},
 {id:'pvn',parent:'hypothalamus',name:'Paraventricular nucleus',short:'PVN',aka:['paraventricular nucleus','pvn'],
  where:'Along the wall of the third ventricle in the upper hypothalamus.',
  summary:'The PVN starts the HPA axis: it releases CRH, which tells the pituitary to release ACTH, which tells the adrenal glands to release cortisol. It also makes oxytocin and vasopressin.',
  does:['Starting the stress-hormone cascade','Making oxytocin and vasopressin','Regulating appetite and blood pressure'],
  clinical:'An overactive HPA axis is found in many people with depression and is involved in anxiety and PTSD.'},
 {id:'arcuate',parent:'hypothalamus',name:'Arcuate nucleus',short:'Arcuate',aka:['arcuate nucleus'],
  where:'At the base of the hypothalamus, next to the pituitary stalk.',
  summary:'The arcuate nucleus reads hormones in the blood, such as leptin from fat and ghrelin from the stomach, and controls hunger and energy use. It also helps control growth hormone and prolactin release.',
  does:['Hunger and fullness signals','Energy balance','Controlling pituitary hormones'],
  clinical:'Damage to this area can cause severe weight gain (hypothalamic obesity).'},
 {id:'lateralhyp',parent:'hypothalamus',name:'Lateral hypothalamus',short:'Lateral hypothalamus',aka:['lateral hypothalamus'],
  where:'The outer part of the hypothalamus on each side.',
  summary:'The lateral hypothalamus promotes hunger, arousal and motivation. It contains the neurons that make orexin (also called hypocretin), which keep you awake and keep the switch between sleep and wake stable.',
  does:['Wakefulness (orexin)','Hunger','Motivation'],
  clinical:'Loss of orexin neurons causes narcolepsy type 1.'},
 {id:'mammillary',parent:'hypothalamus',name:'Mammillary bodies',short:'Mammillary bodies',aka:['mammillary bodies','mammillary body'],
  where:'Two small round bumps at the back of the underside of the hypothalamus.',
  summary:'The mammillary bodies receive input from the hippocampus through the fornix and pass it to the anterior thalamus, forming part of the Papez circuit for memory.',
  does:['Relaying memory signals','Spatial memory'],
  clinical:'They shrink in Wernicke-Korsakoff syndrome, caused by thiamine (vitamin B1) deficiency, which leads to severe memory loss.'},
 {id:'pituitary',parent:'hypothalamus',name:'Pituitary gland',short:'Pituitary',aka:['pituitary gland','pituitary'],
  where:'Hanging below the hypothalamus on a stalk, in a bony pocket called the sella turcica.',
  summary:'Often called the master gland, the pituitary releases hormones that control the thyroid, adrenal glands, growth, reproduction, milk production and water balance. Its front part is controlled by releasing hormones from the hypothalamus; its back part releases oxytocin and vasopressin made in the hypothalamus.',
  does:['Releasing hormones that control other glands','Growth','Water balance'],
  clinical:"Pituitary adenomas are common, usually benign tumors. They can release too much hormone or press on the optic chiasm above and cause loss of peripheral vision."},
 /* ---------- Hippocampus ---------- */
 {id:'ca',parent:'hippocampus',name:"Ammon's horn (CA1–CA3)",short:'CA1–CA3',aka:["ammon's horn",'cornu ammonis','ca1','ca3'],
  where:'The main curled layer of neurons forming the body of the hippocampus.',
  summary:'The CA fields are the core hippocampal circuits. CA3 has many connections back onto itself, which lets it complete a whole memory from a partial cue. CA1 compares new input with stored memories and sends the result to the subiculum and cortex.',
  does:['Storing memory patterns','Completing memories from cues','Comparing new and stored information'],
  clinical:'CA1 neurons are especially vulnerable to low oxygen; a brief cardiac arrest can damage them and cause lasting memory loss. Hippocampal sclerosis, scarring of CA1 and CA3, is the most common cause of drug-resistant temporal lobe epilepsy.'},
 {id:'dg',parent:'hippocampus',name:'Dentate gyrus',short:'Dentate gyrus',aka:['dentate gyrus'],
  where:'A C-shaped band tucked inside the curl of the CA fields, on the inner side of the hippocampus.',
  summary:'The dentate gyrus is the entry point for signals from the entorhinal cortex. It performs pattern separation, keeping similar experiences distinct, like where you parked today versus yesterday. It is one of the few places where new neurons can form in adults, though how much this happens in humans is still debated.',
  does:['Pattern separation','Entry point for cortical input','Adult neurogenesis'],
  clinical:'In animal studies, chronic stress reduces new neuron growth here, while exercise and antidepressants increase it.'},
 {id:'subiculum',parent:'hippocampus',name:'Subiculum',short:'Subiculum',aka:['subiculum'],
  where:'The lower edge of the hippocampus, where it meets the parahippocampal gyrus.',
  summary:'The main output of the hippocampus, sending processed information to the entorhinal cortex, mammillary bodies and other areas. It also helps regulate the stress response.',
  does:['Main hippocampal output','Spatial signals','Stress regulation'],
  clinical:"It is affected early in Alzheimer's disease."},
 {id:'fornix',parent:'hippocampus',name:'Fornix',short:'Fornix',aka:['fornix'],
  where:'An arching bundle running from the back of each hippocampus, under the corpus callosum, down to the mammillary bodies.',
  summary:'The fornix is a C-shaped bundle of white matter that carries signals from the hippocampus to the mammillary bodies and other areas. It is the main output pathway of the hippocampus in the Papez circuit.',
  does:['Carrying hippocampal output','Linking memory structures'],
  clinical:'Damage to the fornix, for example during surgery near the third ventricle, can cause severe amnesia.',
  fact:'Fornix is Latin for "arch".'},
 /* ---------- Amygdala ---------- */
 {id:'bla',parent:'amygdala',name:'Basolateral complex',short:'Basolateral',aka:['basolateral complex','basolateral amygdala'],
  where:'The lower outer part of the amygdala.',
  summary:'The input side of the amygdala. It receives information from all the senses, the thalamus and the cortex, and learns which cues predict danger or reward, as in fear conditioning.',
  does:['Fear conditioning','Linking cues to outcomes','Emotional memory'],
  clinical:'Overactive fear learning here is a leading model for anxiety disorders and PTSD.'},
 {id:'cea',parent:'amygdala',name:'Central nucleus',short:'Central nucleus',aka:['central nucleus of the amygdala','central amygdala'],
  where:'The upper inner part of the amygdala.',
  summary:'The main output of the amygdala. It triggers fear responses through the hypothalamus and brainstem: freezing, a racing heart, faster breathing and the release of stress hormones.',
  does:['Triggering bodily fear responses','Freezing','Startle'],
  clinical:'It drives the physical symptoms of fear and anxiety.'},
 {id:'medamyg',parent:'amygdala',name:'Medial nucleus',short:'Medial nucleus',aka:['medial amygdala'],
  where:'The inner surface of the amygdala.',
  summary:'The medial nucleus receives smell and pheromone signals and influences social behaviors such as aggression and parenting. Most of what is known comes from animal studies.',
  does:['Social smell signals','Social and parenting behavior','Aggression']},
 /* ---------- Corpus callosum ---------- */
 {id:'rostrum',parent:'callosum',name:'Rostrum',short:'Rostrum',aka:['rostrum'],
  where:'The thin lower front tip of the corpus callosum.',
  summary:'The rostrum connects the lower parts of the two frontal lobes, including the orbitofrontal cortex.',
  does:['Linking the orbitofrontal regions']},
 {id:'genu',parent:'callosum',name:'Genu',short:'Genu',aka:['genu'],
  where:'The forward bend at the front of the corpus callosum.',
  summary:'The genu ("knee") carries fibers between the left and right prefrontal cortex.',
  does:['Linking the prefrontal cortices','Coordinating planning across hemispheres'],
  clinical:'Its integrity is often studied with diffusion MRI in schizophrenia, bipolar disorder and ADHD.'},
 {id:'ccbody',parent:'callosum',name:'Body of the corpus callosum',short:'Body',aka:['body of the corpus callosum'],
  where:'The long middle section of the corpus callosum.',
  summary:'The body connects motor, premotor and somatosensory cortex of both sides, plus parts of the parietal lobes.',
  does:['Coordinating both sides of the body','Sharing touch information'],
  clinical:'It is commonly affected by the plaques of multiple sclerosis.'},
 {id:'splenium',parent:'callosum',name:'Splenium',short:'Splenium',aka:['splenium'],
  where:'The thick back end of the corpus callosum.',
  summary:'The splenium connects the occipital lobes and parts of the temporal and parietal lobes, sharing visual information between hemispheres.',
  does:['Linking visual cortices','Joining both halves of the visual field'],
  clinical:"Damage here together with damage to the left visual cortex can cause alexia without agraphia: a person can write but cannot read what they just wrote."},
 /* ---------- Ventricles ---------- */
 {id:'latvent',parent:'ventricles',name:'Lateral ventricles',short:'Lateral ventricles',aka:['lateral ventricles','lateral ventricle'],
  where:'One C-shaped cavity in each hemisphere, with horns reaching into the frontal, occipital and temporal lobes.',
  summary:'The largest ventricles. Most CSF is made by the choroid plexus here, then flows through small openings into the third ventricle.',
  does:['Making most of the CSF','Holding and circulating CSF'],
  clinical:"They enlarge in hydrocephalus and when surrounding tissue shrinks, as in Alzheimer's and Huntington's disease. Mild enlargement is a well-replicated finding in schizophrenia."},
 {id:'thirdvent',parent:'ventricles',name:'Third ventricle',short:'Third ventricle',aka:['third ventricle'],
  where:'A narrow slit on the midline between the two halves of the thalamus.',
  summary:'CSF enters the third ventricle from the lateral ventricles and drains through the cerebral aqueduct. The hypothalamus forms its floor and lower walls.',
  does:['Passing CSF to the aqueduct'],
  clinical:'A colloid cyst can suddenly block it and cause dangerous hydrocephalus.'},
 {id:'aqueduct',parent:'ventricles',name:'Cerebral aqueduct',short:'Aqueduct',aka:['cerebral aqueduct','aqueduct of sylvius'],
  where:'A narrow canal running through the midbrain.',
  summary:'The cerebral aqueduct connects the third and fourth ventricles.',
  does:['Carrying CSF through the midbrain'],
  clinical:'Because it is so narrow, it is the most common site of blockage causing hydrocephalus (aqueductal stenosis).'},
 {id:'fourthvent',parent:'ventricles',name:'Fourth ventricle',short:'Fourth ventricle',aka:['fourth ventricle'],
  where:'A tent-shaped cavity between the brainstem and the cerebellum.',
  summary:'CSF leaves the fourth ventricle through small openings to bathe the outside of the brain and spinal cord.',
  does:['Releasing CSF around the brain and spinal cord'],
  clinical:'Childhood tumors such as medulloblastoma often grow near it and block CSF flow.'}
]};
