window.DISEASES = [
/* ===== Neurodegenerative ===== */
{id:'alzheimers',name:"Alzheimer's disease",short:"Alzheimer's",aka:["alzheimer's disease","alzheimer's",'alzheimers','alzheimer disease'],cat:'Neurodegenerative diseases',
 summary:"Alzheimer's disease is a progressive brain disease and the most common cause of dementia. Two abnormal proteins build up: amyloid-beta forms plaques between neurons, and tau forms tangles inside them. Neurons and synapses are gradually lost, first in memory regions of the medial temporal lobe, then across much of the cortex. Brain changes begin 15–20 years before symptoms.",
 symptoms:['Forgetting recent conversations and events','Repeating questions','Getting lost in familiar places','Trouble with planning, money and complex tasks','Word-finding difficulty','Mood and personality changes, withdrawal','In late stages, loss of speech, mobility and swallowing'],
 causes:'Age is the biggest risk factor. The APOE ε4 gene variant raises risk, and rare mutations in APP, PSEN1 or PSEN2 cause early-onset familial disease. Down syndrome raises risk because chromosome 21 carries APP. Hearing loss, high blood pressure, diabetes, smoking, physical inactivity and low education are modifiable risk factors.',
 brain:[['entorhinal','p','Usually the first cortical area to develop tau tangles'],['hippocampus','p','Shrinks early, causing difficulty forming new memories'],['pcc','p','Reduced metabolism appears early on PET scans'],['precuneus','p','Early amyloid buildup and reduced metabolism'],['lc','s','Tau appears here even before the entorhinal cortex in many people'],['angular','s','Parietal involvement causes trouble with spatial and language tasks'],['temporal','s','Atrophy spreads through the temporal lobe'],['latvent','s','Ventricles enlarge as surrounding tissue shrinks'],['frontal','s','Frontal involvement in later stages affects judgment and behavior']],
 treatment:'Cholinesterase inhibitors (donepezil, rivastigmine, galantamine) and memantine can modestly help symptoms. Anti-amyloid antibodies (lecanemab and donanemab) remove plaques and modestly slow decline in early disease, with a risk of brain swelling or bleeding (ARIA). Exercise, managing blood pressure and hearing, and social engagement support brain health.',
 prevalence:'More than 7 million Americans aged 65 and older; dementia affects roughly 57 million people worldwide.',
 fact:'Alois Alzheimer described the disease in 1906 after examining the brain of his patient Auguste Deter.'},
{id:'parkinsons',name:"Parkinson's disease",short:"Parkinson's",aka:["parkinson's disease","parkinson's",'parkinsons','parkinson disease'],cat:'Neurodegenerative diseases',
 summary:"Parkinson's disease is a progressive disorder caused mainly by the loss of dopamine-producing neurons in the substantia nigra. Clumps of the protein alpha-synuclein, called Lewy bodies, build up in neurons. Without enough dopamine in the striatum, the basal ganglia cannot release movement normally, causing slowness, stiffness and tremor.",
 symptoms:['Resting tremor, often starting in one hand','Bradykinesia: slowness and smaller movements','Rigidity','Shuffling walk and balance problems','Soft voice and small handwriting','Early non-motor signs: loss of smell, constipation, acting out dreams (REM sleep behavior disorder), depression'],
 causes:'Most cases have no single cause. Age is the main risk factor. Genes such as LRRK2, GBA and SNCA contribute, and pesticide exposure and head injury raise risk.',
 brain:[['sn','p','Loss of dopamine neurons in the pars compacta, the defining feature'],['putamen','p','Loses its dopamine input first and most severely'],['gp','s','Overactive output that holds back movement'],['stn','s','Overactive; the main deep brain stimulation target'],['olfactory','s','Among the first areas affected, explaining early loss of smell'],['medulla','s','Lewy pathology begins in the lower brainstem in the Braak staging model'],['lc','s','Loss of norepinephrine neurons, linked to mood and attention symptoms'],['pons','s','Involvement of REM sleep circuits causes dream enactment']],
 treatment:'Levodopa (combined with carbidopa) is the most effective medication. Others include dopamine agonists, MAO-B inhibitors and COMT inhibitors. Deep brain stimulation helps selected patients. Exercise, physical therapy and speech therapy are important.',
 prevalence:'More than 10 million people worldwide, and rising as populations age.',
 fact:'Movement symptoms usually appear only after a large share of nigral dopamine neurons, often estimated at 50–80%, has already been lost.'},
{id:'huntingtons',name:"Huntington's disease",short:"Huntington's",aka:["huntington's disease","huntington's",'huntington disease'],cat:'Neurodegenerative diseases',
 summary:"Huntington's disease is an inherited disorder that destroys neurons in the striatum and later the cortex. It causes uncontrolled movements (chorea), cognitive decline and psychiatric symptoms, usually beginning between ages 30 and 50.",
 symptoms:['Chorea: involuntary jerking or writhing movements','Clumsiness and balance problems','Difficulty planning, focusing and organizing','Depression, irritability and apathy','Trouble swallowing and speaking in later stages'],
 causes:'An expanded CAG repeat in the HTT gene. It is autosomal dominant, so each child of an affected parent has a 50% chance of inheriting it. Longer repeats tend to cause earlier onset.',
 brain:[['caudate','p','The earliest and most severe neuron loss'],['putamen','p','Severe neuron loss'],['gp','s','Disrupted basal ganglia output'],['latvent','s','Enlarge as the caudate shrinks'],['dlpfc','s','Cortical thinning linked to cognitive decline']],
 treatment:'No cure. Tetrabenazine, deutetrabenazine and valbenazine reduce chorea; antidepressants and antipsychotics treat psychiatric symptoms; therapy and genetic counseling support families.',
 prevalence:'About 3–7 per 100,000 people of European ancestry; less common elsewhere.',
 fact:'The folk singer Woody Guthrie died of Huntington\'s disease in 1967.'},
{id:'als',name:'Amyotrophic lateral sclerosis',short:'ALS',aka:['amyotrophic lateral sclerosis','als',"lou gehrig's disease",'motor neuron disease'],cat:'Neurodegenerative diseases',
 summary:'ALS is a progressive disease that destroys both upper motor neurons in the motor cortex and lower motor neurons in the brainstem and spinal cord. Muscles weaken and waste away, eventually affecting speech, swallowing and breathing. Thinking is often preserved, though some people develop frontotemporal dementia.',
 symptoms:['Weakness in a hand, arm or leg','Muscle twitches (fasciculations) and cramps','Stiffness and brisk reflexes','Slurred speech and trouble swallowing','Breathing weakness'],
 causes:'About 90% of cases are sporadic. About 10% are familial, most often linked to C9orf72, SOD1, TARDBP or FUS genes. Clumps of the protein TDP-43 are found in most cases.',
 brain:[['m1','p','Upper motor neurons degenerate'],['medulla','p','Motor nuclei for the tongue and throat degenerate, affecting speech and swallowing'],['pons','s','Motor nuclei for chewing and facial movement'],['premotor','s','Frontal involvement on the ALS–frontotemporal dementia spectrum']],
 treatment:'Riluzole and edaravone modestly slow progression; tofersen treats SOD1-related ALS. Multidisciplinary care, breathing support and feeding support extend survival and quality of life.',
 prevalence:'About 2 per 100,000 people develop it each year.',
 fact:'The 2014 Ice Bucket Challenge raised over $100 million, which helped fund the discovery of the ALS gene NEK1.'},
{id:'ftd',name:'Frontotemporal dementia',short:'FTD',aka:['frontotemporal dementia','ftd','semantic dementia'],cat:'Neurodegenerative diseases',
 summary:'Frontotemporal dementia is a group of disorders where neurons in the frontal and temporal lobes degenerate. The behavioral variant changes personality and conduct; language variants (primary progressive aphasias) affect speech or word meaning. It often starts between 45 and 65.',
 symptoms:['Disinhibition and socially inappropriate behavior','Apathy and loss of empathy','Compulsive behaviors and changes in eating','Difficulty planning','Losing word meanings (semantic variant)','Halting, effortful speech (nonfluent variant)'],
 causes:'Abnormal tau or TDP-43 proteins. Up to about a third of cases are inherited, most often through C9orf72, MAPT or GRN genes.',
 brain:[['vmpfc','p','Early atrophy in the behavioral variant, causing disinhibition'],['ofc','p','Atrophy linked to compulsions and poor judgment'],['antinsula','p','Early loss, linked to reduced empathy'],['acc','s','Linked to apathy'],['tpole','p','Atrophy in the semantic variant'],['broca','s','Atrophy in the nonfluent variant']],
 treatment:'No disease-modifying treatment yet. SSRIs can reduce behavioral symptoms; speech therapy and caregiver support are central.',
 prevalence:'One of the most common dementias in people under 65.'},
{id:'dlb',name:'Dementia with Lewy bodies',short:'Lewy body dementia',aka:['dementia with lewy bodies','lewy body dementia'],cat:'Neurodegenerative diseases',
 summary:'Dementia with Lewy bodies is caused by alpha-synuclein clumps (Lewy bodies) spreading through the cortex and brainstem. It combines dementia with fluctuating alertness, vivid visual hallucinations, REM sleep behavior disorder and parkinsonism.',
 symptoms:['Fluctuating attention and alertness','Detailed visual hallucinations','Acting out dreams','Parkinson-like stiffness and slowness','Problems with visual-spatial tasks'],
 causes:'Mostly unknown; age is the main risk factor. Variants in GBA and APOE raise risk.',
 brain:[['v2v3','p','Reduced activity in visual cortex, linked to hallucinations'],['sn','s','Dopamine neuron loss causes parkinsonism'],['pons','s','Involvement of REM sleep circuits'],['lc','s','Early brainstem involvement'],['pcc','s','Relatively spared compared with the precuneus (the "cingulate island sign" on scans)']],
 treatment:'Cholinesterase inhibitors often help cognition and hallucinations. Many antipsychotics can cause severe reactions and must be used with great care.',
 prevalence:'Possibly the second most common degenerative dementia after Alzheimer\'s.'},
{id:'vascdem',name:'Vascular dementia',short:'Vascular dementia',aka:['vascular dementia','vascular cognitive impairment'],cat:'Neurodegenerative diseases',
 summary:'Vascular dementia is cognitive decline caused by reduced blood flow to the brain, through major strokes, many small silent strokes, or damage to small vessels deep in the white matter. It often causes slowed thinking and problems with planning rather than memory loss first, and it often occurs alongside Alzheimer\'s.',
 symptoms:['Slowed thinking','Trouble with planning and organizing','Step-like decline after strokes','Walking problems','Mood changes'],
 causes:'High blood pressure, diabetes, smoking, high cholesterol, atrial fibrillation and previous strokes.',
 brain:[['callosum','s','White matter damage disconnects brain regions'],['latvent','s','White matter changes cluster around the ventricles'],['caudate','s','Small (lacunar) strokes often hit deep nuclei'],['thalamus','s','Thalamic lacunes can cause memory problems'],['dlpfc','s','Disconnection of frontal circuits causes executive slowing']],
 treatment:'Control vascular risk factors and prevent further strokes. Cholinesterase inhibitors have small benefits.',
 prevalence:'The second most common cause of dementia, often mixed with Alzheimer\'s.'},
{id:'psp',name:'Progressive supranuclear palsy',short:'PSP',aka:['progressive supranuclear palsy','psp'],cat:'Neurodegenerative diseases',
 summary:"Progressive supranuclear palsy is a tau disorder that damages the brainstem, basal ganglia and frontal lobes. It is often mistaken for Parkinson's disease at first, but it causes early falls, stiffness of the trunk and difficulty moving the eyes, especially looking down.",
 symptoms:['Early, unexplained backward falls','Difficulty moving the eyes up and down','Stiff, upright posture','Slurred speech and swallowing trouble','Apathy and slowed thinking'],
 causes:'Abnormal tau accumulation; the cause is unknown.',
 brain:[['midbrain','p','Atrophy causes the "hummingbird sign" on MRI and impairs vertical gaze'],['stn','s','Neuron loss'],['gp','s','Neuron loss'],['dentate','s','Degeneration of cerebellar output'],['frontal','s','Frontal involvement causes apathy and executive problems']],
 treatment:'No disease-modifying treatment. Physical, speech and occupational therapy help; levodopa occasionally helps a little.',
 prevalence:'About 5–7 per 100,000 people.'},
{id:'cjd',name:'Creutzfeldt-Jakob disease',short:'CJD',aka:['creutzfeldt-jakob disease','cjd','prion disease'],cat:'Neurodegenerative diseases',
 summary:'CJD is a rare, rapidly progressive and fatal prion disease. Misfolded prion proteins force normal proteins to misfold, causing brain tissue to develop tiny holes (spongiform change). Most people die within a year of symptom onset.',
 symptoms:['Rapidly worsening dementia over weeks to months','Myoclonus: sudden muscle jerks','Problems with coordination and vision','Behavior changes'],
 causes:'About 85% of cases are sporadic, 10–15% are inherited through PRNP gene mutations, and a small number are acquired, such as variant CJD linked to eating beef from cattle with BSE ("mad cow disease").',
 brain:[['caudate','p','Bright signal on diffusion MRI is a diagnostic clue'],['putamen','p','Bright signal on diffusion MRI'],['frontal','s','Cortical "ribboning" on MRI across the cortex'],['parietal','s','Cortical involvement'],['pulvinar','s','The "pulvinar sign" is characteristic of variant CJD']],
 treatment:'No cure; care focuses on comfort. Strict sterilization prevents spread through surgical instruments.',
 prevalence:'About 1–2 cases per million people each year.'},
{id:'ms',name:'Multiple sclerosis',short:'Multiple sclerosis',aka:['multiple sclerosis'],cat:'Autoimmune & inflammatory diseases',
 summary:"Multiple sclerosis is an autoimmune disease in which the immune system attacks myelin, the insulation around nerve fibers, in the brain, spinal cord and optic nerves. Inflamed areas form plaques that disrupt signals. Most people start with relapsing-remitting disease; some later shift to a progressive course.",
 symptoms:['Vision loss or pain in one eye (optic neuritis)','Numbness, tingling or weakness','Fatigue','Balance problems and dizziness','Bladder problems','Thinking and memory difficulties','Symptoms worsening with heat'],
 causes:'Genetic susceptibility combined with environmental factors. Infection with Epstein-Barr virus appears to be a near-necessary trigger. Low vitamin D, smoking and childhood obesity also raise risk.',
 brain:[['callosum','p','Lesions in the corpus callosum ("Dawson\'s fingers") are characteristic'],['latvent','p','Lesions typically cluster in white matter around the ventricles'],['pons','s','Brainstem lesions cause double vision and dizziness'],['cerebhemi','s','Cerebellar lesions cause tremor and poor coordination']],
 treatment:'Disease-modifying therapies (such as ocrelizumab, natalizumab, ofatumumab and others) reduce relapses and new lesions. Steroids shorten relapses. Rehabilitation and symptom treatment help daily life.',
 prevalence:'About 2.8 million people worldwide; about two to three times more common in women.',
 fact:'A 2022 study of 10 million US military members found that Epstein-Barr infection raised MS risk about 32-fold.'},
/* ===== Cerebrovascular ===== */
{id:'ischemic',name:'Ischemic stroke',short:'Ischemic stroke',aka:['ischemic stroke'],cat:'Cerebrovascular diseases',
 summary:'An ischemic stroke happens when a blood clot or narrowed artery cuts off blood flow to part of the brain, starving it of oxygen. About 85% of strokes are ischemic. The symptoms depend on which artery is blocked; the middle cerebral artery, which supplies much of the outer brain, is the most commonly affected.',
 symptoms:['Sudden face drooping','Arm or leg weakness on one side','Speech difficulty or confusion','Sudden vision loss','Sudden dizziness or loss of balance'],
 causes:'Atherosclerosis, blood clots from the heart in atrial fibrillation, and small vessel disease. Risk factors include high blood pressure, diabetes, smoking, high cholesterol and inactivity.',
 brain:[['m1','p','Middle cerebral artery strokes often cause weakness on the opposite side'],['s1','p','Loss of sensation on the opposite side'],['broca','s','Left-sided strokes can cause expressive aphasia'],['wernicke','s','Left-sided strokes can cause receptive aphasia'],['putamen','s','Small deep (lacunar) strokes'],['ventthal','s','Thalamic strokes cause sensory loss or pain']],
 treatment:'Emergency treatment: clot-dissolving medication (alteplase or tenecteplase), usually within 4.5 hours, and mechanical thrombectomy for large-vessel blockages, up to 24 hours in selected patients. Then rehabilitation and prevention of another stroke.',
 prevalence:'About 795,000 strokes occur in the US each year.',
 fact:'"Time is brain": an untreated large stroke destroys an estimated 1.9 million neurons every minute. Remember BE FAST: Balance, Eyes, Face, Arm, Speech, Time.'},
{id:'ich',name:'Hemorrhagic stroke',short:'Hemorrhagic stroke',aka:['hemorrhagic stroke','intracerebral hemorrhage','brain bleed'],cat:'Cerebrovascular diseases',
 summary:'A hemorrhagic stroke happens when a blood vessel inside the brain bursts, and the leaking blood damages and compresses brain tissue. It accounts for about 10–15% of strokes but a larger share of stroke deaths.',
 symptoms:['Sudden severe headache','Weakness or numbness on one side','Vomiting','Decreased consciousness','Seizures'],
 causes:'Long-standing high blood pressure is the most common cause, followed by amyloid buildup in vessel walls (cerebral amyloid angiopathy) in older adults, blood thinners and vascular malformations.',
 brain:[['putamen','p','The most common site of high-blood-pressure bleeds'],['thalamus','p','Another common site'],['pons','s','Pontine bleeds are often severe'],['cerebhemi','s','Cerebellar bleeds may need urgent surgery']],
 treatment:'Rapid blood pressure lowering, reversing blood thinners, and sometimes surgery to remove the clot or relieve pressure.',
 prevalence:'About 10–15% of all strokes.'},
{id:'sah',name:'Subarachnoid hemorrhage and brain aneurysm',short:'Aneurysm rupture',aka:['subarachnoid hemorrhage','brain aneurysm','aneurysm'],cat:'Cerebrovascular diseases',
 summary:'A brain aneurysm is a weak, bulging spot in an artery wall, usually at the base of the brain. If it ruptures, blood fills the subarachnoid space around the brain, causing a sudden, severe headache. It is a medical emergency.',
 symptoms:['Sudden "worst headache of my life"','Stiff neck','Nausea and vomiting','Sensitivity to light','Loss of consciousness'],
 causes:'High blood pressure, smoking, family history and some inherited conditions such as polycystic kidney disease.',
 brain:[['ventricles','s','Blood can block CSF flow and cause hydrocephalus'],['ofc','s','Rupture of an anterior communicating artery aneurysm can damage the underside of the frontal lobe'],['hypothalamus','s','Can be affected by nearby bleeding, disturbing sodium and hormone balance']],
 treatment:'Securing the aneurysm by endovascular coiling or surgical clipping; nimodipine to reduce the risk of vasospasm; managing hydrocephalus.',
 prevalence:'An estimated 3% of adults have an unruptured aneurysm; most never rupture.'},
/* ===== Seizure & headache ===== */
{id:'epilepsy',name:'Epilepsy',short:'Epilepsy',aka:['epilepsy','temporal lobe epilepsy','seizure disorder'],cat:'Seizure & headache disorders',
 summary:'Epilepsy is a tendency to have repeated, unprovoked seizures, which are bursts of abnormal, synchronized electrical activity in the brain. Focal seizures start in one area; generalized seizures involve both hemispheres from the start. Temporal lobe epilepsy is the most common focal type in adults.',
 symptoms:['Staring spells or brief lapses in awareness','Jerking movements','Unusual feelings such as déjà vu, fear or a rising stomach sensation (auras)','Odd smells or tastes','Confusion after a seizure'],
 causes:'Genetics, brain injury, stroke, infection, tumors, developmental brain malformations and hippocampal sclerosis. In about half of cases, no cause is found.',
 brain:[['hippocampus','p','Hippocampal sclerosis is the most common cause of drug-resistant temporal lobe epilepsy'],['amygdala','s','Seizures here cause fear and emotional auras'],['entorhinal','s','Part of the seizure network'],['temporal','s','Most common lobe for focal seizures'],['antthal','s','A deep brain stimulation target for drug-resistant epilepsy']],
 treatment:'Antiseizure medications (such as levetiracetam, lamotrigine and carbamazepine) control seizures in about two-thirds of people. For drug-resistant epilepsy: surgery, laser ablation, vagus nerve stimulation, deep brain stimulation and the ketogenic diet.',
 prevalence:'About 50 million people worldwide.'},
{id:'migraine',name:'Migraine',short:'Migraine',aka:['migraine','migraines'],cat:'Seizure & headache disorders',
 summary:'Migraine is a common neurological disorder with recurring attacks of moderate to severe, often one-sided, throbbing headache, with nausea and sensitivity to light and sound. About a third of people have aura, temporary visual or sensory disturbances before the headache.',
 symptoms:['Prodrome: yawning, cravings, mood changes','Aura: zigzag lights or blind spots','Throbbing headache lasting 4–72 hours','Nausea and vomiting','Sensitivity to light, sound and smell','Postdrome: feeling drained'],
 causes:'Strong genetic component. Triggers include stress, sleep changes, hormonal shifts, skipped meals and certain foods or smells.',
 brain:[['v1','s','Cortical spreading depression across visual cortex is thought to cause aura'],['hypothalamus','s','Activity during the prodrome may explain yawning and cravings'],['pons','s','Brainstem nuclei are active during attacks'],['ventthal','s','Thalamic sensitization contributes to light sensitivity and skin pain']],
 treatment:'Acute: pain relievers, triptans, gepants and ditans. Prevention: CGRP-targeting antibodies, gepants, beta-blockers, topiramate, amitriptyline and Botox for chronic migraine.',
 prevalence:'About 1 billion people worldwide; about three times more common in women.'},
{id:'cluster',name:'Cluster headache',short:'Cluster headache',aka:['cluster headache','cluster headaches'],cat:'Seizure & headache disorders',
 summary:'Cluster headache causes excruciating, one-sided pain around the eye that lasts 15 minutes to 3 hours, often at the same time each day, during "cluster" periods of weeks to months.',
 symptoms:['Severe stabbing pain around one eye','Tearing, red eye and runny nose on the same side','Drooping eyelid','Restlessness and pacing','Attacks with clockwork timing'],
 causes:'Unknown; smoking, alcohol during clusters and a family history are associated.',
 brain:[['hypothalamus','p','The posterior hypothalamus is active during attacks and may drive their timing'],['scn','s','Circadian timing of attacks suggests clock involvement']],
 treatment:'High-flow oxygen and injected triptans stop attacks. Verapamil, galcanezumab and steroids prevent them.',
 prevalence:'About 1 in 1,000 people; more common in men.'},
/* ===== Trauma ===== */
{id:'tbi',name:'Traumatic brain injury and concussion',short:'TBI',aka:['traumatic brain injury','tbi','concussion','concussions'],cat:'Brain injury',
 summary:'A traumatic brain injury is damage from an external force, such as a fall, crash, sports impact or blast. A concussion is a mild TBI. The brain moves inside the skull, bruising its surface and stretching or tearing long nerve fibers (diffuse axonal injury).',
 symptoms:['Headache and dizziness','Confusion and memory problems','Nausea','Sensitivity to light and noise','Trouble concentrating and sleeping','Mood changes and irritability'],
 causes:'Falls, motor vehicle crashes, assaults, sports and military blasts.',
 brain:[['ofc','p','The underside of the frontal lobe scrapes against ridges of the skull'],['tpole','p','The front of the temporal lobe is commonly bruised'],['callosum','s','Shearing forces cause diffuse axonal injury'],['brainstem','s','Rotational forces can injure the brainstem in severe cases']],
 treatment:'Concussion: brief relative rest, then gradual return to activity and school or work. Moderate to severe TBI: emergency care, controlling pressure inside the skull, then rehabilitation.',
 prevalence:'Tens of millions of people worldwide each year.'},
{id:'cte',name:'Chronic traumatic encephalopathy',short:'CTE',aka:['chronic traumatic encephalopathy','cte'],cat:'Brain injury',
 summary:'CTE is a progressive tau disease linked to repeated head impacts, including those that do not cause concussion symptoms. It has been found in contact sport athletes and military veterans. It can only be confirmed after death.',
 symptoms:['Memory problems','Impulsivity and aggression','Depression and apathy','Confusion','Later dementia and parkinsonism'],
 causes:'Years of repeated head impacts, such as in American football, boxing, soccer heading or military blasts.',
 brain:[['frontal','p','Tau collects around blood vessels at the depths of the sulci'],['amygdala','s','Tau in later stages, linked to mood changes'],['hippocampus','s','Involved in later stages, linked to memory loss'],['thalamus','s','Involved in later stages'],['callosum','s','Thinning of white matter']],
 treatment:'No specific treatment; symptoms are managed. Reducing head impacts is the main prevention.',
 prevalence:'Unknown in the general population; found in a high share of brains donated by former professional football players.',
 fact:'Pathologist Bennet Omalu first reported CTE in a former NFL player in 2005.'},
/* ===== Infections ===== */
{id:'meningitis',name:'Meningitis',short:'Meningitis',aka:['meningitis','bacterial meningitis'],cat:'Infections',
 summary:'Meningitis is inflammation of the meninges, the membranes covering the brain and spinal cord, usually from infection. Bacterial meningitis is a medical emergency; viral meningitis is more common and usually milder. The meninges themselves are not shown in this model.',
 symptoms:['Fever','Severe headache','Stiff neck','Sensitivity to light','Confusion','Rash in meningococcal infection'],
 causes:'Bacteria such as Streptococcus pneumoniae and Neisseria meningitidis, viruses such as enteroviruses, and less often fungi.',
 brain:[['ventricles','s','Inflammation can block CSF flow and cause hydrocephalus'],['frontal','s','Inflammation can spread to the brain surface (meningoencephalitis)']],
 treatment:'Bacterial: urgent IV antibiotics and steroids. Viral: supportive care. Vaccines prevent many bacterial types.',
 prevalence:'Bacterial meningitis is much less common in countries with routine vaccination.'},
{id:'hsve',name:'Herpes simplex encephalitis',short:'HSV encephalitis',aka:['herpes simplex encephalitis','encephalitis'],cat:'Infections',
 summary:'Herpes simplex encephalitis is infection and inflammation of the brain by herpes simplex virus, usually HSV-1. It typically targets the temporal and frontal lobes, especially the limbic system. It is the most common cause of sporadic fatal viral encephalitis.',
 symptoms:['Fever and headache','Confusion and personality change','Seizures','Memory problems','Smell or taste hallucinations'],
 causes:'Reactivation or new infection with HSV-1 that reaches the brain, possibly through the olfactory or trigeminal nerves.',
 brain:[['hippocampus','p','Damage causes lasting memory loss'],['entorhinal','p','Medial temporal involvement'],['amygdala','p','Limbic involvement'],['antinsula','s','Often involved'],['ofc','s','Often involved']],
 treatment:'Urgent IV acyclovir, started as soon as it is suspected, greatly reduces death and disability.',
 prevalence:'About 2–4 cases per million people each year.',
 fact:'Clive Wearing, a musician left with one of the most severe cases of amnesia ever recorded, lost his memory to herpes encephalitis in 1985.'},
/* ===== Tumors ===== */
{id:'gbm',name:'Glioblastoma',short:'Glioblastoma',aka:['glioblastoma','gbm','glioma'],cat:'Brain tumors',
 summary:'Glioblastoma is the most common and aggressive primary brain cancer in adults. It grows from glial cells and spreads into surrounding brain tissue, making complete removal impossible.',
 symptoms:['Headaches, often worse in the morning','Seizures','Personality or memory changes','Weakness, speech or vision problems depending on location','Nausea'],
 causes:'Mostly unknown. Prior radiation to the head is a known risk factor.',
 brain:[['frontal','p','One of the most common locations'],['temporal','p','One of the most common locations'],['callosum','s','Tumors that cross through it to both sides are called "butterfly gliomas"']],
 treatment:'Surgery to remove as much as safely possible, then radiation and temozolomide chemotherapy; tumor-treating fields for some patients.',
 prevalence:'About 3 per 100,000 people each year; median survival is about 15 months with treatment.'},
{id:'meningioma',name:'Meningioma',short:'Meningioma',aka:['meningioma','meningiomas'],cat:'Brain tumors',
 summary:'Meningiomas grow from the meninges, the membranes around the brain. They are the most common primary brain tumor, and most are slow-growing and benign. They cause symptoms by pressing on nearby brain tissue.',
 symptoms:['Headaches','Seizures','Vision changes','Personality change with frontal tumors','Loss of smell with tumors under the frontal lobe'],
 causes:'Mostly unknown; prior radiation and the genetic condition NF2 raise risk. More common in women.',
 brain:[['frontal','s','Convexity and falx meningiomas often press on the frontal lobes'],['olfactory','s','Olfactory groove meningiomas cause loss of smell']],
 treatment:'Observation for small tumors; surgery or radiation when needed.',
 prevalence:'About 40% of primary brain tumors.'},
{id:'pitadenoma',name:'Pituitary adenoma',short:'Pituitary adenoma',aka:['pituitary adenoma','pituitary tumor'],cat:'Brain tumors',
 summary:'Pituitary adenomas are usually benign tumors of the pituitary gland. Some release too much of a hormone; larger ones press on nearby structures, especially the optic chiasm.',
 symptoms:['Loss of peripheral vision','Headache','Hormone effects: irregular periods, milk production, growth changes or Cushing\'s features','Fatigue from hormone deficiency'],
 causes:'Mostly unknown; a few are part of inherited syndromes such as MEN1.',
 brain:[['pituitary','p','The tumor\'s origin'],['hypothalamus','s','Large tumors can press upward on it']],
 treatment:'Medications (such as cabergoline for prolactinomas), surgery through the nose, or radiation.',
 prevalence:'Found incidentally on about 10% of brain scans, though most cause no symptoms.'},
/* ===== Structural & developmental ===== */
{id:'hydrocephalus',name:'Hydrocephalus',short:'Hydrocephalus',aka:['hydrocephalus','normal pressure hydrocephalus'],cat:'Structural & developmental conditions',
 summary:'Hydrocephalus is a buildup of cerebrospinal fluid that enlarges the ventricles and raises pressure on the brain. It can be present at birth or develop later. Normal pressure hydrocephalus in older adults causes a classic triad: walking problems, urinary incontinence and cognitive decline.',
 symptoms:['Infants: rapidly growing head, bulging soft spot','Headache, vomiting and blurred vision','Walking difficulty','Urinary urgency or incontinence','Memory and thinking problems'],
 causes:'Blocked CSF flow (for example aqueductal stenosis or tumors), poor absorption after bleeding or infection, or unknown causes.',
 brain:[['latvent','p','Enlarge as fluid builds up'],['thirdvent','p','Enlarges'],['aqueduct','p','The most common site of blockage'],['fourthvent','s','Enlarges if blockage is further downstream']],
 treatment:'A shunt to drain CSF to the abdomen, or endoscopic third ventriculostomy to create a bypass.',
 prevalence:'About 1 in 1,000 births; normal pressure hydrocephalus is underdiagnosed in older adults.'},
{id:'cp',name:'Cerebral palsy',short:'Cerebral palsy',aka:['cerebral palsy'],cat:'Structural & developmental conditions',
 summary:'Cerebral palsy is a group of lifelong movement and posture disorders caused by damage to the developing brain before, during or soon after birth. The damage does not get worse, though its effects can change with growth.',
 symptoms:['Stiff muscles (spasticity)','Involuntary movements (dyskinetic type)','Poor balance and coordination (ataxic type)','Delayed motor milestones','Sometimes epilepsy, intellectual disability or vision and hearing problems'],
 causes:'Premature birth, low birth weight, infections during pregnancy, lack of oxygen, strokes in the baby and brain malformations.',
 brain:[['m1','p','Damage to motor areas or their pathways causes spastic types'],['latvent','s','Periventricular white matter injury is common in premature babies'],['putamen','s','Damage causes dyskinetic types'],['thalamus','s','Often damaged alongside the basal ganglia'],['cerebhemi','s','Damage causes ataxic types']],
 treatment:'Physical, occupational and speech therapy; botulinum toxin and baclofen for spasticity; orthopedic surgery; assistive devices.',
 prevalence:'About 2–3 per 1,000 children; the most common physical disability in childhood.'},
/* ===== Movement ===== */
{id:'et',name:'Essential tremor',short:'Essential tremor',aka:['essential tremor'],cat:'Movement disorders',
 summary:'Essential tremor causes rhythmic shaking, mainly of both hands during action, such as writing or holding a cup. The head and voice can also shake. It is the most common movement disorder.',
 symptoms:['Shaking hands during action','Head or voice tremor','Worse with stress, caffeine and fatigue','Often improves temporarily with alcohol'],
 causes:'Strongly familial in about half of cases.',
 brain:[['cerebhemi','p','Cerebellar circuit dysfunction and Purkinje cell changes'],['dentate','p','Abnormal cerebellar output'],['ventthal','p','The ventral intermediate nucleus is the target for deep brain stimulation and focused ultrasound']],
 treatment:'Propranolol and primidone; deep brain stimulation or focused ultrasound thalamotomy for severe cases.',
 prevalence:'About 1% of people overall and several percent of those over 65.'},
{id:'dystonia',name:'Dystonia',short:'Dystonia',aka:['dystonia','dystonias'],cat:'Movement disorders',
 summary:'Dystonia causes sustained or intermittent muscle contractions that produce twisting movements and abnormal postures. It can affect one area, such as the neck (cervical dystonia) or hand (writer\'s cramp), or the whole body.',
 symptoms:['Twisting or pulling postures','Neck turning','Cramping of the hand when writing','Eyelid closure (blepharospasm)','Often triggered by specific actions'],
 causes:'Genetics (such as DYT1), brain injury, medications, or unknown.',
 brain:[['putamen','p','Abnormal basal ganglia signaling'],['gp','p','The internal globus pallidus is the deep brain stimulation target'],['cerebhemi','s','Cerebellar circuits are increasingly implicated'],['s1','s','Altered sensory processing and body maps']],
 treatment:'Botulinum toxin injections for focal dystonia; medications such as trihexyphenidyl; deep brain stimulation for severe generalized dystonia.',
 prevalence:'The third most common movement disorder.'},
{id:'ataxia',name:'Hereditary cerebellar ataxias',short:'Cerebellar ataxia',aka:['spinocerebellar ataxia',"friedreich's ataxia",'cerebellar ataxia'],cat:'Movement disorders',
 summary:"This group of inherited diseases, including the spinocerebellar ataxias and Friedreich's ataxia, causes progressive loss of coordination as the cerebellum and its connections degenerate.",
 symptoms:['Unsteady, wide-based walking','Clumsy hands','Slurred speech','Abnormal eye movements'],
 causes:"Gene mutations, often repeat expansions (CAG repeats in many SCAs; GAA repeats in the FXN gene in Friedreich's ataxia).",
 brain:[['cerebhemi','p','Degeneration causes limb ataxia'],['vermis','p','Degeneration causes unsteady walking'],['dentate','s',"Degeneration, especially in Friedreich's ataxia"],['pons','s','Involved in several SCA types']],
 treatment:"Physical and speech therapy. Omaveloxolone is approved for Friedreich's ataxia.",
 prevalence:'Rare; each type affects a few people per 100,000.'},
/* ===== Metabolic & toxic ===== */
{id:'wks',name:'Wernicke-Korsakoff syndrome',short:'Wernicke-Korsakoff',aka:['wernicke-korsakoff syndrome','korsakoff syndrome',"korsakoff's syndrome",'wernicke encephalopathy'],cat:'Metabolic & toxic conditions',
 summary:'Wernicke-Korsakoff syndrome is brain damage caused by thiamine (vitamin B1) deficiency. Wernicke encephalopathy is the acute stage, with confusion, eye movement problems and unsteady walking; untreated, it can lead to Korsakoff syndrome, with severe lasting memory loss.',
 symptoms:['Confusion','Abnormal eye movements','Unsteady walking','Severe inability to form new memories','Confabulation: filling memory gaps with invented stories'],
 causes:'Thiamine deficiency, most often from long-term heavy alcohol use, but also from severe vomiting, malnutrition or bariatric surgery.',
 brain:[['mammillary','p','Shrinkage is a hallmark'],['mdthal','p','Damage contributes to amnesia'],['antthal','s','Disrupts the Papez memory circuit'],['fornix','s','Memory circuit disconnection'],['vermis','s','Damage causes unsteady walking'],['midbrain','s','Damage near the aqueduct affects eye movements']],
 treatment:'Urgent high-dose IV thiamine. Early treatment can reverse Wernicke symptoms, but memory loss from Korsakoff syndrome often persists.',
 prevalence:'Found in about 1–2% of autopsies; often missed during life.'},
{id:'wilson',name:"Wilson's disease",short:"Wilson's disease",aka:["wilson's disease",'wilson disease'],cat:'Metabolic & toxic conditions',
 summary:"Wilson's disease is an inherited disorder in which the body cannot remove copper, which builds up in the liver and brain. It causes liver disease, movement disorders and psychiatric symptoms, usually starting between ages 5 and 35.",
 symptoms:['Tremor, stiffness and abnormal movements','Slurred speech and drooling','Depression, personality change or psychosis','Liver problems','Copper-colored rings around the cornea (Kayser-Fleischer rings)'],
 causes:'Mutations in the ATP7B gene, inherited in an autosomal recessive pattern.',
 brain:[['putamen','p','Copper deposits are most prominent here'],['gp','s','Copper damage'],['caudate','s','Copper damage'],['midbrain','s','Can produce the "face of the giant panda" sign on MRI'],['pons','s','Involved in some cases']],
 treatment:'Lifelong chelating drugs (penicillamine or trientine) or zinc, and a low-copper diet. Liver transplant for severe liver failure.',
 prevalence:'About 1 in 30,000 people.'}
];
