window.COND_EXT=window.COND_EXT||{};
Object.assign(window.COND_EXT,{
'disease:cluster':{
 overview:['Cluster headache causes excruciating, one-sided pain around the eye, lasting 15 minutes to 3 hours, often at the same time each day, during "cluster" periods that last weeks to months and then go into remission. It is often described as one of the most painful conditions known.','Its clockwork timing, both daily and seasonal, points to the brain\'s internal clock. Unlike people with migraine, who lie still, people with cluster headache are typically restless and pace during attacks.'],
 brain:[['hypothalamus','p','The posterior hypothalamus becomes active during attacks and may switch them on, which explains their regular timing and the autonomic symptoms like tearing and a runny nose.'],['scn','s','The master clock may set the circadian and seasonal timing of attacks.']],
 symptoms:['Severe stabbing pain around one eye','Tearing, red eye and runny nose on the same side','Drooping eyelid and small pupil','Restlessness and pacing','Attacks with clockwork timing'],
 diagnosis:'Clinical diagnosis based on attack pattern; MRI rules out other causes.',
 causes:['Unknown; smoking, alcohol during clusters and a family history are associated.'],
 treatment:['High-flow oxygen and injected or nasal triptans stop attacks. Verapamil, galcanezumab and short courses of steroids prevent them. Nerve stimulation is an option for chronic cases.'],
 course:'Episodic in most people, with remissions lasting months to years; about 10–20% have the chronic form.'},
'disease:tbi':{
 overview:['A traumatic brain injury is damage caused by an external force, such as a fall, crash, sports impact or blast. A concussion is a mild TBI. The brain moves inside the skull, bruising its surface where it strikes bony ridges and stretching long nerve fibers.','After impact, a cascade of chemical changes follows: ion imbalances, energy crisis and inflammation, which is why the brain is vulnerable for days to weeks and why rest followed by gradual return to activity is recommended.'],
 brain:[['ofc','p','The underside of the frontal lobe scrapes against the bony floor of the skull, causing bruising that can change judgment, impulse control and personality.'],['tpole','p','The front of the temporal lobe hits the skull\'s middle fossa, affecting memory and emotion.'],['callosum','s','Rotational forces shear long axons (diffuse axonal injury), slowing processing speed.'],['brainstem','s','Severe rotational forces can injure the brainstem, affecting consciousness.']],
 symptoms:['Headache and dizziness','Confusion and memory problems','Nausea','Sensitivity to light and noise','Trouble concentrating and sleeping','Mood changes and irritability'],
 diagnosis:'The Glasgow Coma Scale grades severity; CT or MRI detects bleeding or swelling. Concussion is a clinical diagnosis, as scans are usually normal.',
 types:['Mild (concussion), moderate and severe TBI.'],
 causes:['Falls, motor vehicle crashes, assaults, sports and military blasts.'],
 treatment:['Concussion: brief relative rest, then gradual return to activity and school or work. Moderate to severe TBI: emergency care, controlling pressure inside the skull, then rehabilitation.'],
 course:'Most concussions resolve within weeks; some people have persistent symptoms. Moderate and severe TBI recovery can take months to years.'},
'disease:cte':{
 overview:['CTE is a progressive tau disease linked to years of repeated head impacts, including many that never cause concussion symptoms. It has been found in contact-sport athletes and military veterans and can currently only be confirmed after death.','Its signature is tau building up around small blood vessels at the bottoms of the sulci, the places most strained by impacts.'],
 brain:[['frontal','p','Tau collects around blood vessels at the depths of frontal sulci, affecting judgment and impulse control.'],['amygdala','s','Tau in later stages is linked to mood changes and aggression.'],['hippocampus','s','Involvement in later stages causes memory loss.'],['thalamus','s','Involved in later stages.'],['callosum','s','Thinning of white matter.']],
 symptoms:['Memory problems','Impulsivity and aggression','Depression and apathy','Confusion','Later dementia and parkinsonism'],
 diagnosis:'Confirmed only by brain examination after death; "traumatic encephalopathy syndrome" criteria describe likely cases in life.',
 causes:['Years of repeated head impacts.'],
 treatment:['No specific treatment; symptoms are managed. Reducing head impacts is the main prevention.'],
 course:'Progressive over years to decades.'},
'disease:meningitis':{
 overview:['Meningitis is inflammation of the meninges, the membranes covering the brain and spinal cord, usually caused by infection. Bacterial meningitis can kill within hours and is a medical emergency; viral meningitis is more common and usually milder.','The meninges are not shown in this model; the highlighted areas show common complications.'],
 brain:[['ventricles','s','Inflammation can block CSF flow and cause hydrocephalus.'],['frontal','s','Inflammation can spread to the brain surface (meningoencephalitis).']],
 symptoms:['Fever','Severe headache','Stiff neck','Sensitivity to light','Confusion','Rash in meningococcal infection'],
 diagnosis:'Lumbar puncture to analyze spinal fluid, plus blood cultures.',
 causes:['Bacteria, viruses and less often fungi.'],
 treatment:['Bacterial: urgent IV antibiotics and steroids. Viral: supportive care. Vaccines prevent many bacterial types.'],
 course:'Bacterial meningitis can leave hearing loss or cognitive problems.'},
'disease:hsve':{
 overview:['Herpes simplex encephalitis is infection and inflammation of the brain by herpes simplex virus, usually HSV-1. It typically targets the medial temporal lobes, insula and orbitofrontal cortex, the limbic regions, and without treatment it is often fatal.'],
 brain:[['hippocampus','p','Destruction of the hippocampus causes lasting memory loss.'],['entorhinal','p','Medial temporal damage disrupts memory input.'],['amygdala','p','Limbic damage can change emotion and behavior.'],['antinsula','s','Often involved.'],['ofc','s','Often involved, affecting behavior.']],
 symptoms:['Fever and headache','Confusion and personality change','Seizures','Memory problems','Smell or taste hallucinations'],
 diagnosis:'MRI showing temporal lobe changes and PCR testing of spinal fluid for HSV.',
 causes:['HSV-1 reaching the brain, possibly via the olfactory or trigeminal nerves.'],
 treatment:['Urgent IV acyclovir, started as soon as it is suspected.'],
 course:'Many survivors have lasting memory or behavior problems.'},
'disease:gbm':{
 overview:['Glioblastoma is the most common and aggressive primary brain cancer in adults. It grows from glial cells and infiltrates surrounding brain tissue, so it cannot be completely removed.'],
 brain:[['frontal','p','One of the most common locations.'],['temporal','p','One of the most common locations.'],['callosum','s','Tumors that cross it to both sides are called "butterfly gliomas."']],
 symptoms:['Headaches, often worse in the morning','Seizures','Personality or memory changes','Weakness, speech or vision problems depending on location','Nausea'],
 diagnosis:'MRI followed by biopsy or surgery; molecular markers such as IDH and MGMT status guide treatment and prognosis.',
 causes:['Mostly unknown; prior radiation to the head is a known risk factor.'],
 treatment:['Surgery, then radiation and temozolomide chemotherapy; tumor-treating fields for some patients.'],
 course:'Median survival is about 15 months with treatment.'},
'disease:meningioma':{overview:['Meningiomas grow from the meninges. They are the most common primary brain tumor; most are slow-growing and benign and cause symptoms by pressing on nearby brain tissue.'],
 brain:[['frontal','s','Convexity and falx meningiomas often press on the frontal lobes.'],['olfactory','s','Olfactory groove meningiomas cause loss of smell.']],
 diagnosis:'MRI typically shows a well-defined tumor attached to the dura.',
 causes:['Mostly unknown; prior radiation and NF2 raise risk.'],
 treatment:['Observation, surgery or radiation.'],
 course:'Usually good outcomes.'},
'disease:pitadenoma':{overview:['Pituitary adenomas are usually benign tumors of the pituitary gland. Some release too much hormone; larger ones press on the optic chiasm above, causing loss of peripheral vision.'],
 brain:[['pituitary','p','The tumor\'s origin, which may overproduce or underproduce hormones.'],['hypothalamus','s','Large tumors can press upward on it.']],
 diagnosis:'MRI and hormone blood tests; visual field testing.',
 causes:['Mostly unknown; a few are part of inherited syndromes.'],
 treatment:['Medications, surgery through the nose, or radiation.'],
 course:'Usually good outcomes.'},
'disease:hydrocephalus':{overview:['Hydrocephalus is a buildup of cerebrospinal fluid that enlarges the ventricles and raises pressure on the brain. It can be present at birth or develop later.','Normal pressure hydrocephalus in older adults causes a classic triad: walking problems, urinary incontinence and cognitive decline, and is one of the few treatable causes of dementia.'],
 brain:[['latvent','p','Enlarge as fluid builds up, stretching nearby white matter.'],['thirdvent','p','Enlarges.'],['aqueduct','p','The most common site of blockage.'],['fourthvent','s','Enlarges if blockage is further downstream.']],
 diagnosis:'CT or MRI shows enlarged ventricles; a lumbar drain trial predicts response in normal pressure hydrocephalus.',
 causes:['Blocked CSF flow, poor absorption after bleeding or infection, or unknown causes.'],
 treatment:['A shunt to drain CSF or endoscopic third ventriculostomy.'],
 course:'Outcomes depend on cause and timing.'},
'disease:cp':{overview:['Cerebral palsy is a group of lifelong movement and posture disorders caused by damage to the developing brain before, during or soon after birth. The damage does not worsen, though its effects change with growth.'],
 brain:[['m1','p','Damage to motor areas or their pathways causes spastic types.'],['latvent','s','Periventricular white matter injury is common in premature babies.'],['putamen','s','Damage causes dyskinetic types.'],['thalamus','s','Often damaged alongside the basal ganglia.'],['cerebhemi','s','Damage causes ataxic types.']],
 diagnosis:'Clinical assessment and MRI, often confirmed by age 2.',
 causes:['Premature birth, low birth weight, infections in pregnancy, lack of oxygen and strokes in the baby.'],
 treatment:['Physical, occupational and speech therapy; botulinum toxin and baclofen; orthopedic surgery; assistive devices.'],
 course:'Lifelong; many people lead independent lives.'},
'disease:et':{overview:['Essential tremor causes rhythmic shaking, mainly of both hands during action. It is the most common movement disorder and often runs in families.'],
 brain:[['cerebhemi','p','Cerebellar circuit dysfunction produces the oscillation that drives tremor.'],['dentate','p','Abnormal cerebellar output.'],['ventthal','p','The ventral intermediate nucleus relays the tremor signal and is the treatment target.']],
 diagnosis:'Clinical diagnosis.',
 causes:['Strongly familial in about half of cases.'],
 treatment:['Propranolol and primidone; deep brain stimulation or focused ultrasound for severe cases.'],
 course:'Slowly progressive.'},
'disease:dystonia':{overview:['Dystonia causes sustained or intermittent muscle contractions producing twisting movements and abnormal postures. It can be focal, such as cervical dystonia or writer\'s cramp, or generalized.'],
 brain:[['putamen','p','Abnormal basal ganglia signaling disrupts selection of muscle activity.'],['gp','p','The internal globus pallidus is the deep brain stimulation target.'],['cerebhemi','s','Cerebellar circuits are increasingly implicated.'],['s1','s','Altered sensory body maps.']],
 diagnosis:'Clinical diagnosis; genetic testing in early-onset cases.',
 causes:['Genetics, brain injury, medications or unknown.'],
 treatment:['Botulinum toxin injections; medications; deep brain stimulation.'],
 course:'Varies by type.'},
'disease:ataxia':{overview:["This group of inherited diseases, including the spinocerebellar ataxias and Friedreich's ataxia, causes progressive loss of coordination as the cerebellum and its connections degenerate."],
 brain:[['cerebhemi','p','Degeneration causes limb clumsiness.'],['vermis','p','Degeneration causes unsteady walking.'],['dentate','s',"Degeneration, especially in Friedreich's ataxia."],['pons','s','Involved in several SCA types.']],
 diagnosis:'MRI and genetic testing.',
 causes:['Gene mutations, often repeat expansions.'],
 treatment:["Physical and speech therapy; omaveloxolone for Friedreich's ataxia."],
 course:'Progressive over years to decades.'},
'disease:wks':{overview:['Wernicke-Korsakoff syndrome is brain damage caused by thiamine deficiency. The acute stage (Wernicke encephalopathy) causes confusion, eye movement problems and unsteadiness; untreated, it can lead to Korsakoff syndrome, with severe lasting memory loss and confabulation.'],
 brain:[['mammillary','p','Shrinkage disrupts the Papez memory circuit.'],['mdthal','p','Damage contributes to amnesia.'],['antthal','s','Disrupts the memory circuit.'],['fornix','s','Memory circuit disconnection.'],['vermis','s','Damage causes unsteady walking.'],['midbrain','s','Damage near the aqueduct affects eye movements.']],
 diagnosis:'Clinical diagnosis; MRI may show changes around the third ventricle and aqueduct.',
 causes:['Thiamine deficiency from heavy alcohol use, malnutrition, vomiting or bariatric surgery.'],
 treatment:['Urgent high-dose IV thiamine.'],
 course:'Early treatment can reverse Wernicke symptoms; Korsakoff memory loss often persists.'},
'disease:wilson':{overview:["Wilson's disease is an inherited disorder in which the body cannot remove copper, which builds up in the liver and brain, causing liver disease, movement disorders and psychiatric symptoms."],
 brain:[['putamen','p','Copper deposits are most prominent here, disrupting movement control.'],['gp','s','Copper damage.'],['caudate','s','Copper damage.'],['midbrain','s','Can produce the "face of the giant panda" sign on MRI.'],['pons','s','Involved in some cases.']],
 diagnosis:'Blood ceruloplasmin, urine copper, eye exam for Kayser-Fleischer rings, liver biopsy and genetic testing.',
 causes:['ATP7B mutations, inherited in an autosomal recessive pattern.'],
 treatment:['Lifelong chelation (penicillamine or trientine) or zinc, and a low-copper diet.'],
 course:'With early treatment, life expectancy can be near normal.'}
});
