window.COND_EXT=window.COND_EXT||{};
Object.assign(window.COND_EXT,{
'psych:adhd':{
 overview:[
  'ADHD is a neurodevelopmental condition defined by a persistent pattern of inattention, hyperactivity and impulsivity that is more severe than expected for a person\'s age and gets in the way of school, work or relationships. Symptoms must begin before age 12, show up in more than one setting, and last at least six months.',
  'It is best understood as a difference in self-regulation rather than a lack of knowledge or effort. People with ADHD usually know what they should do; the difficulty is getting the brain to start, sustain and stop behavior on demand, especially when a task is boring or the reward is far away. The same brain can lock onto something highly stimulating for hours, which is why "hyperfocus" and inattention can coexist.',
  'ADHD frequently continues into adulthood, where hyperactivity often turns into inner restlessness, and disorganization, time blindness and emotional reactivity become the main problems. It commonly co-occurs with anxiety, depression, learning disorders, autism and substance use.'],
 brain:[
  ['dlpfc','p','Holds goals and instructions in working memory. In ADHD it is less active during demanding tasks and matures later, so plans and instructions "drop out" of mind, which shows up as forgetfulness, losing track mid-task and difficulty organizing multi-step work.'],
  ['vlpfc','p','Acts as the brain\'s brake for stopping an action. Weaker right VLPFC activation during stop-signal tasks means a response that has already started is harder to cancel, producing blurting, interrupting and acting before thinking.'],
  ['caudate','p','Part of the striatum that links the prefrontal cortex to action selection. It is smaller in many children with ADHD and receives less effective dopamine signaling, which weakens the loop that keeps the brain engaged with the current goal. Stimulant medications boost dopamine here.'],
  ['nacc','s','Encodes how rewarding something is expected to be. In ADHD it responds weakly to rewards that are delayed, so immediate rewards win out, which helps explain procrastination and the pull of phones and games over homework.'],
  ['acc','s','Monitors errors and signals when more effort is needed. Reduced error-related activity means mistakes and drifting attention are noticed later, so careless errors pile up.'],
  ['pcc','s','A hub of the default mode network, which should quiet down during tasks. In ADHD it keeps intruding, so attention drifts into daydreaming during lectures or reading.'],
  ['cerebhemi','s','Supports timing and the automatic sequencing of behavior. Smaller cerebellar volume reported in several studies may contribute to poor time estimation and clumsiness.']],
 symptoms:['Difficulty sustaining attention on tasks that are not inherently interesting','Careless mistakes and overlooking details','Losing things and forgetting appointments or tasks','Poor time management and chronic lateness ("time blindness")','Fidgeting, restlessness or feeling driven by a motor','Talking excessively, interrupting and difficulty waiting a turn','Strong preference for immediate rewards; procrastination','Emotional reactivity and frustration intolerance','Hyperfocus on highly engaging activities'],
 diagnosis:'Diagnosis is clinical: there is no blood test or brain scan for ADHD. A clinician gathers a detailed history, uses standardized rating scales from multiple informants (parents, teachers, partners), confirms symptoms started in childhood and cause impairment in at least two settings, and rules out other explanations such as sleep problems, anxiety, depression, hearing or vision problems, thyroid disease or learning disorders. Children need six or more symptoms in a domain; people aged 17 and older need five.',
 types:['Predominantly inattentive presentation: mainly attention and organization problems, without much hyperactivity. It is more often missed, especially in girls and women.','Predominantly hyperactive-impulsive presentation: mainly restlessness and impulsivity; more common in young children.','Combined presentation: significant symptoms in both domains. A person\'s presentation can change over time.'],
 causes:['ADHD is among the most heritable psychiatric conditions, with twin studies estimating heritability around 70–80%. It is polygenic: many common gene variants, including some involved in dopamine signaling, each add a small amount of risk.','Environmental factors that raise risk include preterm birth and low birth weight, prenatal exposure to tobacco, alcohol or some medications, lead exposure, and early severe deprivation. Parenting style, screen time and sugar do not cause ADHD, though environment can make symptoms better or worse.'],
 treatment:['Stimulant medications (methylphenidate and amphetamine formulations) are the most effective treatment, helping about 70–80% of people. They increase dopamine and norepinephrine signaling in prefrontal and striatal circuits, strengthening attention and impulse control while the medication is active.','Non-stimulant options include atomoxetine and viloxazine (norepinephrine reuptake inhibitors) and guanfacine and clonidine (alpha-2 agonists that strengthen prefrontal signaling). These can suit people who do not tolerate stimulants or who have tics or substance use concerns.','Behavioral parent training is first-line for preschool children. School supports (504 plans or IEPs), organizational skills training, coaching and CBT for adults build routines and external structure: planners, timers, breaking tasks into small steps and making rewards more immediate.'],
 course:'Symptoms often decline with age, especially hyperactivity, but around half to two-thirds of children continue to have impairing symptoms as adults. Untreated ADHD is associated with higher rates of school dropout, accidents, job instability and substance use; treatment reduces many of these risks. Many adults find ways to build on strengths such as creativity, energy and the ability to hyperfocus.'},

'psych:asd':{
 overview:[
  'Autism spectrum disorder is a lifelong neurodevelopmental difference in how a person communicates, relates to others and processes the world. Diagnosis requires persistent differences in social communication and interaction, together with restricted or repetitive behaviors, interests or sensory responses, present from early childhood.',
  'Autism is a spectrum in two senses: abilities vary enormously, from people who need around-the-clock support and do not use spoken language to people with advanced degrees who mainly struggle with social expectations and sensory overload; and each person has their own mix of strengths and challenges. Common strengths include attention to detail, pattern recognition, honesty and deep expertise in areas of interest.',
  'Many autistic people and advocates favor a neurodiversity view: autism is a natural variation in brain development, and much of the disability comes from environments that do not accommodate it. Support focuses on communication, independence, wellbeing and reducing distress rather than making a person appear non-autistic.'],
 brain:[
  ['amygdala','s','Flags socially and emotionally important information. Many autistic children show unusually fast amygdala growth in early childhood and different responses to faces and eye contact, which may make eye contact feel uncomfortable and change which social cues get noticed.'],
  ['stg','s','The superior temporal sulcus decodes gaze direction, voices and body movement. Atypical activity here may make it harder to read intentions from subtle nonverbal signals in real time.'],
  ['fusiform','s','Specializes in recognizing faces as a whole. Some studies find reduced face-specific responses, with faces processed more like objects, which can make recognizing people and expressions more effortful.'],
  ['dmpfc','s','Builds models of what others are thinking (theory of mind). Different activation during these tasks fits with difficulty guessing unspoken intentions, though autistic people often understand each other well, a pattern called the "double empathy" problem.'],
  ['antinsula','s','Decides which internal and external signals are important. Differences here are linked to sensory over- or under-responsiveness and difficulty identifying one\'s own emotions (alexithymia).'],
  ['cerebhemi','s','The cerebellum shapes prediction and timing in movement, language and social interaction. Reduced Purkinje cell numbers are one of the most consistent post-mortem findings and may contribute to motor clumsiness and difficulty adapting to unpredictable situations.'],
  ['callosum','s','Connects the hemispheres. A smaller corpus callosum and altered long-range connectivity may favor detailed local processing over integrating information across the brain.']],
 symptoms:['Differences in back-and-forth conversation and shared attention','Less use or different use of eye contact, gestures and facial expressions','Difficulty understanding unwritten social rules or developing friendships in typical ways','Repetitive movements or speech, including stimming, which often helps self-regulation','Strong need for routine and distress at unexpected changes','Intense, focused interests','Sensory over- or under-sensitivity to sound, light, touch, taste, smell or pain','Meltdowns or shutdowns when overwhelmed'],
 diagnosis:'Diagnosis is based on developmental history and direct observation, often with tools such as the ADOS-2 and ADI-R. Screening is recommended at 18 and 24 months, and reliable diagnosis is possible by age 2, though many people, especially girls, women and those without intellectual disability, are diagnosed much later. Clinicians specify the support level needed (1–3) and whether there is intellectual or language impairment. Hearing tests and genetic testing are commonly recommended.',
 types:['DSM-5 combined earlier labels, including Asperger syndrome and pervasive developmental disorder, into a single autism spectrum diagnosis. Instead of subtypes it uses support levels: Level 1 (requiring support), Level 2 (requiring substantial support) and Level 3 (requiring very substantial support), rated separately for social communication and restricted or repetitive behaviors.'],
 causes:['Autism is highly heritable (estimates around 60–90%). Hundreds of genes are involved, many affecting synapse formation and brain development. About 10–20% of cases are linked to an identifiable genetic change, such as fragile X syndrome, tuberous sclerosis or specific copy-number variants.','Factors associated with modestly higher likelihood include older parental age, very preterm birth and some prenatal exposures such as valproate. Very large studies have shown that vaccines do not cause autism. Parenting style does not cause autism.'],
 treatment:['There is no medication for autism itself. Support is individualized: speech and language therapy (including augmentative and alternative communication devices), occupational therapy for sensory and motor needs, and developmental or naturalistic behavioral approaches in early childhood.','Practical accommodations make a large difference: predictable routines, visual schedules, quiet spaces, noise-reducing headphones, clear direct communication and workplace adjustments. Co-occurring conditions such as anxiety, depression, ADHD, epilepsy, sleep and gastrointestinal problems are common and are treated in their own right. Risperidone and aripiprazole are approved for severe irritability.'],
 course:'Autism is lifelong, but skills and needs change over time, and many people develop strong coping strategies. Outcomes vary widely. Autistic adults face high rates of anxiety, depression and unemployment, much of it linked to lack of support and acceptance, which makes accommodation and community important.'},

'psych:tourette':{
 overview:[
  "Tourette's syndrome is the best-known tic disorder. It is diagnosed when a person has had multiple motor tics and at least one vocal tic for more than a year, starting before age 18, not caused by a substance or another medical condition. Tics usually start around ages 5–7 and peak in severity around 10–12.",
  'Tics are sudden, rapid, repetitive movements or sounds. They are not fully voluntary, but they are not completely involuntary either: most people feel a building urge before a tic and can suppress it briefly, though this takes effort and the urge grows. Tics change over time, wax and wane, and worsen with stress, excitement or fatigue.',
  "Most people with Tourette's also have at least one other condition, most commonly ADHD, OCD, anxiety or learning difficulties, and these often cause more impairment than the tics themselves."],
 brain:[
  ['caudate','p','Part of the circuit that filters out unwanted movement programs. A smaller caudate and abnormal cortico-striatal signaling let fragments of movement or sound "leak through" as tics, and smaller caudate volume in childhood has been linked to worse tics later.'],
  ['sma','p','Prepares self-initiated movements. It becomes active shortly before each tic and is thought to generate the premonitory urge, the feeling that something must be done.'],
  ['putamen','s','Stores motor habits. Tics resemble overlearned habits, which may explain why they become ingrained and why habit-based therapy (CBIT) helps.'],
  ['antinsula','s','Turns body sensations into feelings. It contributes to the itch-like or pressure-like sensory part of the premonitory urge.'],
  ['gp','s','The main output gate of the basal ganglia. Deep brain stimulation here can reduce severe tics, showing that this output is part of the tic-generating loop.'],
  ['thalamus','s','Relays basal ganglia output back to the cortex. Thalamic nuclei are another deep brain stimulation target, and the loop through the thalamus is what lets tics repeat.']],
 symptoms:['Simple motor tics: eye blinking, grimacing, head jerking, shoulder shrugging','Complex motor tics: touching, jumping, copying others\' movements (echopraxia)','Simple vocal tics: sniffing, throat clearing, grunting','Complex vocal tics: words, phrases, repeating others (echolalia) or oneself (palilalia)','Coprolalia (socially inappropriate words) in a minority','Premonitory urge before tics and relief afterward','Ability to suppress tics briefly, often followed by a rebound'],
 diagnosis:"Diagnosis is clinical, based on observing tics and the history of their onset and duration. Videos recorded at home help because tics are often suppressed in the doctor's office. Clinicians screen for ADHD, OCD and anxiety, and may order tests only if another cause is suspected. Tic disorders with only motor or only vocal tics are diagnosed as persistent (chronic) motor or vocal tic disorder; tics for less than a year are provisional tic disorder.",
 causes:["Tourette's is strongly genetic, with heritability estimated around 70–80%, involving many genes. Risk factors include male sex (3–4 times more common), maternal smoking, prenatal stress and low birth weight. A possible link with streptococcal infection (PANDAS) remains controversial."],
 treatment:['Many people need only education, reassurance and an understanding school or workplace. Comprehensive Behavioral Intervention for Tics (CBIT) teaches awareness of the premonitory urge and a competing response that is physically incompatible with the tic; it reduces tics as effectively as many medications.','When medication is needed: alpha-2 agonists (guanfacine, clonidine) are often tried first, especially with ADHD; dopamine-blocking drugs such as aripiprazole, haloperidol and pimozide are more powerful but have more side effects; VMAT2 inhibitors and botulinum toxin injections help some people. Deep brain stimulation is reserved for severe, treatment-resistant adult cases.'],
 course:'Tics typically peak in early adolescence. By early adulthood, about a third of people are tic-free and another third improve substantially, though a minority continue to have significant tics. Co-occurring ADHD, OCD and anxiety often need ongoing attention.'},

'psych:dyslexia':{
 overview:['Dyslexia is a specific learning disorder in which a person has persistent difficulty with accurate and fluent word reading, decoding and spelling, despite adequate intelligence, vision and teaching. It is the most common learning disorder.','The core problem for most people is phonological: breaking spoken words into their individual sounds and linking those sounds to letters. Because reading depends on this mapping, words have to be effortfully sounded out instead of recognized automatically, which slows reading and uses up attention that would otherwise go to understanding.','Dyslexia is not a vision problem and has nothing to do with reading letters backward, which is common in all young readers. Many people with dyslexia have strong reasoning, oral language and big-picture thinking, and listening comprehension is often much better than reading comprehension.'],
 brain:[['supramarginal','p','Part of the left temporoparietal network that links letters to speech sounds. It is consistently underactive during reading in dyslexia, matching the core phonological difficulty of sounding out words.'],['fusiform','p','Contains the visual word form area, which learns to recognize familiar written words instantly. It responds weakly in dyslexia because letter-sound links never became automatic, so even familiar words are read slowly.'],['broca','s','Supports sounding out and articulating words. It is often more active in dyslexic readers, likely compensating by subvocalizing words.'],['angular','s','Connects written words to meaning. Weaker connections with visual and language areas slow comprehension of written text.'],['cerebhemi','s','Helps make skills automatic. The debated cerebellar theory proposes that reduced automatization contributes to slow, effortful reading.']],
 symptoms:['Slow, effortful, inaccurate reading','Difficulty sounding out unfamiliar words','Persistent spelling errors','Trouble with rhyming and splitting words into sounds in early childhood','Difficulty learning letter names and sounds','Avoiding reading aloud','Listening comprehension stronger than reading comprehension'],
 diagnosis:'Assessment by an educational psychologist or specialist measures phonological awareness, decoding of real and nonsense words, reading fluency, spelling and comprehension, and compares them with oral language and reasoning. Diagnosis requires difficulties that persist for at least six months despite targeted help. Early screening in kindergarten and first grade allows intervention before a child falls behind.',
 causes:['Dyslexia is strongly familial: a child with an affected parent has a much higher risk. Heritability is roughly 40–70%, involving many genes that affect early brain development. Early speech and language delays are a warning sign.'],
 treatment:['The most effective intervention is explicit, systematic, multisensory instruction in phonics and phonological awareness, often called structured literacy (for example Orton-Gillingham-based programs). Starting early (kindergarten to second grade) gives the best results, but older students and adults also improve.','Accommodations level the field: extra time, audiobooks and text-to-speech, speech-to-text for writing, and reduced penalties for spelling. Brain imaging studies show that successful reading intervention increases activity in the left temporoparietal and fusiform reading network.'],
 course:'Dyslexia is lifelong, but with good instruction most people learn to read accurately, though reading may remain slower than average. Early identification reduces the risk of the low self-esteem and school avoidance that often follow years of struggling.'},

'psych:schizophrenia':{
 overview:['Schizophrenia is a serious mental illness that affects perception, thinking, motivation and the sense of what is real. It usually begins in the late teens to early 30s, often after a prodrome of months to years with social withdrawal, declining performance and unusual ideas.','Symptoms fall into three groups. Positive symptoms are experiences added to normal life, such as hallucinations, delusions and disorganized thinking. Negative symptoms are losses: reduced motivation, pleasure, speech and emotional expression. Cognitive symptoms include problems with attention, working memory and planning. Negative and cognitive symptoms often affect daily life the most and respond least to medication.','Schizophrenia is not "split personality," and most people with it are not violent; they are far more likely to be victims of violence. With early, consistent treatment and support, many people have long periods of recovery, work and maintain relationships.'],
 brain:[['caudate','p','The associative striatum, mostly in the caudate, receives too much dopamine in psychosis. This is thought to make ordinary events feel strangely significant ("aberrant salience"), and delusions develop as explanations for those experiences. Antipsychotics work mainly by blocking dopamine D2 receptors here.'],['dlpfc','p','Holds and manipulates information in working memory. It is underactive during demanding tasks (hypofrontality), partly from too little dopamine signaling in the cortex, producing the cognitive symptoms: trouble concentrating, planning and following conversations.'],['hippocampus','p','Hyperactivity in CA1 often appears early and may drive excess dopamine release in the striatum. It also shrinks over the illness, linked to memory problems.'],['stg','p','Processes speech sounds. Reduced gray matter and spontaneous activity here during hallucinations suggest the brain misattributes its own inner speech to an external voice.'],['latvent','p','Enlarged ventricles are among the oldest replicated findings. They reflect reduced surrounding brain tissue rather than causing symptoms.'],['mdthal','s','Relays and synchronizes information with the prefrontal cortex. Reduced thalamocortical connectivity may disrupt the filtering of sensory input and organized thought.'],['vta','s','The dopamine source for the mesolimbic and mesocortical pathways, whose imbalance underlies positive and negative symptoms.'],['acc','s','Monitors conflict and errors. Reduced activity is linked to difficulty recognizing that one\'s own perceptions or beliefs might be mistaken.']],
 symptoms:['Hallucinations, most often hearing voices commenting or conversing','Delusions such as being watched, followed, controlled or having special powers','Disorganized speech that jumps between topics','Disorganized or unusual behavior','Reduced motivation and social withdrawal','Flat facial expression and speech','Reduced pleasure (anhedonia)','Problems with attention, memory and planning','Reduced insight into being ill'],
 diagnosis:'Diagnosis requires at least two core symptoms (delusions, hallucinations, disorganized speech, grossly disorganized or catatonic behavior, or negative symptoms) for a significant part of a month, with at least one being delusions, hallucinations or disorganized speech, and continuous signs of illness for at least six months. Clinicians rule out substance-induced psychosis, mood disorders with psychotic features, and medical causes such as brain tumors, autoimmune encephalitis and thyroid disease, often with blood tests and brain imaging.',
 types:['DSM-5 removed the older subtypes (paranoid, disorganized, catatonic, undifferentiated) because they were unreliable. Related diagnoses on the spectrum include brief psychotic disorder (under a month), schizophreniform disorder (one to six months), schizoaffective disorder and delusional disorder.'],
 causes:['Schizophrenia is highly heritable, around 80%. A person with an affected identical twin has about a 40–50% risk, compared with under 1% in the general population. Hundreds of common variants add small risks, and rare variants, such as the 22q11.2 deletion, add large risks.','Environmental factors include pregnancy and birth complications, prenatal infection or malnutrition, childhood adversity, migration and urban upbringing, and heavy use of high-potency cannabis in adolescence. The leading model is neurodevelopmental: early vulnerability combined with changes during adolescent brain maturation, including excessive synaptic pruning.'],
 treatment:['Antipsychotic medication is the foundation of treatment and reduces positive symptoms and relapse risk. Clozapine is the most effective option for treatment-resistant illness, which affects about a third of people. Long-acting injectable forms help people who struggle with daily pills.','Coordinated specialty care for first-episode psychosis combines medication, CBT for psychosis, family education, supported employment and education, and case management, and improves outcomes. Cognitive remediation, social skills training and peer support help with negative and cognitive symptoms. Physical health care matters: life expectancy is reduced by 10–20 years, mostly due to heart disease and smoking.'],
 course:'The course varies. Roughly a quarter of people recover well, about half have ongoing symptoms with periods of improvement and relapse, and others have persistent disability. Shorter time to treatment, good support and staying on treatment predict better outcomes.'},

'psych:schizoaffective':{
 overview:['Schizoaffective disorder combines symptoms of schizophrenia, such as hallucinations or delusions, with major mood episodes of depression or mania. To meet the diagnosis, psychotic symptoms must also occur for at least two weeks without a mood episode, and mood episodes must be present for the majority of the illness.','It sits between schizophrenia and bipolar disorder, sharing genetic risk and features with both, and the diagnosis can be unstable over time. Outcomes tend to be somewhat better than in schizophrenia but worse than in mood disorders with psychosis.'],
 brain:[['dlpfc','s','Shows the same reduced working-memory activity as in schizophrenia, contributing to cognitive symptoms.'],['hippocampus','s','Volume reductions similar to schizophrenia and bipolar disorder may contribute to memory problems and to the dopamine dysregulation that drives psychosis.'],['amygdala','s','Altered emotional reactivity, as in mood disorders, may contribute to the intense mood episodes.'],['latvent','s','Mild enlargement reflects reduced surrounding brain tissue, as in schizophrenia.']],
 symptoms:['Hallucinations or delusions','Major depressive episodes: low mood, hopelessness, low energy','Manic episodes (bipolar type): elevated or irritable mood, reduced sleep, racing thoughts','Disorganized thinking','Social and occupational decline'],
 diagnosis:'The diagnosis depends on careful timing of psychotic and mood symptoms over the whole illness, often requiring longitudinal observation and records. Medical and substance-related causes are ruled out.',
 types:['Bipolar type: includes manic episodes, with or without depression.','Depressive type: only major depressive episodes.'],
 causes:['Genetic risk overlaps with both schizophrenia and bipolar disorder. Environmental stressors and substance use can trigger episodes.'],
 treatment:['Treatment combines an antipsychotic (paliperidone is FDA-approved specifically for this condition) with a mood stabilizer for the bipolar type or an antidepressant for the depressive type. Psychotherapy, family education, case management and vocational support help long-term recovery.'],
 course:'Usually long-term, with episodes of psychosis and mood disturbance. Outcomes are generally intermediate between schizophrenia and bipolar disorder, and many people achieve stable functioning with treatment.'},

'psych:delusional':{
 overview:['Delusional disorder involves one or more fixed, false beliefs lasting at least a month, without the other major symptoms of schizophrenia such as prominent hallucinations or disorganized speech. Outside the delusion and its consequences, people often function surprisingly well and may seem completely ordinary.','Delusions are often plausible-sounding (non-bizarre), such as being followed, cheated on or having a serious illness, which can make them hard to recognize. People rarely see the belief as a symptom and usually come to attention because of conflict, legal problems or repeated medical visits.'],
 brain:[['dlpfc','s','Evaluates beliefs against evidence. Research suggests a "jumping to conclusions" reasoning style and weaker belief updating, which may let an initial suspicion harden into certainty (limited studies).'],['caudate','s','As in other psychoses, excess striatal dopamine may make certain events feel unusually meaningful, which a delusion then explains (proposed).'],['acc','s','Monitors conflicting information. Reduced conflict monitoring may make it easier to dismiss evidence against the belief (limited evidence).']],
 symptoms:['A persistent, fixed belief that does not change with evidence','Behavior consistent with the belief, such as investigating a partner or contacting authorities','Irritability or low mood related to the belief','Little or no hallucination','Otherwise intact functioning'],
 diagnosis:'Clinicians confirm the belief has lasted at least a month, rule out schizophrenia, mood disorders with psychosis, dementia and substance use, and assess risk related to the belief.',
 types:['Persecutory: being conspired against or harmed (most common).','Jealous: a partner is unfaithful.','Erotomanic: someone, often of higher status, is in love with the person.','Grandiose: having great talent, knowledge or a special relationship.','Somatic: having a bodily defect or illness.','Mixed or unspecified.'],
 causes:['Causes are not well understood. Risk factors include family history of psychotic disorders or paranoid traits, social isolation, immigration, hearing impairment and stressful life events.'],
 treatment:['Building a trusting relationship comes first, since confronting the belief directly usually backfires. Antipsychotic medication helps many people, and CBT can gently explore the evidence and reduce distress and preoccupation.'],
 course:'The course varies: some people recover fully, while others have a chronic course with fluctuations. Functioning is often better preserved than in schizophrenia.'},

'psych:bipolar':{
 overview:['Bipolar disorder causes episodes of abnormally elevated or irritable mood and energy (mania or hypomania) and, in most people, episodes of major depression. Between episodes many people return to their usual baseline, though some have ongoing milder symptoms.','Mania is more than a good mood: it involves a marked increase in energy and activity with reduced need for sleep, racing thoughts, rapid speech, inflated confidence and risky decisions that can damage finances, relationships and health. Severe mania can include psychosis and usually requires hospitalization. Depressive episodes are often longer and are the main source of disability.','Bipolar disorder usually starts in the late teens or twenties. It is often misdiagnosed as depression at first, because people more often seek help when depressed, which matters because antidepressants alone can trigger mania.'],
 brain:[['amygdala','p','Detects emotional significance. It is overreactive to emotional stimuli in both mania and depression, amplifying emotional responses and making mood harder to keep stable.'],['vlpfc','p','Regulates emotion from the top down. Reduced activity weakens control over the amygdala, so emotional reactions run unchecked, especially during mood episodes.'],['acc','p','The subgenual ACC regulates mood and links emotion to the body. Reduced volume and altered activity are found in both bipolar disorder and depression, linked to mood swings and depressive episodes.'],['nacc','s','Drives reward seeking. Heightened reward sensitivity is thought to contribute to the goal-driven, risk-taking behavior of mania; it can rise before episodes.'],['hippocampus','s','Volume reductions are linked to memory problems; lithium treatment is associated with larger hippocampal volume, possibly through neuroprotective effects.'],['callosum','s','White matter connecting the hemispheres shows reduced integrity, which may disrupt coordination between emotion and regulation networks.']],
 symptoms:['Mania: elevated, expansive or irritable mood for at least a week','Greatly reduced need for sleep without feeling tired','Racing thoughts, rapid pressured speech, jumping between ideas','Grandiosity and inflated self-esteem','Risky behavior: spending sprees, reckless driving, impulsive decisions','Hypomania: the same features, milder and shorter (at least 4 days), without severe impairment','Depression: low mood, loss of interest, fatigue, hopelessness, changes in sleep and appetite','Psychotic symptoms in severe episodes'],
 diagnosis:'Diagnosis is based on a careful history of mood episodes, often with input from family, since people may not recognize hypomania. Mood charts help. Clinicians rule out thyroid disease, substance-induced mood changes and medications such as steroids. Bipolar I requires at least one manic episode; bipolar II requires at least one hypomanic and one major depressive episode, and no full mania.',
 types:['Bipolar I disorder: at least one manic episode; depressive episodes are common but not required.','Bipolar II disorder: hypomanic and major depressive episodes, never full mania. Not a milder disorder: depression often dominates.','Cyclothymic disorder: chronic fluctuating hypomanic and depressive symptoms below the threshold of full episodes.','Specifiers include rapid cycling (four or more episodes a year), mixed features and seasonal pattern.'],
 causes:['Bipolar disorder is among the most heritable psychiatric disorders (about 60–85%), with genetic overlap with schizophrenia and depression. Triggers include sleep disruption and shift work, stressful events, substance use, childbirth and antidepressants used without a mood stabilizer.'],
 treatment:['Mood stabilizers are the foundation. Lithium is the gold standard and reduces both mania and suicide risk; valproate and carbamazepine treat mania; lamotrigine prevents depressive episodes. Several antipsychotics (such as quetiapine, lurasidone, cariprazine and olanzapine) treat mania or bipolar depression.','Psychotherapy (CBT, family-focused therapy, interpersonal and social rhythm therapy) and psychoeducation reduce relapses. Protecting sleep and a regular daily routine are powerful preventive tools. Lithium and valproate need blood monitoring, and valproate carries serious risks in pregnancy.'],
 course:'Bipolar disorder is usually lifelong but highly treatable. Without treatment, episodes tend to become more frequent. Many people live full lives with consistent treatment and early recognition of warning signs such as reduced sleep.'},

'psych:cyclothymia':{
 overview:['Cyclothymic disorder involves at least two years (one year in children and teens) of frequent periods of hypomanic and depressive symptoms that never meet criteria for full episodes, with no more than two months symptom-free at a time.','Because the swings are milder, people may see them as personality ("moody," "unpredictable") rather than a disorder, but the constant instability can strain relationships and work. Around 15–50% of people later develop bipolar I or II.'],
 brain:[['amygdala','s','Emotional overreactivity similar to bipolar disorder may drive frequent mood shifts (limited direct research).'],['vlpfc','s','Weaker top-down regulation is proposed to allow mood to swing more easily.']],
 symptoms:['Frequent shifts between elevated and low moods','Periods of high energy, confidence and reduced sleep need','Periods of low mood, low energy and pessimism','Irritability','Rarely more than two months without symptoms'],
 diagnosis:'Diagnosed from a long-term history of symptoms, often with mood charting, after ruling out full mood episodes, substances and medical causes.',
 causes:['Strong family links with bipolar disorder suggest shared genetic risk.'],
 treatment:['Psychotherapy, mood tracking and regular sleep and routines help most. Mood stabilizers may be used, and antidepressants alone are used cautiously because they can trigger hypomania.'],
 course:'Usually chronic, beginning in adolescence or early adulthood, with a significant risk of progressing to bipolar I or II.'},

'psych:mdd':{
 overview:['Major depressive disorder is a common, serious and treatable mood disorder. It is diagnosed when, for at least two weeks, a person has depressed mood or loss of interest and pleasure most of the day, nearly every day, along with other symptoms that affect sleep, appetite, energy, concentration, self-worth and thoughts about death.','Depression is a whole-body illness. It changes how the brain processes reward, threat and memory, alters stress hormones, sleep and inflammation, and slows thinking and movement. It is not the same as ordinary sadness, and it is not a sign of weakness: people cannot simply decide to snap out of it.','It is one of the leading causes of disability worldwide. Episodes can be single or recurrent, and the more episodes a person has, the higher the risk of another, which makes continued treatment after recovery important.'],
 brain:[['acc','p','The subgenual ACC links emotion with bodily and stress responses. It is overactive in depression and normalizes with successful treatment; it has been a deep brain stimulation target in treatment-resistant depression. Overactivity is linked to persistent sadness and negative self-focus.'],['dlpfc','p','Provides cognitive control over emotion. It is underactive, especially on the left, which weakens the ability to shift attention away from negative thoughts and contributes to poor concentration and indecision. TMS treatment targets it.'],['amygdala','p','Detects emotional threat. It overreacts to negative faces and words and is slow to settle, biasing perception and memory toward the negative; antidepressants reduce this bias early in treatment.'],['hippocampus','p','Forms memories and helps shut off the stress response. Smaller volume is linked to recurrent or chronic depression, probably partly due to prolonged stress hormones; this may contribute to memory problems and weaker stress regulation.'],['nacc','s','Drives anticipation of reward. Blunted responses help explain anhedonia: activities stop feeling worth doing.'],['pvn','s','Starts the stress-hormone cascade. An overactive HPA axis with high cortisol is common, especially in severe depression, and may damage the hippocampus over time.'],['raphe','s','The source of serotonin. Most antidepressants increase serotonin signaling, though depression is not simply low serotonin; downstream changes in plasticity seem more important.'],['pcc','s','A default mode network hub. Excessive connectivity with the subgenual ACC is linked to rumination, repetitive dwelling on problems.']],
 symptoms:['Depressed mood most of the day, nearly every day','Markedly reduced interest or pleasure (anhedonia)','Significant change in appetite or weight','Insomnia or sleeping too much','Slowed movement and speech, or agitation','Fatigue and loss of energy','Feelings of worthlessness or excessive guilt','Difficulty thinking, concentrating or deciding','Recurrent thoughts of death or suicide'],
 diagnosis:'Diagnosis requires at least five of nine symptoms for two weeks, including depressed mood or loss of interest, causing significant distress or impairment. Clinicians use interviews and screening tools such as the PHQ-9, ask about past manic or hypomanic episodes to rule out bipolar disorder, assess suicide risk, and check for medical contributors such as thyroid disease, anemia, vitamin deficiencies and medications.',
 types:['Specifiers describe the pattern of an episode: with anxious distress, with melancholic features (loss of pleasure in nearly everything, early-morning waking, worse in the morning), with atypical features (mood that brightens with good news, oversleeping, increased appetite), with psychotic features, with peripartum onset (during pregnancy or within four weeks after birth) and with seasonal pattern.'],
 causes:['Depression arises from interacting factors. Genetics accounts for roughly 35–40% of risk. Stressful life events, especially losses and humiliations, childhood adversity and trauma, chronic illness, chronic pain, social isolation, hormonal changes and some medications all raise risk.','The "chemical imbalance" explanation is now considered too simple. Current models emphasize altered brain circuits, chronic stress responses, inflammation and reduced neuroplasticity; antidepressants likely work partly by restoring plasticity over weeks.'],
 treatment:['For mild to moderate depression, psychotherapy (CBT, behavioral activation, interpersonal therapy) and antidepressants are similarly effective; for more severe depression, the combination works best. SSRIs and SNRIs are usually first-line; others include bupropion, mirtazapine and vortioxetine. Medication typically takes 2–6 weeks to work and is continued for at least 6–12 months after recovery.','For treatment-resistant depression: switching or augmenting medications (for example with lithium or an atypical antipsychotic), transcranial magnetic stimulation, esketamine nasal spray, and electroconvulsive therapy, which is the most effective treatment for severe or psychotic depression. Exercise, regular sleep and social connection support recovery.'],
 course:'Most episodes improve with treatment within months. About half of people who have one episode will have another, and the risk rises with each episode, but maintenance treatment and therapy skills substantially reduce relapse. Anyone with thoughts of suicide should seek help immediately.'},

'psych:pdd':{
 overview:['Persistent depressive disorder, formerly called dysthymia, is depressed mood on most days for at least two years (one year in young people), with at least two other depressive symptoms. Symptoms can be milder than major depression, but their persistence makes them very disabling, and many people come to think of low mood as simply part of who they are.','Major depressive episodes can occur on top of it, sometimes called "double depression." Because it often begins in childhood or adolescence, it can shape personality, relationships and career choices.'],
 brain:[['amygdala','s','Heightened reactivity to negative emotion keeps the brain tuned toward threat and disappointment over the long term.'],['acc','s','Altered activity similar to major depression is linked to persistent low mood and negative self-focus.'],['dlpfc','s','Reduced regulation makes it harder to shift out of negative thinking patterns.']],
 symptoms:['Low mood most days for years','Low energy and fatigue','Low self-esteem','Poor concentration and indecision','Hopelessness','Changes in appetite or sleep','Feeling that this is "just how I am"'],
 diagnosis:'Diagnosed by history: depressed mood for most of the day, more days than not, for at least two years, never symptom-free for more than two months, with impairment, after ruling out bipolar disorder and medical causes.',
 causes:['Genetics, chronic stress, early adversity and temperament all contribute, similar to major depression. Early onset is common.'],
 treatment:['Combining psychotherapy with antidepressants tends to work better than either alone. CBASP (Cognitive Behavioral Analysis System of Psychotherapy) was developed specifically for chronic depression; CBT and interpersonal therapy also help.'],
 course:'Chronic and often long-lasting, but treatment can lead to remission, sometimes revealing to people for the first time what their baseline mood can be.'},

'psych:pmdd':{
 overview:['Premenstrual dysphoric disorder is a severe, cyclical mood disorder in which symptoms appear in the week or so before menstruation, improve within a few days after it starts and are minimal or absent in the week after. It is much more disabling than typical premenstrual syndrome.','Hormone levels in people with PMDD are usually normal. Instead, the brain appears unusually sensitive to normal rises and falls in estrogen, progesterone and its neuroactive metabolite allopregnanolone, which affects GABA signaling.'],
 brain:[['amygdala','s','Becomes more reactive in the late luteal phase, intensifying irritability, anxiety and emotional reactions.'],['hypothalamus','s','Coordinates the menstrual cycle and responds to cyclical hormone signals, which in PMDD trigger abnormal mood responses.'],['raphe','s','Supplies serotonin. Fast-acting benefit from SSRIs, sometimes within days, suggests altered serotonin sensitivity across the cycle.'],['dlpfc','s','Shows altered activity during emotion regulation in the luteal phase, weakening control over mood.']],
 symptoms:['Marked mood swings or sudden sadness','Irritability, anger or conflict','Depressed mood or hopelessness','Anxiety or tension','Loss of interest, fatigue, trouble concentrating','Changes in sleep and appetite, food cravings','Physical symptoms such as breast tenderness and bloating'],
 diagnosis:'Diagnosis requires daily symptom ratings across at least two cycles showing the cyclical pattern, with at least five symptoms including a core mood symptom, causing significant impairment.',
 causes:['An abnormal brain response to normal hormone changes, with genetic contributions, possibly involving the ESC/E(Z) gene complex that regulates responses to sex hormones.'],
 treatment:['SSRIs are first-line and can work when taken only in the luteal phase. Some hormonal contraceptives that suppress ovulation (such as those containing drospirenone) help. CBT, exercise and stress reduction support management. In severe cases, medications that suppress ovarian function are used.'],
 course:'Symptoms continue cyclically until menopause, sometimes worsening in the late reproductive years, but treatment is effective for most people.'},

'psych:sad':{
 overview:['Major depression with seasonal pattern, often called seasonal affective disorder, is depression that returns at the same time of year, usually beginning in fall or winter and lifting in spring, for at least two consecutive years. A less common summer pattern also exists.','It is more common at higher latitudes, where winter days are short. The leading explanation is that reduced morning light shifts the body\'s internal clock out of sync with sleep and daily life.'],
 brain:[['scn','p','The master clock is reset each morning by light. With less daylight, it drifts later relative to sleep, desynchronizing hormones, alertness and mood.'],['pineal','p','Releases melatonin in darkness. Winter can extend or shift melatonin release, contributing to oversleeping and low energy.'],['raphe','s','Brain serotonin transporter activity rises in winter in some studies, which would lower available serotonin and may contribute to low mood.']],
 symptoms:['Low mood that returns in the darker months','Oversleeping and difficulty waking','Low energy and heaviness','Craving carbohydrates and weight gain','Social withdrawal ("hibernating")','Improvement in spring and summer'],
 diagnosis:'Requires a pattern of major depressive episodes tied to a season for at least two years, with seasonal episodes outnumbering non-seasonal ones.',
 causes:['Reduced daylight, genetic vulnerability and living farther from the equator.'],
 treatment:['Bright light therapy each morning, typically 10,000 lux for 20–30 minutes, is first-line and often works within one to two weeks. CBT adapted for seasonal depression has lasting benefits, and antidepressants also help; bupropion started before winter can prevent episodes.'],
 course:'Episodes tend to recur each year but can be prevented or reduced by starting treatment before the usual onset.'}
});
