window.COND_EXT=window.COND_EXT||{};
Object.assign(window.COND_EXT,{
'psych:anorexia':{
 overview:['Anorexia nervosa is a serious eating disorder characterized by restriction of energy intake leading to significantly low body weight for a person\'s age and health, an intense fear of gaining weight or behaviors that prevent weight gain, and a disturbed experience of body shape or denial of the seriousness of low weight.','It affects every organ system, including the heart, bones, hormones and brain, and has one of the highest mortality rates of any psychiatric condition. Starvation itself changes thinking, making it more rigid and food-focused, which helps keep the illness going. Full recovery is possible, especially with early treatment.'],
 brain:[['antinsula','p','Integrates hunger, taste and body signals into feelings. Altered activity may blunt hunger signals and change how food and the body feel, contributing to restriction and distorted body experience.'],['caudate','s','Part of the reward and habit system. Altered dopamine responses may make restriction feel rewarding and food less so, and restriction can become a habit.'],['dlpfc','s','Supports self-control. Heightened prefrontal control is linked to the ability to override hunger and to rigid, perfectionistic thinking.'],['ofc','s','Represents the reward value of food. Altered responses may reduce the pleasure of eating.'],['hypothalamus','s','Regulates appetite and reproductive hormones. Starvation disrupts these systems, causing loss of periods and other hormone changes.']],
 symptoms:['Restriction of food intake','Intense fear of weight gain','Distorted body image','Denial of the seriousness of low weight','Rigid food rituals','Excessive exercise in some','Physical effects: low heart rate, dizziness, feeling cold, loss of periods, bone loss'],
 diagnosis:'Clinicians assess weight history, eating behaviors, beliefs about weight and shape, and medical status, including heart rhythm, electrolytes and bone health. Severity is graded by body mass index in adults and percentiles in young people.',
 types:['Restricting type: weight loss mainly through dieting, fasting or excessive exercise.','Binge-eating/purging type: recurrent binge eating or purging behaviors.'],
 causes:['Genetics accounts for about 50–60% of risk, and recent studies suggest metabolic as well as psychiatric genetic factors. Temperament (perfectionism, anxiety, harm avoidance), dieting, and cultural pressures about thinness contribute.'],
 treatment:['Medical stabilization and nutritional restoration are essential. Family-based treatment is the most effective approach for adolescents. For adults, specialized therapies such as CBT-E, MANTRA and specialist supportive clinical management are used.','No medication treats anorexia directly, though co-occurring conditions may be treated. Many brain changes improve with weight restoration.'],
 course:'The course varies; many people recover fully, some have relapses and a minority have a chronic course. Early treatment improves outcomes.'},
'psych:bulimia':{
 overview:['Bulimia nervosa involves recurrent episodes of binge eating with a sense of loss of control, followed by compensatory behaviors to prevent weight gain, at least once a week for three months, with self-worth heavily based on body shape and weight.','People with bulimia are often at a normal weight, which can make the disorder easy to miss. Episodes are usually secret and accompanied by shame. Repeated purging can cause dangerous electrolyte imbalances and dental damage.'],
 brain:[['vlpfc','p','Supports inhibitory control. Reduced activity may make it harder to stop once a binge starts.'],['ofc','s','Altered food-reward valuation may increase the drive to binge.'],['antinsula','s','Altered taste and body-signal processing may affect hunger and fullness cues.'],['nacc','s','Altered reward responses to food may reinforce the binge cycle.']],
 symptoms:['Recurrent binge episodes with loss of control','Compensatory behaviors','Self-evaluation driven by shape and weight','Secrecy and shame','Swollen cheeks, dental erosion, electrolyte problems'],
 diagnosis:'Requires binge and compensatory episodes at least weekly for three months, with self-evaluation overly influenced by weight and shape.',
 causes:['Genetics, dieting, low self-esteem, emotion regulation difficulties and cultural pressures.'],
 treatment:['CBT-E is the leading treatment. Fluoxetine is FDA-approved for bulimia.'],
 course:'Many people improve with treatment, though relapse can occur.'},
'psych:bed':{
 overview:['Binge-eating disorder involves recurrent binge episodes with a sense of loss of control and marked distress, without the regular compensatory behaviors of bulimia. It is the most common eating disorder.','Binges often follow stress, negative emotions or restrictive dieting and are followed by shame and guilt, which can trigger the next binge.'],
 brain:[['nacc','p','Shows heightened responses to food cues, increasing the drive to eat.'],['ofc','s','Altered reward valuation of food.'],['vlpfc','s','Reduced inhibitory control makes it harder to stop eating once started.']],
 symptoms:['Eating unusually large amounts in a short period','Feeling out of control while eating','Eating rapidly, when not hungry or until uncomfortably full','Eating alone due to embarrassment','Shame and guilt afterward'],
 diagnosis:'Requires binge episodes at least weekly for three months with marked distress.',
 causes:['Genetics, dieting, stress, depression and difficulties regulating emotion.'],
 treatment:['CBT is first-line. Lisdexamfetamine is FDA-approved for moderate to severe binge-eating disorder.'],
 course:'Often chronic but responsive to treatment.'},
'psych:insomnia':{
 overview:['Insomnia disorder is persistent difficulty falling asleep, staying asleep or waking too early, at least three nights a week for three months, despite enough opportunity to sleep, causing daytime fatigue, mood problems or impaired functioning.','It is understood as a state of hyperarousal: the brain and body stay too alert at night. Over time, worrying about sleep and spending long hours awake in bed teach the brain to associate the bed with wakefulness, which keeps insomnia going even after the original trigger is gone.'],
 brain:[['lateralhyp','s','Arousal systems such as orexin stay too active at night, keeping the brain awake.'],['thalamus','s','Normally gates sensory input and deactivates at sleep onset. Reduced deactivation may let the brain stay alert.'],['acc','s','Heightened activity is linked to a racing, worried mind at bedtime.'],['amygdala','s','Heightened emotional arousal makes it harder to wind down.']],
 symptoms:['Trouble falling or staying asleep','Waking too early','Daytime fatigue and sleepiness','Poor concentration and irritability','Worry about sleep'],
 diagnosis:'Based on sleep history and sleep diaries; sleep studies are used if sleep apnea or other disorders are suspected.',
 causes:['Hyperarousal, stress, irregular schedules, anxiety and depression, pain and learned links between bed and wakefulness.'],
 treatment:['CBT-I (stimulus control, sleep restriction, cognitive work and sleep hygiene) is first-line and outperforms sleeping pills over the long term. Medications are generally for short-term use.'],
 course:'Can be chronic but responds well to CBT-I.'},
'psych:narcolepsy':{
 overview:['Narcolepsy is a chronic neurological sleep disorder in which the brain cannot properly regulate sleep and wakefulness. It causes overwhelming daytime sleepiness, and in type 1, cataplexy: sudden muscle weakness triggered by strong emotions such as laughter.','Features of REM sleep intrude into waking: muscle paralysis appears as cataplexy and sleep paralysis, and dream imagery appears as hallucinations when falling asleep or waking.'],
 brain:[['lateralhyp','p','Orexin neurons stabilize wakefulness. Their loss in type 1 narcolepsy leaves the sleep–wake switch unstable, so people slip into sleep or REM-like states during the day.'],['pons','s','Controls REM sleep and its muscle paralysis. Without orexin, this paralysis can switch on while awake, causing cataplexy and sleep paralysis.'],['amygdala','s','Strong emotions activate the amygdala, which can trigger cataplexy through brainstem circuits.']],
 symptoms:['Excessive daytime sleepiness and sudden sleep attacks','Cataplexy (type 1)','Sleep paralysis','Vivid hallucinations when falling asleep or waking','Fragmented nighttime sleep'],
 diagnosis:'Overnight sleep study followed by a multiple sleep latency test; low orexin in spinal fluid confirms type 1.',
 types:['Type 1: with cataplexy and/or low orexin.','Type 2: without cataplexy, normal orexin.'],
 causes:['Type 1 is caused by loss of orexin neurons, probably through an autoimmune attack in people with the HLA-DQB1*06:02 gene variant.'],
 treatment:['Modafinil, solriamfetol, pitolisant and stimulants for sleepiness; sodium oxybate for sleepiness and cataplexy; scheduled naps.'],
 course:'Lifelong, but symptoms are manageable with treatment.'},
'psych:aud':{
 overview:['Alcohol use disorder is a problematic pattern of drinking marked by loss of control, craving and continued use despite harm. It ranges from mild to severe and involves lasting changes in the brain\'s reward, stress and self-control systems.','Addiction is often described in three repeating stages: binge and intoxication (driven by reward), withdrawal and negative feelings (driven by stress systems), and preoccupation and anticipation (driven by weakened prefrontal control). Over time, people drink less for pleasure and more to relieve withdrawal and distress.'],
 brain:[['nacc','p','The reward hub adapts to repeated alcohol-induced dopamine surges, so cues linked to drinking trigger strong craving while ordinary rewards feel less satisfying.'],['vta','p','Alcohol increases dopamine release from VTA neurons, the initial reinforcing effect that drives repeated use.'],['dlpfc','p','Supports self-control and planning. Weakened top-down control makes it harder to resist drinking despite intentions.'],['antinsula','s','Turns body states into felt urges, contributing to craving.'],['ofc','s','Altered valuation makes alcohol seem more valuable than other rewards.'],['vermis','s','Long-term heavy use shrinks the cerebellum, especially the vermis, causing unsteady gait.'],['hippocampus','s','Alcohol disrupts memory formation (blackouts), and heavy long-term use reduces volume.'],['mammillary','s','Thiamine deficiency can cause Wernicke-Korsakoff syndrome, damaging these memory structures.']],
 symptoms:['Drinking more or longer than intended','Unsuccessful efforts to cut down','Craving','Tolerance','Withdrawal: shaking, sweating, anxiety, insomnia; in severe cases seizures or delirium tremens','Continued drinking despite problems','Giving up activities'],
 diagnosis:'Based on 11 DSM-5 criteria; severity is mild (2–3), moderate (4–5) or severe (6+). The AUDIT questionnaire is a common screening tool.',
 causes:['Genetics (about 50% heritable), early first use, stress, trauma, mental health conditions and social environment.'],
 treatment:['Medications include naltrexone, acamprosate and disulfiram. Counseling, CBT, motivational interviewing and mutual-help groups support recovery. Withdrawal from heavy long-term drinking can be dangerous and may need medical supervision.'],
 course:'Often chronic and relapsing, but many people recover, especially with treatment.'},
'psych:oud':{
 overview:['Opioid use disorder is a chronic, treatable condition involving compulsive use of opioids such as heroin, fentanyl or prescription painkillers despite harm. Physical dependence develops quickly, and withdrawal is intensely unpleasant, which powerfully drives continued use.','The current overdose crisis is driven mainly by illicitly manufactured fentanyl, which is extremely potent. Medications for opioid use disorder are highly effective and cut overdose deaths substantially, yet they remain underused.'],
 brain:[['vta','p','Opioids inhibit the brakes on VTA dopamine neurons, releasing a surge of dopamine that produces euphoria and reinforces use.'],['nacc','p','Repeated surges reshape the reward hub, building intense craving and cue-driven urges.'],['lc','s','Opioids suppress the locus coeruleus; during withdrawal it rebounds into overactivity, causing anxiety, sweating and agitation.'],['medulla','s','The breathing centers are highly sensitive to opioids; overdose kills mainly by stopping breathing.'],['antinsula','s','Turns withdrawal discomfort into craving.'],['ofc','s','Altered decision-making favors drug use over other rewards.']],
 symptoms:['Strong cravings','Tolerance','Withdrawal: aches, sweating, diarrhea, anxiety, insomnia','Loss of control over use','Continued use despite harm','Overdose risk'],
 diagnosis:'Based on DSM-5 criteria similar to alcohol use disorder.',
 causes:['Exposure to opioids, genetics, chronic pain, trauma, mental health conditions and social factors.'],
 treatment:['Buprenorphine, methadone and extended-release naltrexone reduce overdose deaths and support recovery. Naloxone reverses overdoses. Counseling and recovery support help.'],
 course:'Chronic and relapsing, but long-term medication treatment greatly improves survival and recovery.'},
'psych:stimulant':{
 overview:['Stimulant use disorder involves problematic use of cocaine, methamphetamine or other stimulants, with craving, binge patterns and continued use despite harm. Stimulants produce intense euphoria and energy followed by a crash of exhaustion and low mood.','Heavy use can cause paranoia and psychosis, heart attacks, strokes and, increasingly, overdoses when stimulants are contaminated with fentanyl.'],
 brain:[['nacc','p','Stimulants block dopamine reuptake or force its release, flooding the reward hub with dopamine and producing intense euphoria and craving.'],['vta','p','Dopamine circuitry adapts with repeated use, reducing the brain\'s response to natural rewards.'],['caudate','s','Use shifts from goal-directed to habit-driven.'],['ofc','s','Altered valuation and reduced activity during withdrawal.'],['acc','s','Weaker error monitoring and control.']],
 symptoms:['Binge patterns of use','Intense craving','Paranoia or psychosis with heavy use','Crash of exhaustion and low mood','Weight loss and sleep disruption'],
 diagnosis:'Based on DSM-5 criteria similar to other substance use disorders.',
 causes:['Genetics, early exposure, trauma, mental health conditions and environment.'],
 treatment:['Contingency management has the strongest evidence. CBT also helps. There are no FDA-approved medications yet.'],
 course:'Chronic and relapsing, but recovery is common with treatment.'},
'psych:gambling':{
 overview:['Gambling disorder is persistent, problematic gambling causing significant distress or harm. It is the only behavioral addiction in the main DSM-5 diagnostic section.','It activates the same reward circuits as drugs. Unpredictable wins and near-misses are especially powerful, and chasing losses drives escalating bets and debt.'],
 brain:[['nacc','p','Responds strongly to wins and near-misses, reinforcing continued gambling.'],['vmpfc','s','Altered valuation of risky choices.'],['ofc','s','Altered decision-making.'],['antinsula','s','Near-miss effects activate the insula, increasing the urge to continue.']],
 symptoms:['Needing to bet more for excitement','Restlessness when trying to stop','Chasing losses','Lying to hide gambling','Jeopardizing relationships or work','Relying on others for money'],
 diagnosis:'Requires four or more of nine DSM-5 criteria within a year.',
 causes:["Genetics, impulsivity, early wins, easy access, and rarely dopamine agonist medications used for Parkinson's disease."],
 treatment:['CBT has the best support; naltrexone has some evidence. Self-exclusion programs and support groups help.'],
 course:'Can be chronic, but many people recover.'},
'psych:bpd':{
 overview:['Borderline personality disorder is a long-standing pattern of intense and unstable emotions, unstable relationships and self-image, and impulsivity. Emotions rise quickly, run hot and take a long time to settle. It usually emerges in adolescence or early adulthood.','A widely used model describes BPD as the result of high biological emotional sensitivity meeting an environment that invalidated or punished emotions. People with BPD often experience intense fear of abandonment and may react strongly to perceived rejection. Self-harm and suicidal behavior are common and serious.','BPD is highly treatable, and long-term studies show that most people improve substantially over time.'],
 brain:[['amygdala','p','Detects emotional threat. In BPD it reacts more strongly to social cues like a neutral face or a delayed reply, and takes longer to settle afterward. Together with weaker prefrontal calming, this helps explain fast, intense mood shifts and fear of abandonment.'],['vlpfc','p','Regulates emotion from the top down. Reduced activity weakens the brake on emotional reactions, so feelings escalate quickly.'],['acc','p','Monitors conflict and helps regulate emotion and impulses. Reduced activity and volume are linked to difficulty pausing before acting on strong feelings.'],['ofc','s','Altered activity is linked to impulsivity and difficulty weighing consequences.'],['hippocampus','s','Smaller volume, often associated with early trauma, may affect emotional memory and stress regulation.'],['antinsula','s','Heightened sensitivity to social exclusion makes rejection feel especially painful.']],
 symptoms:['Intense fear of abandonment','Unstable, intense relationships swinging between idealization and devaluation','Unstable sense of identity','Impulsive behaviors','Recurrent self-harm or suicidal behavior','Rapid mood shifts lasting hours to days','Chronic emptiness','Intense, hard-to-control anger','Stress-related paranoia or dissociation'],
 diagnosis:'Requires at least five of nine criteria, beginning by early adulthood and present across contexts. Clinicians rule out bipolar disorder, PTSD and substance effects, which often co-occur.',
 causes:['Biological emotional sensitivity (heritability about 40%) combined with an invalidating environment, childhood trauma, neglect or unstable attachments.'],
 treatment:['Dialectical behavior therapy (DBT), teaching emotion regulation, distress tolerance, mindfulness and relationship skills, has the strongest evidence. Mentalization-based treatment, schema therapy and transference-focused psychotherapy also work. Medication can help specific symptoms but is not a primary treatment.'],
 course:'Outcomes are better than once thought: in long-term studies, most people with BPD no longer meet the diagnostic criteria after 10 years, though some difficulties may persist.'},
'psych:aspd':{
 overview:['Antisocial personality disorder is a long-standing pattern of disregarding and violating the rights of others, beginning with conduct problems before age 15 and diagnosed only in adults. Psychopathy is a related but narrower research concept that adds shallow emotion and a marked lack of empathy and remorse.','Not everyone with ASPD is violent or has psychopathic traits, and the disorder is heavily overrepresented in prisons, where up to around half of inmates may meet criteria.'],
 brain:[['amygdala','p',"Reduced response to fear and others' distress, especially in people with psychopathic traits, weakens the emotional signals that normally discourage harming others."],['vmpfc','p','Reduced activity and volume are linked to poor moral decision-making and failure to learn from punishment.'],['ofc','p','Reduced gray matter is linked to impulsivity and poor judgment.'],['acc','s','Weaker error monitoring makes it harder to adjust behavior after mistakes.'],['nacc','s','Heightened reward sensitivity may drive risk-taking.']],
 symptoms:['Repeated rule- or law-breaking','Deceitfulness and manipulation','Impulsivity and failure to plan','Irritability and aggression','Reckless disregard for safety','Irresponsibility','Lack of remorse'],
 diagnosis:'Requires age 18 or older, evidence of conduct disorder before 15, and at least three of seven criteria.',
 causes:['Genetics, childhood conduct disorder, abuse or neglect, and harsh or inconsistent parenting.'],
 treatment:['Difficult to treat. Approaches focus on co-occurring substance use, anger management and CBT-based programs. Early intervention for childhood conduct problems is most promising.'],
 course:'Antisocial behavior often decreases after age 40.'},
'psych:npd':{
 overview:['Narcissistic personality disorder is a pervasive pattern of grandiosity, need for admiration and lack of empathy. Beneath the confident surface, self-esteem is often fragile and highly sensitive to criticism, which can trigger shame, rage or withdrawal.','Researchers distinguish grandiose narcissism (bold, entitled) and vulnerable narcissism (insecure, hypersensitive), which often coexist in the same person.'],
 brain:[['antinsula','p','Reduced gray matter in the left anterior insula is linked to lower empathy, which may make it harder to feel what others feel.'],['dmpfc','s','Altered self-related processing may contribute to an inflated or unstable self-image.'],['acc','s','Altered response to social exclusion may underlie sensitivity to criticism.']],
 symptoms:['Inflated sense of importance','Fantasies of success or power','Need for excessive admiration','Sense of entitlement','Exploiting others','Lack of empathy','Envy and arrogance'],
 diagnosis:'Requires at least five of nine criteria beginning by early adulthood.',
 causes:['Genetics and childhood experiences, including both excessive praise and harsh criticism.'],
 treatment:['Long-term psychotherapy such as transference-focused psychotherapy or schema therapy.'],
 course:'Often stable, though some traits soften with age.'},
'psych:avpd':{overview:['Avoidant personality disorder is a pervasive pattern of social inhibition, feelings of inadequacy and extreme sensitivity to criticism, leading to avoidance of social contact despite wanting it. It overlaps heavily with severe social anxiety disorder.'],
 brain:[['amygdala','p','Heightened threat response to social cues overlaps with social anxiety.'],['antinsula','s','Heightened social pain.'],['dmpfc','s','Self-focused evaluation.']],
 diagnosis:'Requires at least four of seven criteria beginning by early adulthood.',
 causes:['Shy temperament, genetics and experiences of rejection.'],
 treatment:['CBT and schema therapy; SSRIs may help with anxiety.'],
 course:'Often chronic, but therapy can lead to substantial improvement.'},
'psych:ocpd':{overview:['OCPD is a pervasive preoccupation with orderliness, perfectionism and control at the expense of flexibility and efficiency. Unlike OCD, there are usually no true obsessions or compulsions, and people see their standards as correct rather than distressing.'],
 brain:[['dlpfc','s','Altered cognitive control (limited research).'],['caudate','s','Some overlap with OCD circuitry has been proposed.'],['ofc','s','Rigid valuation (limited research).']],
 diagnosis:'Requires at least four of eight criteria beginning by early adulthood.',
 causes:['Genetics and temperament; it often runs in families.'],
 treatment:['CBT and psychodynamic therapy.'],
 course:'Often stable over time.'},
'psych:stpd':{overview:['Schizotypal personality disorder involves social and interpersonal deficits, acute discomfort in close relationships, and odd beliefs, perceptions or behavior. It shares genetic risk with schizophrenia but without sustained psychosis.'],
 brain:[['stg','s','Smaller left superior temporal gyrus, similar to schizophrenia, may relate to unusual perceptions.'],['dlpfc','s','Mild working memory and prefrontal changes.'],['latvent','s','Mild ventricular enlargement in some studies.']],
 diagnosis:'Requires at least five of nine criteria beginning by early adulthood.',
 causes:['Shares genetic risk with schizophrenia.'],
 treatment:['Psychotherapy and social skills training; low-dose antipsychotics for some symptoms.'],
 course:'Usually stable; a minority develop schizophrenia.'},
'psych:ppd':{overview:['Paranoid personality disorder is a pervasive distrust and suspiciousness of others, interpreting their motives as harmful, without the fixed delusions of psychosis.'],
 brain:[['amygdala','s','Heightened threat detection is proposed; direct imaging research is limited.']],
 diagnosis:'Requires at least four of seven criteria beginning by early adulthood.',
 causes:['Possible genetic links with schizophrenia, and early adversity.'],
 treatment:['Psychotherapy focused on building trust.'],
 course:'Often chronic.'},
'psych:szpd':{overview:['Schizoid personality disorder is a pervasive pattern of detachment from social relationships and a restricted range of emotional expression. People prefer solitary activities and seem indifferent to praise or criticism.'],
 brain:[['nacc','s','Reduced social reward response is proposed; brain imaging research is very limited.']],
 diagnosis:'Requires at least four of seven criteria beginning by early adulthood.',
 causes:['Genetic links to the schizophrenia spectrum are suspected.'],
 treatment:['People rarely seek treatment; psychotherapy can help when they do.'],
 course:'Usually stable.'},
'psych:hpd':{overview:['Histrionic personality disorder is a pattern of excessive emotionality and attention-seeking, with a need to be the center of attention.'],
 brain:[['amygdala','s','Heightened emotional reactivity is proposed; almost no imaging research exists.']],
 diagnosis:'Requires at least five of eight criteria beginning by early adulthood.',
 causes:['Genetics and early experiences; little research exists.'],
 treatment:['Psychotherapy.'],
 course:'Traits may soften with age.'},
'psych:dpd':{overview:['Dependent personality disorder is a pervasive, excessive need to be taken care of, leading to submissive, clinging behavior and fear of separation.'],
 brain:[['amygdala','s','Heightened anxiety about separation is proposed; imaging research is very limited.']],
 diagnosis:'Requires at least five of eight criteria beginning by early adulthood.',
 causes:['Overprotective or authoritarian parenting, anxious temperament and chronic illness in childhood.'],
 treatment:['Psychotherapy focused on building independence and assertiveness.'],
 course:'Can improve with therapy.'},
'psych:conduct':{overview:['Conduct disorder is a repetitive pattern in children or teens of violating the basic rights of others or major social rules, such as aggression, destroying property, deceit and serious rule-breaking.','A subgroup with callous-unemotional traits (limited guilt, empathy and concern about performance) tends to have more severe and persistent problems and different underlying brain patterns.'],
 brain:[['amygdala','p',"Reduced response to others' distress, especially with callous-unemotional traits, weakens the signals that normally discourage harming others."],['vmpfc','s','Reduced activity during decision-making.'],['antinsula','s','Altered empathy and emotional awareness.'],['ofc','s','Reduced sensitivity to punishment.']],
 diagnosis:'Requires at least three of 15 criteria in the past year. Specifiers include childhood- vs adolescent-onset and limited prosocial emotions.',
 causes:['Genetics, harsh or inconsistent parenting, abuse, neighborhood violence and peer influence.'],
 treatment:['Parent management training, multisystemic therapy and school-based programs work best when started early.'],
 course:'Many improve by adulthood, but childhood onset raises the risk of antisocial personality disorder.'},
'psych:ied':{overview:['Intermittent explosive disorder involves recurrent, impulsive outbursts of verbal or physical aggression that are far out of proportion to the trigger and are not planned.'],
 brain:[['amygdala','p','Overactive response to angry faces and provocation fuels rapid rage.'],['ofc','p','Reduced regulation of anger responses means the brake engages too late.'],['acc','s','Weaker control over impulsive reactions.']],
 diagnosis:'Requires frequent verbal outbursts (twice weekly for three months) or three damaging outbursts within a year, starting after age 6.',
 causes:['Genetics, exposure to violence in childhood and serotonin system differences.'],
 treatment:['CBT focused on anger regulation; SSRIs.'],
 course:'Often begins in adolescence and can be chronic.'},
'psych:delirium':{overview:['Delirium is an acute, fluctuating disturbance in attention and awareness that develops over hours to days, usually caused by an underlying medical condition, infection, surgery, medication or substance withdrawal. It is a medical emergency.','It can be hyperactive (agitated), hypoactive (quiet and withdrawn, easily missed) or mixed. Delirium increases the risk of long-term cognitive decline and death, especially in older adults.'],
 brain:[['thalamus','s','Disrupted arousal and attention gating.'],['dlpfc','s','Disrupted attention networks.'],['pcc','s','Altered default mode network connectivity.']],
 diagnosis:'Bedside tools such as the CAM (Confusion Assessment Method) help detect it; the cause is found through exam, labs and medication review.',
 causes:['Infection, surgery, dehydration, medications, alcohol withdrawal and organ failure. Older age and dementia raise risk.'],
 treatment:['Find and treat the cause; keep the person oriented, mobile and sleeping well; avoid unnecessary sedatives.'],
 course:'Often resolves when the cause is treated, but may leave lasting cognitive effects.'}
});
