window.GLOSSARY = [
 // Anatomy & orientation
 ['cerebral cortex','The thin, folded outer layer of the cerebrum, about 2–4 mm thick and made mostly of gray matter. It handles most higher functions such as thought, language and perception.',['cortex','cortical']],
 ['cerebrum','The largest part of the brain, made of the left and right hemispheres and their lobes.',[]],
 ['hemisphere','One half of the cerebrum. The two hemispheres are linked by the corpus callosum, and each mostly controls the opposite side of the body.',['hemispheres']],
 ['lobe','One of the major divisions of each hemisphere: frontal, parietal, temporal and occipital, plus the hidden insula. They are named after the skull bones that cover them.',['lobes']],
 ['gyrus','A raised ridge on the surface of the brain. Folding into gyri packs more cortex into the skull.',['gyri','precentral gyrus','postcentral gyrus']],
 ['sulcus','A groove between two gyri. Very deep sulci are called fissures.',['sulci','fissure','calcarine sulcus','intraparietal sulcus']],
 ['central sulcus','The deep groove separating the frontal lobe from the parietal lobe, with the motor cortex in front of it and the somatosensory cortex behind it.',[]],
 ['lateral sulcus','The deep groove along the side of the brain that separates the temporal lobe from the frontal and parietal lobes. Also called the Sylvian fissure.',['sylvian fissure']],
 ['brodmann area','One of about 52 regions of the cortex defined by Korbinian Brodmann in 1909 based on differences in cell layers under the microscope. Still used as a map, for example area 17 is V1.',['brodmann areas']],
 ['operculum','The parts of the frontal, parietal and temporal lobes that fold over and cover the insula. Latin for "lid".',['frontal operculum']],
 ['diencephalon','The part of the forebrain between the cerebrum and the brainstem, containing the thalamus, hypothalamus and epithalamus.',[]],
 ['forebrain','The front division of the developing brain, which becomes the cerebrum and diencephalon.',[]],
 ['hindbrain','The back division of the developing brain, which becomes the pons, medulla and cerebellum.',[]],
 ['subcortical','Below the cortex. Used for deep structures such as the basal ganglia, thalamus and amygdala.',[]],
 ['anterior','Toward the front.',[]],
 ['posterior','Toward the back.',[]],
 ['superior','Toward the top.',[]],
 ['inferior','Toward the bottom.',[]],
 ['medial','Toward the midline, the center line that splits the body into left and right.',[]],
 ['lateral','Toward the side, away from the midline.',[]],
 ['dorsal','Toward the back or top. In the brain, dorsal usually means toward the top of the head.',[]],
 ['ventral','Toward the belly or bottom. In the brain, ventral usually means toward the base.',[]],
 ['midline','The imaginary center line that divides the brain and body into left and right halves.',[]],
 ['contralateral','On the opposite side. Most of the cerebrum controls and senses the contralateral side of the body.',[]],
 ['ipsilateral','On the same side. Each half of the cerebellum controls the ipsilateral side of the body.',[]],
 ['decussation','A point where nerve fibers cross from one side of the brain or spinal cord to the other.',['pyramidal decussation']],
 ['homunculus','A map of the body laid out across the motor or somatosensory cortex. Parts that need fine control or sensitivity, like the hands and lips, get much more space.',['motor homunculus','sensory homunculus']],
 ['tonotopic','Organized by sound frequency, like the keys of a piano. The auditory system is tonotopic.',['tonotopically']],
 ['visual field','The whole area you can see without moving your eyes. Each half of it is handled by the opposite hemisphere.',[]],
 ['optic chiasm','The X-shaped crossing just above the pituitary where fibers from the inner half of each retina cross to the other side.',[]],
 ['optic tract','The nerve fibers carrying visual signals from the optic chiasm to the lateral geniculate nucleus.',[]],
 ['optic radiations','Fiber bundles carrying visual signals from the lateral geniculate nucleus to the primary visual cortex.',[]],
 ['corticospinal tract','The main pathway carrying movement commands from the motor cortex down to the spinal cord. Most of its fibers cross in the medulla.',[]],
 ['arcuate fasciculus',"A curved bundle of white matter linking Broca's area and Wernicke's area.",[]],
 ['meninges','Three protective membranes that cover the brain and spinal cord: the dura mater, arachnoid mater and pia mater.',['meninges']],
 ['subarachnoid space','The fluid-filled space between the arachnoid and pia mater, through which CSF and large blood vessels run.',[]],
 ['choroid plexus','Tissue in the ventricles that produces cerebrospinal fluid.',[]],
 ['cerebrospinal fluid','The clear fluid that fills the ventricles and surrounds the brain and spinal cord, cushioning them and removing waste.',['csf']],
 ['spinal cord','The bundle of nerves running down the spine that carries signals between the brain and the body.',[]],
 ['cranial nerves','Twelve pairs of nerves that come straight from the brain rather than the spinal cord. They serve the head, face, senses and some organs.',['cranial nerve']],
 ['vestibular system','The balance organs of the inner ear and the brain circuits that process their signals.',['vestibular']],
 ['vestibulo-ocular reflex','A reflex that moves your eyes opposite to your head movement so your gaze stays steady.',[]],
 ['folia','The thin, leaf-like folds on the surface of the cerebellum.',['folium']],
 ['striatum','The caudate nucleus, putamen and nucleus accumbens together. The main input station of the basal ganglia.',['striatal','associative striatum']],
 ['limbic system','A group of connected structures, including the hippocampus, amygdala, cingulate cortex and parts of the thalamus and hypothalamus, involved in emotion, motivation and memory.',['limbic']],
 ['papez circuit','A memory loop running from the hippocampus through the fornix, mammillary bodies, anterior thalamus and cingulate cortex and back.',[]],
 ['prefrontal cortex','The front part of the frontal lobe, in front of the motor areas, central to planning, decision-making, judgment and social behavior.',['prefrontal']],
 ['reticular formation','A network of neurons running through the brainstem that controls arousal, alertness and the switch between sleep and waking.',[]],
 ['superior colliculus','A bump on the back of the midbrain that controls reflexive eye and head movements toward things you see.',['superior colliculi']],
 ['inferior colliculus','A bump on the back of the midbrain that processes sound before it reaches the thalamus.',['inferior colliculi']],
 ['sella turcica','A saddle-shaped pocket in the skull base that holds the pituitary gland.',[]],
 ['dorsal stream','The visual pathway running up into the parietal lobe that works out where things are and how to act on them. Often called the "where" pathway.',[]],
 ['ventral stream','The visual pathway running down into the temporal lobe that identifies what things are. Often called the "what" pathway.',[]],
 ['default mode network','A set of brain regions, including the posterior cingulate, precuneus and medial prefrontal cortex, that is most active during rest, daydreaming and thinking about yourself.',['default mode']],
 ['salience network','A network centered on the anterior insula and anterior cingulate that detects what is important and switches attention toward it.',[]],
 ['mesolimbic pathway','Dopamine neurons running from the ventral tegmental area to the nucleus accumbens. Central to reward and motivation.',['mesolimbic']],
 ['mesocortical pathway','Dopamine neurons running from the ventral tegmental area to the prefrontal cortex. Important for motivation and cognition.',['mesocortical']],
 ['nigrostriatal pathway','Dopamine neurons running from the substantia nigra to the striatum. Essential for movement and lost in Parkinson\'s disease.',[]],
 ['hpa axis',"The hypothalamic-pituitary-adrenal axis: the body's main stress-hormone system, in which the hypothalamus signals the pituitary, which signals the adrenal glands to release cortisol.",['hypothalamic-pituitary-adrenal axis']],
 ['reward circuit','The brain network that produces wanting and learning from rewards, centered on dopamine from the VTA to the nucleus accumbens and prefrontal cortex.',['reward system']],
 // Cells & signaling
 ['neuron','A nerve cell. Neurons pass electrical and chemical signals to one another; the human brain has roughly 86 billion of them.',['neurons','nerve cell']],
 ['glial cells','Non-neuron cells in the nervous system that support, insulate, feed and protect neurons. They include astrocytes, oligodendrocytes and microglia.',['glia','glial']],
 ['axon','The long fiber a neuron uses to send signals to other cells. Many are wrapped in myelin, which speeds signals up.',['axons']],
 ['myelin','A fatty insulating layer around many axons. It makes nerve signals travel much faster and gives white matter its pale color.',['myelinated']],
 ['synapse','The junction where one neuron passes a signal to another, usually by releasing neurotransmitters.',['synapses','synaptic']],
 ['neurotransmitter','A chemical messenger released at a synapse, such as dopamine, serotonin or glutamate.',['neurotransmitters','neuromodulators','neuromodulator']],
 ['dopamine','A neurotransmitter involved in movement, motivation, reward learning and attention, made mainly in the substantia nigra and ventral tegmental area.',[]],
 ['serotonin','A neurotransmitter involved in mood, sleep, appetite and impulse control, made mainly in the raphe nuclei.',[]],
 ['norepinephrine','A neurotransmitter and hormone involved in alertness, attention and the stress response, made mainly in the locus coeruleus. Also called noradrenaline.',['noradrenaline']],
 ['acetylcholine','A neurotransmitter used by nerves to activate muscles and, in the brain, for attention, learning and memory.',[]],
 ['glutamate',"The brain's main excitatory neurotransmitter, which makes neurons more likely to fire.",[]],
 ['gaba',"The brain's main inhibitory neurotransmitter, which makes neurons less likely to fire.",[]],
 ['melatonin','A hormone released by the pineal gland at night that signals darkness to the body and helps time sleep.',[]],
 ['cortisol','The main stress hormone, released by the adrenal glands. It raises blood sugar and helps the body respond to stress.',[]],
 ['oxytocin','A hormone made in the hypothalamus involved in childbirth, breastfeeding and social bonding.',[]],
 ['vasopressin','A hormone made in the hypothalamus that helps the kidneys hold on to water and influences social behavior.',[]],
 ['orexin','A neuropeptide made in the lateral hypothalamus that promotes wakefulness. Also called hypocretin.',['hypocretin']],
 ['crh','Corticotropin-releasing hormone: released by the hypothalamus to start the stress-hormone cascade.',[]],
 ['acth','Adrenocorticotropic hormone: released by the pituitary to tell the adrenal glands to make cortisol.',[]],
 ['leptin','A hormone made by fat cells that signals the brain about long-term energy stores and reduces hunger.',[]],
 ['ghrelin','A hormone made by the stomach that rises before meals and increases hunger.',[]],
 ['neuromelanin','A dark pigment in some dopamine and norepinephrine neurons, which gives the substantia nigra and locus coeruleus their color.',[]],
 ['purkinje cells','Large neurons in the cerebellar cortex that are the only output of the cerebellar cortex.',['purkinje cell']],
 ['upper motor neuron','A neuron in the motor cortex whose axon runs down to the brainstem or spinal cord.',['upper motor neurons']],
 ['lower motor neuron','A neuron in the brainstem or spinal cord that connects directly to muscles.',['lower motor neurons']],
 ['mirror neurons','Neurons that fire both when you perform an action and when you watch someone else perform it.',['mirror neuron']],
 ['place cells','Neurons in the hippocampus that fire when you are in a specific location, helping form a mental map.',['place cell']],
 ['grid cells','Neurons in the entorhinal cortex that fire at the points of a repeating hexagonal grid as you move through space.',['grid cell']],
 ['head direction cells','Neurons that fire when your head points in a particular direction, like an internal compass.',[]],
 ['white matter','Brain tissue made mostly of myelinated axons. It carries signals between regions, much like wiring.',[]],
 ['gray matter','Brain tissue made mostly of neuron cell bodies and synapses, where most information processing happens.',['grey matter']],
 ['nucleus','In brain anatomy, a cluster of neuron cell bodies deep in the brain that work together on a particular job.',['nuclei']],
 ['relay','In the brain, a station that receives signals and passes them on to their destination, often filtering them along the way.',[]],
 ['hormone','A chemical messenger released into the bloodstream that acts on distant organs, such as cortisol, insulin or adrenaline.',['hormones']],
 ['endocrine system',"The body's network of glands that release hormones into the blood.",['endocrine']],
 // Functions
 ['executive function','A set of mental skills for managing your own behavior: planning, focusing attention, switching between tasks, keeping instructions in mind and controlling impulses.',['executive functions']],
 ['working memory','Holding and using information for a few seconds, like keeping a phone number in mind while you dial it.',['phonological working memory','verbal working memory']],
 ['response inhibition','The ability to stop an action that has already been planned or started.',[]],
 ['cognitive flexibility','The ability to switch between tasks, rules or ways of thinking.',[]],
 ['metacognition','Thinking about your own thinking, such as judging how confident you are in an answer.',[]],
 ['theory of mind','The ability to understand that other people have their own beliefs, desires and intentions that may differ from yours.',[]],
 ['interoception','Your sense of the internal state of your body, such as heartbeat, breathing, hunger and temperature.',[]],
 ['proprioception','Your sense of where your body parts are and how they are moving, even with your eyes closed.',[]],
 ['body schema','The brain\'s internal model of the body\'s position and layout, used to plan movement.',[]],
 ['voluntary movement','Movement you choose to make, like reaching for a cup, as opposed to an automatic reflex.',[]],
 ['coordination','The smooth, well-timed teamwork of muscles needed for accurate movement.',[]],
 ['motor learning','Getting better at a movement through practice, like learning to ride a bike or type.',['motor skills','motor skill','procedural learning']],
 ['declarative memory','Memory for facts and events that you can consciously recall and put into words. Also called explicit memory.',['explicit memory','declarative memories']],
 ['episodic memory','Memory for specific personal events, with their time and place.',['autobiographical memory']],
 ['semantic memory','Memory for general facts and the meanings of words and concepts.',[]],
 ['long-term memory','Memory stored for a long time, from hours to a lifetime.',['long-term memories']],
 ['memory consolidation','The process of stabilizing a new memory so it lasts. Much of it happens during sleep.',['consolidation']],
 ['pattern separation','Storing similar experiences as distinct memories so they are not confused.',[]],
 ['fear conditioning','Learning that a neutral cue predicts something bad, so the cue itself starts to cause fear.',[]],
 ['fear extinction','Learning that a feared cue is now safe. It creates a new safety memory rather than erasing the old fear.',['extinction']],
 ['reward prediction error','The difference between the reward you expected and the reward you got. Dopamine neurons signal it, and it drives learning.',['reward prediction errors']],
 ['homeostasis',"The body's process of keeping internal conditions such as temperature, water balance and blood sugar steady.",[]],
 ['circadian rhythm',"The body's roughly 24-hour internal clock, which times sleep, alertness, hormones and body temperature.",['circadian rhythms','circadian']],
 ['rem sleep','Rapid eye movement sleep: the stage of vivid dreaming, during which most muscles are temporarily paralyzed.',['rem']],
 ['sleep spindles','Short bursts of brain waves during sleep, generated with help from the thalamus, linked to protecting sleep and strengthening memories.',['sleep spindle']],
 ['readiness potential','A slow build-up of brain activity, measured with EEG, that begins before a self-chosen movement.',[]],
 ['fight-or-flight response',"The body's fast reaction to danger: a racing heart, quicker breathing and a surge of stress hormones such as adrenaline.",['fight-or-flight','fight or flight']],
 ['consciousness','The state of being awake and aware of yourself and your surroundings.',['conscious','consciously']],
 ['neuroplasticity',"The brain's ability to change its connections and organization in response to experience, learning or injury.",['plasticity']],
 ['neurogenesis','The birth of new neurons.',['adult neurogenesis']],
 ['autonomic','Describes the automatic body functions, like heart rate, breathing, digestion and blood pressure, that run without conscious effort.',['autonomic nervous system']],
 // Symptoms & clinical signs
 ['aphasia','A language disorder caused by brain damage that affects speaking, understanding, reading or writing.',['expressive aphasia','receptive aphasia','conduction aphasia','primary progressive aphasia','primary progressive aphasias']],
 ['apraxia','Difficulty carrying out skilled, purposeful movements even though strength and understanding are intact.',['ideomotor apraxia']],
 ['agnosia','Inability to recognize objects, faces or sounds even though the senses work normally.',['visual agnosia']],
 ['prosopagnosia','Face blindness: difficulty recognizing faces, including familiar ones.',['face blindness']],
 ['achromatopsia','Loss of color vision. Cerebral achromatopsia is caused by damage to the color area V4.',['cerebral achromatopsia']],
 ['akinetopsia','Motion blindness: inability to perceive movement smoothly, caused by damage to V5/MT.',[]],
 ['hemianopia','Loss of vision in half of the visual field. Homonymous hemianopia affects the same half in both eyes.',['homonymous hemianopia']],
 ['quadrantanopia','Loss of vision in one quarter of the visual field.',[]],
 ['hemispatial neglect','A condition, usually after damage to the right parietal lobe, in which a person fails to notice things on one side of space, typically the left.',['neglect']],
 ['blindsight','A rare ability of some people with visual cortex damage to respond to things in their blind area without consciously seeing them.',[]],
 ['amnesia','Memory loss. Anterograde amnesia is the inability to form new memories; retrograde amnesia is loss of memories from before an injury.',['anterograde amnesia','retrograde amnesia']],
 ['confabulation','Producing false memories without intending to deceive, often to fill gaps in memory.',[]],
 ['ataxia','Clumsy, uncoordinated movement, often with unsteady walking, usually caused by damage to the cerebellum or its connections.',['truncal ataxia','optic ataxia']],
 ['dysmetria','Overshooting or undershooting when reaching for a target, a sign of cerebellar damage.',[]],
 ['intention tremor','A tremor that gets worse as the hand approaches a target, typical of cerebellar damage.',[]],
 ['tremor','An involuntary, rhythmic shaking of a body part.',['resting tremor']],
 ['nystagmus','Involuntary, repetitive jerking movements of the eyes.',[]],
 ['vertigo','A spinning sensation, usually from a problem in the inner ear or its brain connections.',[]],
 ['hemiparesis','Weakness on one side of the body.',['hemiplegia']],
 ['spasticity','Muscle stiffness and tightness caused by damage to motor pathways in the brain or spinal cord.',[]],
 ['rigidity','Stiffness of the muscles that resists movement in any direction, typical of Parkinson\'s disease.',[]],
 ['bradykinesia','Slowness of movement and gradual shrinking of movement size, a core sign of Parkinson\'s disease.',[]],
 ['chorea','Involuntary, irregular, dance-like movements, typical of Huntington\'s disease.',[]],
 ['hemiballismus','Violent, flinging movements of the limbs on one side, usually from damage to the subthalamic nucleus.',[]],
 ['myoclonus','Sudden, brief, shock-like muscle jerks.',[]],
 ['parkinsonism','A combination of slowness, stiffness, tremor and balance problems, seen in Parkinson\'s disease and several other conditions.',[]],
 ['fasciculations','Small, visible twitches of muscle fibers under the skin.',['fasciculation']],
 ['cataplexy','Sudden, brief muscle weakness triggered by strong emotions such as laughter, seen in narcolepsy type 1.',[]],
 ['sleep paralysis','Being briefly unable to move or speak while falling asleep or waking up.',[]],
 ['tic','A sudden, rapid, repetitive movement or sound.',['tics','motor tics','vocal tics']],
 ['premonitory urge','The uncomfortable feeling that builds before a tic and is relieved by doing it.',[]],
 ['coprolalia','Involuntary swearing or socially inappropriate words, seen in a minority of people with Tourette\'s syndrome.',[]],
 ['seizure','A sudden burst of abnormal electrical activity in the brain that can change movement, awareness or feeling.',['seizures']],
 ['aura','A warning sensation before a migraine or seizure, such as flashing lights, tingling or a strange smell.',['auras']],
 ['focal epilepsy','Epilepsy in which seizures start in one particular area of the brain.',['focal seizures','focal seizure']],
 ['cortical spreading depression','A slow wave of intense brain activity followed by quiet that moves across the cortex, thought to cause migraine aura.',[]],
 ['coma','A long-lasting state of deep unconsciousness in which a person cannot be woken.',[]],
 ['dementia','A decline in memory and thinking severe enough to interfere with daily life. It has many causes, the most common being Alzheimer\'s disease.',[]],
 ['locked-in syndrome','A condition, usually caused by damage to the pons, in which a person is awake and aware but can move almost nothing except the eyes.',[]],
 ['split-brain','Describes people whose corpus callosum has been cut, usually to treat severe epilepsy, so the two hemispheres share little information.',['split brain']],
 ['akinetic mutism','A state in which a person is awake but rarely moves or speaks, usually from damage to the anterior cingulate or nearby areas.',[]],
 // Psychology
 ['psychosis','A loss of contact with reality, usually involving hallucinations or delusions.',['psychotic']],
 ['hallucination','Perceiving something that is not there, such as hearing voices.',['hallucinations','auditory hallucinations','visual hallucinations']],
 ['delusion','A fixed false belief that persists despite clear evidence against it.',['delusions']],
 ['positive symptoms','In schizophrenia, experiences added to normal life, such as hallucinations, delusions and disorganized thinking.',[]],
 ['negative symptoms','In schizophrenia, reductions in normal functions, such as motivation, pleasure, speech and emotional expression.',[]],
 ['mania','A period of abnormally elevated or irritable mood with high energy, reduced need for sleep and risky behavior, lasting at least a week.',['manic']],
 ['hypomania','A milder, shorter form of mania that does not cause severe impairment.',['hypomanic']],
 ['anhedonia','Reduced ability to feel pleasure or interest.',[]],
 ['rumination','Repetitively going over negative thoughts or problems without reaching a solution.',[]],
 ['obsession','An unwanted, intrusive thought, image or urge that causes anxiety.',['obsessions']],
 ['compulsion','A repetitive behavior or mental act done to reduce anxiety or prevent a feared outcome.',['compulsions']],
 ['dissociation','A disconnection between thoughts, memories, feelings, surroundings or identity.',['dissociative']],
 ['hypervigilance','Being constantly on alert for danger.',[]],
 ['impulsivity','Acting quickly without thinking through consequences.',['impulsive']],
 ['empathy','The ability to understand and share the feelings of another person.',[]],
 ['psychopathy','A personality construct marked by shallow emotion, lack of empathy and remorse, and manipulative or antisocial behavior.',['psychopathic traits','callous-unemotional traits']],
 ['comorbidity','Having two or more conditions at the same time.',['co-occurring']],
 ['heritability','The share of differences in a trait across a population that can be explained by genetic differences.',['heritable']],
 ['prevalence','The share of a population that has a condition at a given time or over a lifetime.',[]],
 // Disease processes
 ['atrophy','Shrinking of tissue, such as loss of brain volume from neuron death.',[]],
 ['lesion','An area of damaged or abnormal tissue.',['lesions']],
 ['neurodegenerative','Describes diseases in which neurons gradually die over time, such as Alzheimer\'s and Parkinson\'s.',['neurodegeneration']],
 ['amyloid-beta','A protein fragment that clumps into plaques between neurons in Alzheimer\'s disease.',['amyloid','amyloid plaques','plaques']],
 ['tau','A protein that normally stabilizes the internal skeleton of neurons. In diseases like Alzheimer\'s it misfolds and forms tangles.',['tau tangles','neurofibrillary tangles','tangles']],
 ['alpha-synuclein','A protein that clumps into Lewy bodies in Parkinson\'s disease and Lewy body dementia.',[]],
 ['lewy bodies','Abnormal clumps of alpha-synuclein protein inside neurons.',['lewy body']],
 ['tdp-43','A protein that forms abnormal clumps in most cases of ALS and many cases of frontotemporal dementia.',[]],
 ['prion','A misfolded protein that can force normal proteins to misfold too, spreading through the brain.',['prions']],
 ['demyelination','Damage to or loss of the myelin coating around nerve fibers.',['demyelinating']],
 ['autoimmune','Describes a condition where the immune system mistakenly attacks the body\'s own tissues.',[]],
 ['inflammation','The immune system\'s response to injury or infection, which can damage tissue if it persists.',['neuroinflammation']],
 ['ischemia','Reduced blood flow to tissue, depriving it of oxygen.',['ischemic']],
 ['hemorrhage','Bleeding from a ruptured blood vessel.',[]],
 ['atherosclerosis','Buildup of fatty plaque inside arteries, narrowing them.',[]],
 ['atrial fibrillation','An irregular heart rhythm that lets clots form in the heart, which can travel to the brain.',[]],
 ['diffuse axonal injury','Widespread tearing of long nerve fibers caused by rapid acceleration and rotation of the brain.',[]],
 ['diabetes insipidus','A rare condition in which the body cannot hold on to water, causing heavy urination and intense thirst. It is unrelated to blood-sugar diabetes.',[]],
 ['thiamine','Vitamin B1. Severe deficiency damages the brain, causing Wernicke-Korsakoff syndrome.',['vitamin b1']],
 ['autosomal dominant','An inheritance pattern where one copy of a changed gene is enough to cause a condition, giving each child a 50% chance.',[]],
 ['autosomal recessive','An inheritance pattern where two copies of a changed gene, one from each parent, are needed to cause a condition.',[]],
 ['cag repeat','A repeated three-letter DNA sequence. Too many repeats in certain genes cause diseases such as Huntington\'s and some ataxias.',['repeat expansions','repeat expansion']],
 ['apoe ε4','A version of the APOE gene that raises the risk of Alzheimer\'s disease. One copy roughly triples risk; two copies raise it much more.',['apoe4','apoe']],
 ['stroke','Brain damage caused when a blocked or burst blood vessel cuts off the blood supply to part of the brain.',['strokes']],
 // Treatment & methods
 ['ssri','Selective serotonin reuptake inhibitor: a common class of antidepressant, such as sertraline or fluoxetine, that increases serotonin signaling.',['ssris']],
 ['snri','Serotonin-norepinephrine reuptake inhibitor: an antidepressant class that increases both serotonin and norepinephrine signaling.',['snris']],
 ['antipsychotic','A medication that reduces psychotic symptoms, mainly by blocking dopamine D2 receptors.',['antipsychotics']],
 ['mood stabilizer','A medication, such as lithium, that reduces mood episodes in bipolar disorder.',['mood stabilizers']],
 ['cbt','Cognitive behavioral therapy: a structured talk therapy that changes unhelpful thoughts and behaviors.',['cognitive behavioral therapy']],
 ['dbt','Dialectical behavior therapy: a CBT-based therapy teaching mindfulness, emotion regulation, distress tolerance and relationship skills.',['dialectical behavior therapy']],
 ['exposure therapy','A therapy in which a person gradually and safely faces feared situations so the brain learns they are safe.',['exposure and response prevention','erp']],
 ['deep brain stimulation','Surgery that places electrodes in specific brain structures and delivers electrical pulses to change abnormal activity.',['dbs']],
 ['transcranial magnetic stimulation','A noninvasive treatment that uses magnetic pulses to stimulate an area of cortex.',['tms','rtms']],
 ['electroconvulsive therapy','A treatment for severe depression that induces a brief controlled seizure under anesthesia.',['ect']],
 ['mri','Magnetic resonance imaging: a scan using magnets and radio waves to make detailed pictures of the brain.',['mri scan']],
 ['fmri','Functional MRI: measures changes in blood oxygen to show which brain areas are active.',[]],
 ['diffusion mri','An MRI technique that tracks water movement along fibers to map white matter.',['diffusion tensor imaging','dti']],
 ['pet','Positron emission tomography: a scan using a radioactive tracer to measure metabolism or detect proteins like amyloid.',['pet scan','pet scans']],
 ['eeg','Electroencephalography: recording the brain\'s electrical activity through electrodes on the scalp.',[]]
];
