window.HIER = {
 root:{id:'brain',name:'Human brain',kind:'Whole brain',color:'#9FB3D1',
  where:'Inside the skull, sitting on the brainstem, which continues down as the spinal cord.',
  summary:'The adult human brain weighs about 1.3–1.4 kg and contains roughly 86 billion neurons and a similar number of glial cells. It is organized in layers: two cerebral hemispheres with a folded outer cortex, deep structures buried beneath them that handle emotion, memory, movement selection and body regulation, and a hindbrain (cerebellum and brainstem) that keeps you balanced, coordinated and alive.',
  does:['Senses and interprets the world','Plans and controls movement','Stores memories and learns','Generates emotion, motivation and thought','Regulates breathing, heart rate, hormones and sleep'],
  fact:'The brain is about 2% of body weight but uses roughly 20% of the body\'s energy at rest.'},
 hemis:[
  {id:'hemiL',side:'L',name:'Left hemisphere',kind:'Cerebrum · Hemisphere',color:'#7FA6F0',
   where:'The left half of the cerebrum, separated from the right by the longitudinal fissure and joined to it by the corpus callosum.',
   summary:'The left hemisphere controls and senses the right side of the body. In about 95% of right-handed people and most left-handed people, it is dominant for language: producing speech, grammar, reading and writing. It also tends to lead in detailed, sequential analysis, such as arithmetic procedures and fine motor sequences of the right hand.',
   does:['Movement and sensation for the right side of the body','Language in most people','Reading, writing and arithmetic procedures','Seeing the right half of the visual field'],
   damage:"A stroke in the left hemisphere often causes weakness on the right side and aphasia, a language disorder, such as Broca's or Wernicke's aphasia.",
   fact:'The popular idea of "left-brained" logical people and "right-brained" creative people is not supported by brain imaging; both hemispheres work together on almost everything.'},
  {id:'hemiR',side:'R',name:'Right hemisphere',kind:'Cerebrum · Hemisphere',color:'#F0A47F',
   where:'The right half of the cerebrum, separated from the left by the longitudinal fissure and joined to it by the corpus callosum.',
   summary:'The right hemisphere controls and senses the left side of the body. It tends to lead in spatial attention across both sides of space, recognizing faces, reading the emotional tone of voices (prosody) and understanding context, humor and metaphor in language.',
   does:['Movement and sensation for the left side of the body','Spatial attention and awareness','Face recognition','Emotional tone of speech and facial expression','Seeing the left half of the visual field'],
   damage:'A stroke in the right hemisphere often causes weakness on the left side and hemispatial neglect, where a person ignores the left side of space, sometimes without realizing anything is wrong.',
   fact:'In split-brain patients, the right hemisphere can recognize an object shown only to it but cannot name it, because speech is usually controlled by the left hemisphere.'}
 ],
 deep:{id:'deep',name:'Deep structures',kind:'Subcortical & limbic structures',color:'#C9A6F2',
  where:'Buried beneath the cortex in the center of the brain, around the ventricles.',
  summary:'The deep structures include the thalamus and hypothalamus, the basal ganglia, the limbic structures (hippocampus and amygdala), the corpus callosum and the fluid-filled ventricles. They relay and filter information, select actions, form memories, generate emotion and regulate the body. Many psychiatric and neurological conditions center on them.',
  does:['Relaying sensory information to the cortex','Selecting actions and forming habits','Forming memories and emotional responses','Regulating hormones, hunger, temperature and sleep','Connecting the two hemispheres'],
  fact:'Because they are hidden, most of these structures could only be studied after death until MRI became widely available in the 1980s.'},
 hind:{id:'hind',name:'Hindbrain',kind:'Cerebellum & brainstem',color:'#B58BD6'},
 groups:[
  {id:'g_pfc',parent:'frontal',name:'Prefrontal cortex',short:'Prefrontal cortex',kids:['dlpfc','vlpfc','ofc','vmpfc','dmpfc','fpole'],aka:['prefrontal cortex'],
   where:'The front part of the frontal lobe, in front of the motor areas.',
   summary:'The prefrontal cortex is the brain\'s executive center. Its outer (lateral) parts handle working memory, planning and control; its lower and inner parts link emotion and value to decisions and social behavior. It is the most recently evolved part of the cortex, takes until the mid-20s to mature, and is involved in almost every psychiatric condition.',
   does:['Executive function and planning','Working memory','Decision-making and judgment','Emotion regulation','Social behavior and personality'],
   clinical:'Prefrontal damage can leave intelligence intact while ruining judgment, planning and social conduct. Reduced or altered prefrontal activity is reported in depression, schizophrenia, ADHD, addiction and many other conditions.'},
  {id:'g_motor',parent:'frontal',name:'Motor areas',short:'Motor areas',kids:['m1','premotor','sma'],aka:['motor areas'],
   where:'The back strip of the frontal lobe, just in front of the central sulcus.',
   summary:'The motor areas plan, prepare and execute voluntary movement. The premotor cortex and supplementary motor area plan and sequence movements; the primary motor cortex sends the final commands down to the spinal cord.',
   does:['Planning movement','Sequencing movement','Sending movement commands to muscles'],
   clinical:'Damage causes weakness or loss of movement on the opposite side of the body, or difficulty planning skilled movements (apraxia).'},
  {id:'g_ipl',parent:'parietal',name:'Inferior parietal lobule',short:'Inferior parietal',kids:['supramarginal','angular'],aka:['inferior parietal lobule'],
   where:'The lower part of the parietal lobe, below the intraparietal sulcus.',
   summary:'The inferior parietal lobule is a high-level association area where touch, vision, hearing and language meet. It supports reading, arithmetic, tool use, attention and understanding other people\'s actions. It is much larger in humans than in other primates.',
   does:['Language and reading','Arithmetic','Planning gestures and tool use','Spatial attention'],
   clinical:'Damage can cause apraxia, Gerstmann syndrome on the left, or hemispatial neglect on the right.'},
  {id:'g_auditory',parent:'temporal',name:'Auditory & language areas',short:'Auditory & language',kids:['a1','stg','wernicke'],aka:['auditory and language areas'],
   where:'The upper part of the temporal lobe, along the lateral sulcus.',
   summary:'This strip turns sound into meaning. The primary auditory cortex analyzes pitch and timing, the surrounding superior temporal gyrus recognizes speech sounds, voices and music, and Wernicke\'s area connects words to their meaning.',
   does:['Hearing','Speech recognition','Language comprehension','Music perception'],
   clinical:"Damage on the left can cause Wernicke's aphasia. Abnormal activity here is linked to auditory hallucinations in schizophrenia."},
  {id:'g_ventral',parent:'temporal',name:'Lateral & ventral temporal cortex',short:'Lateral & ventral temporal',kids:['mtg','itg','fusiform'],aka:['ventral temporal cortex'],
   where:'The middle and lower outer surface and underside of the temporal lobe.',
   summary:'These areas store knowledge and recognize what things are. The middle temporal gyrus holds word and concept meanings; the inferior temporal gyrus and fusiform gyrus form the end of the ventral "what" visual stream, recognizing objects, faces and written words.',
   does:['Semantic knowledge','Object recognition','Face recognition','Reading words'],
   clinical:'Damage can cause visual agnosia or prosopagnosia; shrinkage occurs in semantic dementia.'},
  {id:'g_mtl',parent:'temporal',name:'Medial temporal cortex',short:'Medial temporal cortex',kids:['parahippocampal','entorhinal'],aka:['medial temporal lobe','medial temporal cortex'],
   where:'The inner underside of the temporal lobe, wrapped around the hippocampus.',
   summary:'The medial temporal cortex is the gateway between the rest of the cortex and the hippocampus. It feeds information about places, scenes, objects and context into the memory system and holds the brain\'s grid-cell navigation system.',
   does:['Feeding information into the hippocampus','Scene and place recognition','Navigation'],
   clinical:"It is among the earliest areas damaged in Alzheimer's disease and a common site of seizures in temporal lobe epilepsy."},
  {id:'g_early',parent:'occipital',name:'Early visual cortex',short:'Early visual cortex',kids:['v1','v2v3'],aka:['early visual cortex'],
   where:'The back and outer surface of the occipital lobe.',
   summary:'The early visual cortex, V1 through V3, builds the first maps of what the eyes see: edges, orientation, contrast, contours and depth. Everything you see passes through these areas before being sent to specialized regions.',
   does:['Edge and contour detection','Mapping the visual field','Depth perception'],
   clinical:'Damage causes blindness in matching parts of the visual field.'},
  {id:'g_special',parent:'occipital',name:'Specialized visual areas',short:'Specialized visual areas',kids:['v4','v5'],aka:['specialized visual areas'],
   where:'The underside (V4) and outer side (V5/MT) of the occipital lobe.',
   summary:'Beyond the early visual cortex, specialized areas handle particular features: V4 handles color and shape, while V5/MT handles motion.',
   does:['Color perception','Motion perception'],
   clinical:'Damage causes selective loss of color vision (achromatopsia) or motion perception (akinetopsia).'},
  {id:'g_medocc',parent:'occipital',name:'Medial occipital gyri',short:'Medial occipital',kids:['cuneus','lingual'],aka:['medial occipital gyri'],
   where:'The inner surface of the occipital lobe, above and below the calcarine sulcus.',
   summary:'The cuneus above the calcarine sulcus and the lingual gyrus below it hold the parts of the visual cortex representing the lower and upper visual fields, respectively.',
   does:['Lower visual field (cuneus)','Upper visual field (lingual gyrus)'],
   clinical:'Damage causes loss of a quarter of the visual field.'},
  {id:'g_striatum',parent:'basalganglia',name:'Striatum',short:'Striatum',kids:['caudate','putamen','nacc'],aka:[],
   where:'The large input region of the basal ganglia: the caudate, putamen and nucleus accumbens.',
   summary:'The striatum receives input from almost the entire cortex and dopamine from the midbrain. Its dorsal part (caudate and putamen) supports goal-directed action and habits; its ventral part (nucleus accumbens) supports reward and motivation.',
   does:['Receiving cortical input to the basal ganglia','Habit and skill learning','Reward and motivation'],
   clinical:"It is central to Parkinson's disease (dopamine loss), Huntington's disease (neuron loss), OCD, Tourette's syndrome and addiction."},
  {id:'g_relay',parent:'thalamus',name:'Sensory & motor relay nuclei',short:'Relay nuclei',kids:['ventthal','lgn','mgn'],aka:['relay nuclei'],
   where:'The lower and back parts of the thalamus.',
   summary:'These nuclei relay specific streams of information: the ventral nuclei carry touch, pain and motor loops, the lateral geniculate carries vision and the medial geniculate carries hearing.',
   does:['Relaying touch and pain','Relaying motor loops','Relaying vision and hearing'],
   clinical:'Damage causes loss of the matching sensation on the opposite side, or chronic pain.'},
  {id:'g_neuromod',parent:'brainstem',name:'Neuromodulator nuclei',short:'Neuromodulator nuclei',kids:['vta','lc','raphe'],aka:['neuromodulator nuclei'],
   where:'Small clusters inside the midbrain, pons and medulla.',
   summary:'These tiny nuclei send long-range fibers throughout the brain and set its overall state. The ventral tegmental area supplies dopamine, the locus coeruleus norepinephrine and the raphe nuclei serotonin, shaping motivation, arousal, mood and sleep.',
   does:['Dopamine for reward and motivation','Norepinephrine for arousal and alertness','Serotonin for mood and sleep'],
   clinical:'Most psychiatric medications act on the chemical systems these nuclei produce.'}
 ]
};
