window.PSYCH = [
/* ===== Neurodevelopmental ===== */
{id:'adhd',name:'Attention-deficit/hyperactivity disorder',short:'ADHD',aka:['adhd','attention-deficit/hyperactivity disorder'],cat:'Neurodevelopmental disorders',
 summary:'ADHD is a neurodevelopmental condition marked by an ongoing pattern of inattention, hyperactivity and impulsivity that interferes with daily life. It begins in childhood, and for many people it continues into adulthood, where restlessness often becomes more internal. It comes in mainly inattentive, mainly hyperactive-impulsive and combined presentations.',
 symptoms:['Trouble sustaining attention and following through on tasks','Losing things, forgetfulness and disorganization','Fidgeting, restlessness and difficulty staying seated','Interrupting, blurting out answers and acting without thinking','Difficulty waiting and preferring immediate rewards','Hyperfocus on highly interesting activities'],
 causes:'ADHD is one of the most heritable psychiatric conditions, with twin-study heritability around 70–80%. Many genes each add a small effect. Premature birth, low birth weight and prenatal exposure to tobacco or alcohol raise risk. Poor parenting and sugar do not cause ADHD.',
 brain:[['dlpfc','p','Lower activity and slower maturation, linked to weaker working memory and planning'],['vlpfc','p','Reduced activation during tasks that require stopping a response'],['caudate','p','Smaller volume in children and altered dopamine signaling in frontostriatal circuits'],['nacc','s','Weaker response to delayed rewards, which fits a preference for immediate rewards'],['acc','s','Weaker error monitoring and attention control'],['pcc','s','The default mode network fails to quiet down during tasks, linked to mind-wandering'],['cerebhemi','s','Smaller cerebellar volume reported in several studies, linked to timing difficulties']],
 treatment:'Stimulant medications (methylphenidate and amphetamines) increase dopamine and norepinephrine signaling and are effective for most people. Non-stimulants include atomoxetine, viloxazine, guanfacine and clonidine. Behavioral parent training, classroom supports, coaching and CBT for adults help build skills and routines.',
 prevalence:'About 5–7% of children and roughly 2.5–3% of adults worldwide.',
 fact:'In a well-known imaging study, the cortex of children with ADHD reached peak thickness about three years later than in other children, suggesting a delay in maturation rather than a fixed deficit.'},
{id:'asd',name:'Autism spectrum disorder',short:'Autism',aka:['autism spectrum disorder','autism','asd','autistic'],cat:'Neurodevelopmental disorders',
 summary:'Autism is a lifelong neurodevelopmental difference in social communication and interaction, together with restricted or repetitive behaviors and interests and differences in sensory processing. It is a spectrum: support needs range from minimal to very high. Many autistic people see autism as part of their identity rather than something to cure.',
 symptoms:['Differences in back-and-forth conversation and nonverbal communication like eye contact','Difficulty reading social cues or unwritten social rules','Repetitive movements or speech (stimming)','Strong preference for routines and sameness','Intense, focused interests','Over- or under-sensitivity to sound, light, touch, taste or smell'],
 causes:'Autism is highly heritable, with hundreds of genes involved, and some cases are linked to specific genetic syndromes such as fragile X. Older parental age and prematurity modestly raise risk. Large studies have found that vaccines do not cause autism.',
 brain:[['amygdala','s','Atypical growth in early childhood and differences in responses to faces and eye contact'],['stg','s','The superior temporal sulcus, which processes gaze, voices and movement, shows atypical activity'],['fusiform','s','Some studies report reduced response to faces'],['dmpfc','s','Differences in activity during theory-of-mind tasks'],['antinsula','s','Differences in interoception and in tagging sensory input as important'],['cerebhemi','s','Fewer Purkinje cells is among the most consistent post-mortem findings'],['callosum','s','Altered connectivity between the hemispheres, often a smaller corpus callosum']],
 treatment:'There is no medication for autism itself. Support focuses on what helps the individual: speech and language therapy, occupational therapy for sensory and motor needs, developmental and behavioral approaches, social communication support, school accommodations and treating co-occurring conditions like anxiety, ADHD or epilepsy.',
 prevalence:'Around 1 in 31 to 1 in 36 children in recent US surveillance, and roughly 1 in 100 worldwide. Diagnosed about 3–4 times more often in boys.',
 fact:'Brain overgrowth in the first years of life, especially in the frontal and temporal cortex, has been reported in a subset of autistic children.'},
{id:'tourette',name:"Tourette's syndrome",short:"Tourette's",aka:["tourette's syndrome","tourette syndrome","tourette's",'tourette'],cat:'Neurodevelopmental disorders',
 summary:"Tourette's syndrome is a tic disorder in which a person has multiple motor tics and at least one vocal tic for more than a year, starting before age 18. Tics are sudden, repetitive movements or sounds. They often wax and wane and usually peak in early adolescence, then improve in adulthood.",
 symptoms:['Motor tics such as blinking, shrugging, head jerking or grimacing','Vocal tics such as sniffing, throat clearing, words or phrases','A premonitory urge, an uncomfortable feeling that builds before a tic and is relieved by it','Ability to briefly hold tics back, at a cost','Common co-occurring ADHD, OCD and anxiety'],
 causes:"Tourette's is strongly genetic, involving many genes. Male sex, prenatal stress and smoking during pregnancy are associated with higher risk.",
 brain:[['caudate','p','Smaller caudate volume and altered cortico-striatal-thalamic loops that fail to filter unwanted movements'],['putamen','s','Abnormal habit-circuit activity'],['sma','p','Becomes active just before tics and is linked to the premonitory urge'],['antinsula','s','Involved in the bodily sensation of the urge'],['gp','s','Deep brain stimulation of the globus pallidus can reduce severe tics'],['thalamus','s','Thalamic nuclei are another deep brain stimulation target for severe tics']],
 treatment:'Education and reassurance are often enough. Comprehensive Behavioral Intervention for Tics (CBIT) teaches competing responses to urges. Medications include alpha-2 agonists (guanfacine, clonidine), aripiprazole and other antipsychotics, and botulinum toxin for specific tics. Deep brain stimulation is reserved for severe adult cases.',
 prevalence:'About 0.3–0.9% of school-age children; 3–4 times more common in boys.',
 fact:'Involuntary swearing (coprolalia) is famous but affects only a minority of people with Tourette\'s, roughly 1 in 10 to 1 in 5.'},
{id:'dyslexia',name:'Dyslexia (specific learning disorder with impairment in reading)',short:'Dyslexia',aka:['dyslexia','specific learning disorder'],cat:'Neurodevelopmental disorders',
 summary:'Dyslexia is a specific learning disorder that makes accurate and fluent reading and spelling hard despite adequate teaching and normal intelligence. The core difficulty is usually phonological: linking the sounds of language to letters.',
 symptoms:['Slow, effortful reading','Trouble sounding out unfamiliar words','Frequent spelling errors','Difficulty with rhyming and splitting words into sounds','Strong listening comprehension compared with reading'],
 causes:'Dyslexia runs strongly in families and is moderately to highly heritable. Early language delays are a risk sign.',
 brain:[['supramarginal','p','Underactive left temporoparietal reading network that links letters to sounds'],['fusiform','p','The visual word form area responds less to written words'],['broca','s','Often more active, possibly compensating for weaker back-of-brain reading areas'],['angular','s','Weaker connection between written words and meaning'],['cerebhemi','s','The cerebellar deficit theory proposes timing and automatization problems (debated)']],
 treatment:'Structured, explicit phonics-based instruction (structured literacy, such as Orton-Gillingham approaches) is the most effective intervention, especially when started early. Accommodations like extra time and audiobooks help. Successful intervention increases activity in the left-hemisphere reading network.',
 prevalence:'Estimates range from about 5% to 10%, depending on the definition used.'},
/* ===== Schizophrenia spectrum ===== */
{id:'schizophrenia',name:'Schizophrenia',short:'Schizophrenia',aka:['schizophrenia'],cat:'Schizophrenia spectrum & psychotic disorders',
 summary:'Schizophrenia is a serious mental illness that affects how a person thinks, perceives and experiences reality. It involves positive symptoms (experiences added to normal life, like hallucinations and delusions), negative symptoms (things reduced, like motivation and emotional expression) and cognitive symptoms (problems with attention and memory). It usually begins between the late teens and early 30s.',
 symptoms:['Hallucinations, most often hearing voices','Delusions, fixed false beliefs such as being watched or controlled','Disorganized thinking and speech','Reduced motivation, pleasure and social drive','Flat or reduced emotional expression','Problems with working memory, attention and planning'],
 causes:'Schizophrenia is highly heritable, and the risk for an identical twin of an affected person is roughly 40–50%. Hundreds of genes contribute. Environmental risk factors include birth complications, prenatal infection, childhood adversity, migration and urban upbringing, and heavy cannabis use in adolescence, especially high-potency cannabis.',
 brain:[['dlpfc','p','Reduced activity during working memory tasks (hypofrontality), linked to cognitive symptoms'],['caudate','p','Excess dopamine synthesis and release in the associative striatum, one of the most robust findings, linked to psychosis'],['hippocampus','p','Smaller volume and overactivity, especially in CA1, early in illness'],['stg','p','Reduced gray matter, linked to auditory hallucinations'],['latvent','p','Enlarged lateral ventricles, reflecting reduced surrounding tissue'],['mdthal','s','Smaller volume and disrupted thalamus–prefrontal connections'],['vta','s','Altered mesolimbic and mesocortical dopamine pathways'],['acc','s','Reduced volume and abnormal error monitoring']],
 treatment:'Antipsychotic medications, which block dopamine D2 receptors, reduce positive symptoms. Clozapine is the most effective option for treatment-resistant illness. CBT for psychosis, family psychoeducation, supported employment and coordinated specialty care for first episodes improve outcomes. Negative and cognitive symptoms remain harder to treat.',
 prevalence:'About 0.3–0.7% of people over their lifetime, slightly more often and earlier in men.',
 fact:'Many people live well with schizophrenia; early treatment of a first episode is linked to better long-term outcomes.'},
{id:'schizoaffective',name:'Schizoaffective disorder',short:'Schizoaffective',aka:['schizoaffective disorder','schizoaffective'],cat:'Schizophrenia spectrum & psychotic disorders',
 summary:'Schizoaffective disorder combines symptoms of schizophrenia, such as hallucinations or delusions, with major mood episodes of depression or mania. To meet the diagnosis, psychotic symptoms must also occur for at least two weeks without a mood episode.',
 symptoms:['Hallucinations or delusions','Major depressive episodes','Manic episodes (bipolar type)','Disorganized thinking','Social and occupational difficulties'],
 causes:'Risk factors overlap with both schizophrenia and bipolar disorder, including strong genetic contributions.',
 brain:[['dlpfc','s','Prefrontal changes overlapping with schizophrenia'],['hippocampus','s','Reduced volume similar to schizophrenia and bipolar disorder'],['amygdala','s','Altered emotional processing'],['latvent','s','Ventricular enlargement reported']],
 treatment:'Antipsychotics combined with mood stabilizers or antidepressants depending on the type, plus psychotherapy, family support and rehabilitation services. Paliperidone is approved specifically for this condition.',
 prevalence:'About 0.3% of people over their lifetime.'},
{id:'delusional',name:'Delusional disorder',short:'Delusional disorder',aka:['delusional disorder'],cat:'Schizophrenia spectrum & psychotic disorders',
 summary:'Delusional disorder involves one or more firmly held false beliefs lasting at least a month, without the other major symptoms of schizophrenia. Apart from the delusion and its consequences, the person often functions fairly normally. Types include persecutory, jealous, erotomanic, grandiose and somatic.',
 symptoms:['A persistent, fixed false belief','Behavior that makes sense in light of the belief','Little or no hallucination','Generally intact daily functioning outside the delusion'],
 causes:'Causes are not well understood. Family history of psychotic disorders, social isolation, hearing loss and stress may contribute.',
 brain:[['dlpfc','s','Research on belief evaluation suggests altered prefrontal reasoning (limited studies)'],['caudate','s','Dopamine dysregulation is proposed, as in other psychoses'],['acc','s','Reduced conflict monitoring is proposed (limited evidence)']],
 treatment:'Antipsychotic medication and psychotherapy, especially CBT that builds trust before gently examining beliefs.',
 prevalence:'About 0.2% of people over their lifetime.'},
/* ===== Bipolar ===== */
{id:'bipolar',name:'Bipolar disorder',short:'Bipolar disorder',aka:['bipolar disorder','bipolar i','bipolar ii','bipolar','manic depression'],cat:'Bipolar & related disorders',
 summary:'Bipolar disorder causes extreme shifts in mood, energy and activity. Bipolar I involves at least one manic episode, often alongside depression. Bipolar II involves hypomania, a milder form of mania, plus major depressive episodes. Between episodes, many people return to their usual baseline.',
 symptoms:['Mania: elevated or irritable mood, much less need for sleep, racing thoughts, rapid speech, grand plans and risky behavior','Hypomania: a milder, shorter version of mania','Depression: low mood, loss of interest, fatigue and hopelessness','Psychotic symptoms during severe episodes','Mixed episodes with features of both'],
 causes:'Bipolar disorder is one of the most heritable psychiatric conditions, with heritability around 60–85%. Sleep disruption, stress and some substances can trigger episodes. Antidepressants alone can sometimes trigger mania.',
 brain:[['amygdala','p','Overactive in response to emotional stimuli, in both manic and depressive phases'],['vlpfc','p','Reduced activity, weakening top-down emotion regulation'],['acc','p','Reduced subgenual ACC volume and altered activity'],['nacc','s','Heightened reward sensitivity, especially in mania'],['hippocampus','s','Volume changes; lithium treatment is associated with larger hippocampal volume'],['callosum','s','White matter differences between hemispheres']],
 treatment:'Mood stabilizers (lithium, valproate, lamotrigine) and some antipsychotics are the core treatment. Psychotherapy, psychoeducation, family-focused therapy and keeping a regular sleep and daily routine reduce relapses.',
 prevalence:'About 1–2.5% of people over their lifetime.',
 fact:'Lithium has been used since 1949, when Australian psychiatrist John Cade reported its effect on mania.'},
{id:'cyclothymia',name:'Cyclothymic disorder',short:'Cyclothymia',aka:['cyclothymic disorder','cyclothymia'],cat:'Bipolar & related disorders',
 summary:'Cyclothymic disorder involves at least two years (one year in young people) of many periods of hypomanic and depressive symptoms that are not severe enough to qualify as full episodes. Mood feels unpredictable and up-and-down.',
 symptoms:['Frequent shifts between elevated and low moods','Periods of high energy and reduced sleep need','Periods of low mood and low energy','Rarely more than two months without symptoms'],
 causes:'It runs in families with bipolar disorder, and some people later develop bipolar I or II.',
 brain:[['amygdala','s','Emotional reactivity similar to bipolar disorder (limited direct research)'],['vlpfc','s','Weaker emotion regulation proposed']],
 treatment:'Psychotherapy, mood tracking and regular routines; mood stabilizers in some cases.',
 prevalence:'About 0.4–1% of people over their lifetime.'},
/* ===== Depressive ===== */
{id:'mdd',name:'Major depressive disorder',short:'Depression',aka:['major depressive disorder','major depression','depression','clinical depression','mdd'],cat:'Depressive disorders',
 summary:'Major depressive disorder is a common and serious mood disorder. For at least two weeks, a person has a persistently low mood or loss of interest and pleasure, together with other symptoms that affect sleep, appetite, energy, thinking and self-worth. It is a medical condition, not a sign of weakness, and it is treatable.',
 symptoms:['Persistent sadness, emptiness or hopelessness','Loss of interest or pleasure (anhedonia)','Changes in sleep and appetite','Fatigue and slowed thinking or movement','Feelings of worthlessness or excessive guilt','Trouble concentrating and making decisions','Thoughts of death or suicide'],
 causes:'Depression arises from a mix of genetics (heritability about 35–40%), life stress, trauma, chronic illness, hormonal changes and some medications. The old idea of a simple "chemical imbalance" is now considered too simple; changes in brain circuits, stress hormones, inflammation and neuroplasticity all appear to play a part.',
 brain:[['acc','p','The subgenual ACC is overactive and is a deep brain stimulation target'],['dlpfc','p','Underactive, especially on the left; this is the main TMS target'],['amygdala','p','Overreacts to negative information'],['hippocampus','p','Smaller volume, especially with recurrent or long-lasting episodes'],['nacc','s','Reduced response to reward, linked to anhedonia'],['pvn','s','Overactive stress-hormone (HPA) axis with high cortisol'],['raphe','s','Source of the serotonin targeted by SSRIs'],['pcc','s','An overactive default mode network is linked to rumination']],
 treatment:'Psychotherapy (CBT, interpersonal therapy, behavioral activation) and antidepressants such as SSRIs and SNRIs are first-line, and combining them often works best. Options for difficult cases include TMS, electroconvulsive therapy (ECT), esketamine and augmentation strategies. Exercise, sleep and social connection support recovery.',
 prevalence:'About 5% of adults worldwide in any given year; nearly 1 in 5 US adults over a lifetime. About twice as common in women.',
 fact:'If you or someone you know is struggling, a doctor, a counselor or a local crisis line can help. In the US, you can call or text 988.'},
{id:'pdd',name:'Persistent depressive disorder',short:'Dysthymia',aka:['persistent depressive disorder','dysthymia'],cat:'Depressive disorders',
 summary:'Persistent depressive disorder, formerly called dysthymia, is a long-lasting depressed mood present most days for at least two years (one year in young people). Symptoms may be milder than major depression, but their length makes them very disabling, and major depressive episodes can occur on top of it.',
 symptoms:['Low mood most of the day, most days','Low energy and fatigue','Low self-esteem','Poor concentration','Feelings of hopelessness','Changes in sleep or appetite'],
 causes:'Similar to major depression: genetics, chronic stress, early adversity and personality factors.',
 brain:[['amygdala','s','Heightened reactivity to negative emotion'],['acc','s','Altered activity similar to major depression'],['dlpfc','s','Reduced prefrontal regulation']],
 treatment:'Combined psychotherapy (such as CBASP or CBT) and antidepressants is often more effective than either alone.',
 prevalence:'About 2–3% of adults over their lifetime.'},
{id:'pmdd',name:'Premenstrual dysphoric disorder',short:'PMDD',aka:['premenstrual dysphoric disorder','pmdd'],cat:'Depressive disorders',
 summary:'PMDD is a severe form of premenstrual syndrome in which mood symptoms appear in the week or so before menstruation and improve within a few days after it starts. The hormone levels are usually normal; the brain appears to be unusually sensitive to normal hormone changes.',
 symptoms:['Marked mood swings or sudden sadness','Irritability or anger','Depressed mood or hopelessness','Anxiety or tension','Fatigue, trouble concentrating, changes in sleep and appetite','Physical symptoms like breast tenderness and bloating'],
 causes:'An abnormal brain response to normal changes in estrogen, progesterone and its metabolite allopregnanolone, with a genetic component.',
 brain:[['amygdala','s','Increased reactivity in the late luteal phase'],['hypothalamus','s','Sensitivity to cyclical hormone signals'],['raphe','s','Serotonin system involvement explains the fast response to SSRIs'],['dlpfc','s','Altered prefrontal activity during emotion regulation']],
 treatment:'SSRIs, which can work even when taken only in the second half of the cycle; some hormonal contraceptives; CBT; and in severe cases, medications that suppress ovulation.',
 prevalence:'About 3–8% of people who menstruate.'},
{id:'sad',name:'Major depression with seasonal pattern',short:'Seasonal depression',aka:['seasonal affective disorder','seasonal depression','winter depression'],cat:'Depressive disorders',
 summary:'Often called seasonal affective disorder, this is major depression that returns at the same time each year, usually in fall and winter, and lifts in spring. It is more common farther from the equator, where winter daylight is short.',
 symptoms:['Low mood in the darker months','Oversleeping and low energy','Craving carbohydrates and weight gain','Social withdrawal','Remission in spring and summer'],
 causes:'Reduced daylight shifts the body clock, alters melatonin timing and may affect serotonin signaling.',
 brain:[['scn','p','The master clock gets weaker light signals and drifts'],['pineal','p','Melatonin release is shifted or prolonged'],['raphe','s','Seasonal changes in serotonin transporter activity have been measured']],
 treatment:'Bright light therapy each morning, typically with a 10,000-lux light box, is a first-line treatment. CBT adapted for seasonal depression and antidepressants also work; bupropion can be started before winter to prevent episodes.',
 prevalence:'Varies widely by latitude, from about 1% to over 9% in some northern regions.'},
/* ===== Anxiety ===== */
{id:'gad',name:'Generalized anxiety disorder',short:'GAD',aka:['generalized anxiety disorder','gad'],cat:'Anxiety disorders',
 summary:'GAD is excessive, hard-to-control worry about many everyday things, such as health, work, family or money, on most days for at least six months, along with physical symptoms of tension.',
 symptoms:['Persistent, excessive worry','Restlessness or feeling on edge','Fatigue','Trouble concentrating or mind going blank','Irritability','Muscle tension','Sleep problems'],
 causes:'Genetics (about 30% heritable), an anxious temperament, stressful life events and difficulty tolerating uncertainty.',
 brain:[['amygdala','p','Heightened reactivity to possible threats'],['vlpfc','s','Weaker regulation of the amygdala'],['acc','s','Altered conflict and threat monitoring'],['antinsula','s','Heightened sensitivity to uncertainty and body signals'],['bla','s','Fear learning circuits generalize threat broadly']],
 treatment:'CBT, including learning to tolerate uncertainty, is highly effective. SSRIs, SNRIs and buspirone are first-line medications. Benzodiazepines work quickly but are generally only for short-term use because of dependence risk.',
 prevalence:'About 3% of US adults in a given year and around 6% over a lifetime.'},
{id:'panic',name:'Panic disorder',short:'Panic disorder',aka:['panic disorder','panic attacks','panic attack'],cat:'Anxiety disorders',
 summary:'Panic disorder involves repeated, unexpected panic attacks, which are sudden surges of intense fear with strong physical symptoms that peak within minutes, followed by ongoing worry about future attacks or changes in behavior to avoid them.',
 symptoms:['Pounding heart and chest pain','Shortness of breath or a feeling of choking','Trembling, sweating, dizziness','Fear of losing control, going crazy or dying','Feeling unreal or detached','Avoiding places where attacks happened'],
 causes:'Genetic vulnerability, high anxiety sensitivity (fearing anxiety sensations themselves), stressful life events and sometimes substances like caffeine or stimulants.',
 brain:[['amygdala','p','Overactive fear network triggers alarm'],['antinsula','p','Body signals such as heartbeat are read as dangerous'],['lc','p','Bursts of norepinephrine drive the racing heart and alertness'],['midbrain','s','The periaqueductal gray coordinates defensive panic responses'],['hippocampus','s','Links attacks to places and contexts'],['pvn','s','Stress-hormone activation']],
 treatment:'CBT with interoceptive exposure, which deliberately brings on mild panic sensations so the brain learns they are safe, is highly effective. SSRIs and SNRIs are first-line medications.',
 prevalence:'About 2–3% of adults in a given year.'},
{id:'socialanx',name:'Social anxiety disorder',short:'Social anxiety',aka:['social anxiety disorder','social anxiety','social phobia'],cat:'Anxiety disorders',
 summary:'Social anxiety disorder is an intense, persistent fear of social or performance situations where a person might be judged, embarrassed or rejected. The fear is out of proportion to the situation and leads to avoidance or endurance with great distress.',
 symptoms:['Fear of speaking, eating or performing in front of others','Worry about blushing, sweating or trembling being noticed','Avoiding social situations','Replaying conversations afterward','Physical symptoms like a racing heart'],
 causes:'Shy or behaviorally inhibited temperament, genetics, and negative social experiences such as bullying.',
 brain:[['amygdala','p','Hyperreactive to faces and social evaluation'],['antinsula','s','Heightened awareness of bodily signs of anxiety'],['dmpfc','s','Excess self-focused attention'],['acc','s','Heightened sensitivity to social rejection']],
 treatment:'CBT with exposure to feared social situations is first-line, along with SSRIs or SNRIs. Beta-blockers can reduce physical symptoms for specific performances.',
 prevalence:'About 7% of US adults in a given year; often begins in adolescence.'},
{id:'phobia',name:'Specific phobia',short:'Specific phobia',aka:['specific phobia','phobia','phobias'],cat:'Anxiety disorders',
 summary:'A specific phobia is an intense, irrational fear of a particular object or situation, such as heights, spiders, flying, needles or blood, that leads to avoidance and distress.',
 symptoms:['Immediate fear when facing the trigger','Avoidance or enduring it with intense anxiety','Fear out of proportion to the actual danger','Fainting in blood-injection-injury phobia, unlike other phobias'],
 causes:'Frightening experiences, watching others react with fear, an evolutionary readiness to fear certain things, and genetics.',
 brain:[['amygdala','p','Rapid fear response to the trigger'],['antinsula','p','Especially active in disgust-related phobias like spiders and blood'],['vmpfc','s','Weak fear extinction keeps the fear going']],
 treatment:'Exposure therapy is one of the most effective treatments in psychology; a single long session can work for some phobias. Virtual reality exposure is increasingly used.',
 prevalence:'About 7–9% of people in a given year, making it the most common anxiety disorder.'},
{id:'agoraphobia',name:'Agoraphobia',short:'Agoraphobia',aka:['agoraphobia'],cat:'Anxiety disorders',
 summary:'Agoraphobia is fear and avoidance of situations where escape might be hard or help unavailable if panic or embarrassing symptoms occur, such as public transport, crowds, open or enclosed spaces, or being outside the home alone.',
 symptoms:['Fear of crowds, lines, transport or open spaces','Needing a companion to go out','In severe cases, being unable to leave home'],
 causes:'Often develops after panic attacks, along with genetics and stressful life events.',
 brain:[['amygdala','p','Overactive fear responses'],['hippocampus','s','Strong links between fear and places or contexts'],['antinsula','s','Heightened body awareness']],
 treatment:'CBT with gradual exposure to avoided situations and SSRIs.',
 prevalence:'About 1–2% of adults in a given year.'},
{id:'sepanx',name:'Separation anxiety disorder',short:'Separation anxiety',aka:['separation anxiety disorder','separation anxiety'],cat:'Anxiety disorders',
 summary:'Separation anxiety disorder is excessive fear or anxiety about being separated from attachment figures, beyond what is expected for a person\'s age. It is most common in children but can occur in adults.',
 symptoms:['Distress when separating from loved ones','Persistent worry that harm will come to them','Refusing to go to school or sleep away from home','Nightmares about separation','Physical complaints when separation is expected'],
 causes:'Temperament, genetics, life stressors such as a move or loss, and overprotective environments.',
 brain:[['amygdala','p','Heightened threat response to separation cues'],['vmpfc','s','Developing regulation of fear in childhood']],
 treatment:'CBT with gradual separation practice and parent involvement; SSRIs in some cases.',
 prevalence:'About 4% of children and around 1–2% of adults.'},
/* ===== OC-related ===== */
{id:'ocd',name:'Obsessive-compulsive disorder',short:'OCD',aka:['obsessive-compulsive disorder','ocd'],cat:'Obsessive-compulsive & related disorders',
 summary:'OCD involves obsessions, which are unwanted, intrusive thoughts, images or urges that cause anxiety, and compulsions, which are repetitive behaviors or mental acts done to reduce that anxiety or prevent a feared outcome. The cycle can take hours a day.',
 symptoms:['Fears of contamination, harm, or things not being "just right"','Intrusive taboo thoughts the person finds disturbing','Washing, checking, ordering, counting or repeating','Mental rituals like praying or reviewing','Avoiding triggers','Usually knowing the thoughts are excessive'],
 causes:'Genetics (moderately heritable), differences in brain circuits, and sometimes a sudden childhood onset after strep infection (PANDAS), which is still debated.',
 brain:[['ofc','p','Overactive, especially when exposed to triggers, signaling that something is wrong'],['caudate','p','Overactive and fails to filter unwanted thoughts and actions'],['acc','p','Excess error signals that feel like "something is not right"'],['thalamus','s','Part of the cortico-striato-thalamo-cortical loop that keeps the cycle going'],['putamen','s','Habit circuits that drive compulsions']],
 treatment:'Exposure and response prevention (ERP), a type of CBT, is the most effective therapy. SSRIs, often at higher doses than for depression, and clomipramine also help. For severe, treatment-resistant cases, deep brain stimulation and surgical options exist.',
 prevalence:'About 1–2% of people over their lifetime.',
 fact:'Successful treatment, with either ERP or medication, has been shown to reduce the overactivity in the caudate.'},
{id:'bdd',name:'Body dysmorphic disorder',short:'Body dysmorphic disorder',aka:['body dysmorphic disorder','bdd'],cat:'Obsessive-compulsive & related disorders',
 summary:'In body dysmorphic disorder, a person is preoccupied with perceived flaws in their appearance that are minor or not visible to others, and performs repetitive behaviors like mirror checking, grooming or seeking reassurance.',
 symptoms:['Preoccupation with a perceived defect','Mirror checking or avoiding mirrors','Excessive grooming or camouflaging','Comparing appearance with others','Seeking cosmetic procedures, which rarely help'],
 causes:'Genetics, a detail-focused perceptual style, and experiences such as teasing.',
 brain:[['ofc','s','Overactivity in circuits shared with OCD'],['caudate','s','Shared obsessive-compulsive circuitry'],['fusiform','s','Detail-focused processing of faces instead of seeing them as a whole'],['v2v3','s','Imbalances in visual processing of fine detail']],
 treatment:'CBT tailored to BDD, including exposure and response prevention, and SSRIs.',
 prevalence:'About 2% of people.'},
{id:'hoarding',name:'Hoarding disorder',short:'Hoarding',aka:['hoarding disorder','hoarding'],cat:'Obsessive-compulsive & related disorders',
 summary:'Hoarding disorder is persistent difficulty discarding possessions, regardless of their value, because of a perceived need to save them and distress at letting them go. Clutter builds up until living spaces cannot be used.',
 symptoms:['Great distress at discarding things','Excessive acquiring','Cluttered living spaces','Trouble organizing and deciding'],
 causes:'Strong family history, indecisiveness, and stressful or traumatic life events.',
 brain:[['acc','p','Abnormal activity when deciding whether to discard personal items'],['antinsula','p','Heightened emotional response when deciding to discard'],['dlpfc','s','Difficulty with decision-making and organizing']],
 treatment:'Specialized CBT for hoarding, including practice in sorting and discarding.',
 prevalence:'About 2–6% of people; more common in older adults.'},
{id:'trich',name:'Trichotillomania and skin-picking disorder',short:'Trichotillomania',aka:['trichotillomania','hair-pulling disorder','skin-picking disorder','excoriation disorder'],cat:'Obsessive-compulsive & related disorders',
 summary:'These are body-focused repetitive behaviors: recurrent hair pulling (trichotillomania) or skin picking (excoriation) that causes hair loss or skin damage, with repeated attempts to stop.',
 symptoms:['Repeated pulling or picking','Tension before and relief or pleasure during the behavior','Often done automatically without awareness','Shame and attempts to hide the effects'],
 causes:'Genetics and differences in habit and reward circuits; the behavior can help regulate boredom or stress.',
 brain:[['putamen','s','Habit circuits'],['acc','s','Altered self-monitoring'],['cerebhemi','s','Gray matter differences in some studies']],
 treatment:'Habit reversal training and comprehensive behavioral treatment (ComB). N-acetylcysteine has some evidence.',
 prevalence:'Each affects about 1–2% of people.'},
/* ===== Trauma ===== */
{id:'ptsd',name:'Post-traumatic stress disorder',short:'PTSD',aka:['post-traumatic stress disorder','ptsd'],cat:'Trauma & stressor-related disorders',
 summary:'PTSD can develop after experiencing or witnessing a traumatic event such as combat, assault, disaster or a serious accident. Symptoms last more than a month and include reliving the event, avoidance, negative changes in mood and thinking, and being constantly on alert.',
 symptoms:['Intrusive memories, flashbacks and nightmares','Avoiding reminders of the trauma','Negative beliefs, guilt, shame or emotional numbness','Hypervigilance and a strong startle response','Irritability and trouble sleeping'],
 causes:'Most people exposed to trauma do not develop PTSD. Risk is higher with severe or repeated trauma, earlier trauma, lack of support afterward, and genetic vulnerability.',
 brain:[['amygdala','p','Hyperreactive to threat and reminders'],['vmpfc','p','Underactive, so it fails to calm the amygdala and extinguish fear'],['hippocampus','p','Smaller volume and trouble telling safe contexts from dangerous ones'],['acc','s','Reduced volume and regulation'],['antinsula','s','Heightened body-based anxiety'],['lc','s','High norepinephrine drives hyperarousal and nightmares'],['pvn','s','Altered stress-hormone (HPA) regulation']],
 treatment:'Trauma-focused psychotherapies such as prolonged exposure, cognitive processing therapy and EMDR are the most effective. SSRIs and SNRIs are first-line medications.',
 prevalence:'About 6–8% of US adults over a lifetime.',
 fact:'Fear extinction does not erase a fear memory; it creates a new safety memory, stored with help from the vmPFC, that competes with the old one.'},
{id:'asd_stress',name:'Acute stress disorder',short:'Acute stress disorder',aka:['acute stress disorder'],cat:'Trauma & stressor-related disorders',
 summary:'Acute stress disorder involves PTSD-like symptoms that occur from 3 days to 1 month after a traumatic event. It may resolve or develop into PTSD.',
 symptoms:['Intrusive memories','Dissociation, such as feeling in a daze','Avoidance','Anxiety and hyperarousal'],
 causes:'Trauma exposure, with similar risk factors to PTSD.',
 brain:[['amygdala','p','Acute threat activation'],['hippocampus','s','Stress effects on memory encoding']],
 treatment:'Brief trauma-focused CBT can prevent progression to PTSD. Single-session debriefing is not recommended.',
 prevalence:'Affects roughly 20% or fewer of people after traumatic events not involving assault, and more after assault.'},
/* ===== Dissociative ===== */
{id:'did',name:'Dissociative identity disorder',short:'DID',aka:['dissociative identity disorder','multiple personality disorder'],cat:'Dissociative disorders',
 summary:'Dissociative identity disorder involves two or more distinct identity states, with gaps in memory for everyday events, personal information or traumatic events. It is almost always linked to severe, repeated childhood trauma and remains an area of debate and ongoing research.',
 symptoms:['Distinct identity states with different senses of self','Memory gaps for everyday events','Finding unexplained items or writing','Depersonalization and derealization','Co-occurring depression, PTSD and self-harm'],
 causes:'Usually linked to severe, chronic early trauma combined with a high capacity for dissociation.',
 brain:[['hippocampus','s','Smaller volume reported in several studies'],['amygdala','s','Smaller volume reported'],['precuneus','s','Altered activity in self-awareness networks between identity states'],['dlpfc','s','Altered prefrontal control (limited research)']],
 treatment:'Long-term, phase-oriented psychotherapy focused on safety and stabilization, trauma processing, then integration.',
 prevalence:'Around 1–1.5% in some community samples; estimates vary and are debated.'},
{id:'dpdr',name:'Depersonalization/derealization disorder',short:'Depersonalization',aka:['depersonalization/derealization disorder','depersonalization','derealization'],cat:'Dissociative disorders',
 summary:'People with this disorder repeatedly feel detached from their own mind, body or feelings (depersonalization), or feel that the world is unreal, dreamlike or foggy (derealization). They know the feeling is not literally true.',
 symptoms:['Feeling like an outside observer of yourself','Emotional numbness','Surroundings seem flat, distant or artificial','Distress about the experience'],
 causes:'Severe stress, childhood emotional abuse, anxiety, and drug experiences can trigger it.',
 brain:[['antinsula','p','Reduced activity, matching the numbing of emotional and body feelings'],['vlpfc','s','Overactive prefrontal inhibition of limbic responses'],['angular','s','The temporoparietal junction supports the sense of being in your body']],
 treatment:'Psychotherapy (CBT, grounding skills) and treating co-occurring anxiety or depression. No medication is specifically approved.',
 prevalence:'About 1–2% of people.'},
/* ===== Somatic ===== */
{id:'ssd',name:'Somatic symptom disorder',short:'Somatic symptom disorder',aka:['somatic symptom disorder'],cat:'Somatic symptom & related disorders',
 summary:'Somatic symptom disorder involves one or more distressing physical symptoms, which may or may not have a medical cause, together with excessive thoughts, feelings or behaviors about them, such as persistent health anxiety or spending large amounts of time on them.',
 symptoms:['Distressing physical symptoms like pain or fatigue','Persistent worry about their seriousness','Frequent medical visits','Symptoms taking over daily life'],
 causes:'Heightened sensitivity to body sensations, anxiety and depression, past illness experiences and stress.',
 brain:[['antinsula','s','Amplified attention to body signals'],['acc','s','Heightened emotional response to bodily sensations'],['amygdala','s','Threat interpretation of sensations']],
 treatment:'CBT, regular scheduled visits with one doctor, and treating co-occurring anxiety or depression.',
 prevalence:'Estimated at about 5–7% of adults.'},
{id:'fnd',name:'Functional neurological disorder',short:'FND',aka:['functional neurological disorder','functional neurological symptom disorder','conversion disorder','fnd'],cat:'Somatic symptom & related disorders',
 summary:'In functional neurological disorder (formerly conversion disorder), people have real neurological symptoms like weakness, tremor, seizures or numbness that come from a problem with how the brain functions rather than structural damage. The symptoms are not faked or imagined.',
 symptoms:['Limb weakness or paralysis','Functional (dissociative) seizures','Tremor, jerks or unusual walking','Numbness or sensory loss','Speech or swallowing problems'],
 causes:'Combinations of physical injury, illness, stress, trauma and attention focused on the body. Many people have no psychological trigger at all.',
 brain:[['angular','s','Reduced activity in the temporoparietal junction, linked to a reduced sense of controlling the movement'],['sma','s','Altered movement preparation'],['amygdala','s','Increased emotional reactivity'],['antinsula','s','Altered body awareness']],
 treatment:'A clear explanation of the diagnosis is a key first step. Specialized physiotherapy, occupational therapy and CBT help retrain brain function.',
 prevalence:'One of the most common reasons for neurology clinic visits.'},
/* ===== Feeding & eating ===== */
{id:'anorexia',name:'Anorexia nervosa',short:'Anorexia nervosa',aka:['anorexia nervosa','anorexia'],cat:'Feeding & eating disorders',
 summary:'Anorexia nervosa is a serious eating disorder involving restriction of food intake leading to significantly low body weight, an intense fear of gaining weight and a distorted experience of body shape. It has one of the highest death rates of any psychiatric condition, but recovery is possible.',
 symptoms:['Restricting food intake','Intense fear of weight gain','Distorted body image','Denial of the seriousness of low weight','Physical effects such as loss of periods, low heart rate and bone loss'],
 causes:'Genetics (about 50–60% heritable), perfectionism and anxiety, and sociocultural pressures. Genetic studies suggest metabolic as well as psychiatric factors.',
 brain:[['antinsula','p','Altered interoception and taste reward processing'],['caudate','s','Altered reward responses and dopamine signaling'],['dlpfc','s','Heightened cognitive control'],['ofc','s','Altered food reward value'],['hypothalamus','s','Appetite and hormone systems are disrupted by starvation']],
 treatment:'Nutritional restoration with medical monitoring is essential. Family-based treatment is the leading approach for adolescents; CBT-E and other specialized therapies are used for adults. Many brain changes improve with weight restoration.',
 prevalence:'Up to about 1–4% of women and a smaller share of men over their lifetime.',
 fact:'If you are worried about yourself or someone else, a doctor or an eating disorder helpline can help.'},
{id:'bulimia',name:'Bulimia nervosa',short:'Bulimia nervosa',aka:['bulimia nervosa','bulimia'],cat:'Feeding & eating disorders',
 summary:'Bulimia nervosa involves recurrent episodes of binge eating with a sense of loss of control, followed by behaviors to prevent weight gain, with self-worth heavily based on body shape and weight.',
 symptoms:['Recurrent binge episodes','Compensatory behaviors','Self-evaluation driven by shape and weight','Secrecy and shame','Physical complications like electrolyte imbalance and dental damage'],
 causes:'Genetics, dieting, low self-esteem and sociocultural pressures.',
 brain:[['vlpfc','p','Reduced inhibitory control'],['ofc','s','Altered reward value of food'],['antinsula','s','Altered taste and body signal processing'],['nacc','s','Altered reward circuit responses']],
 treatment:'CBT-E is the leading treatment. Fluoxetine is FDA-approved for bulimia.',
 prevalence:'About 1% of women over their lifetime; less common in men.'},
{id:'bed',name:'Binge-eating disorder',short:'Binge-eating disorder',aka:['binge-eating disorder','binge eating disorder'],cat:'Feeding & eating disorders',
 summary:'Binge-eating disorder involves recurrent binge episodes with a sense of loss of control and marked distress, without regular compensatory behaviors. It is the most common eating disorder.',
 symptoms:['Eating unusually large amounts in a short time','Feeling out of control while eating','Eating rapidly or when not hungry','Shame and guilt afterward'],
 causes:'Genetics, dieting, stress, depression and difficulties regulating emotion.',
 brain:[['nacc','p','Heightened reward response to food cues'],['ofc','s','Altered reward valuation'],['vlpfc','s','Reduced inhibitory control']],
 treatment:'CBT is first-line. Lisdexamfetamine is FDA-approved for moderate to severe binge-eating disorder.',
 prevalence:'About 1–3% of people over their lifetime.'},
/* ===== Sleep-wake ===== */
{id:'insomnia',name:'Insomnia disorder',short:'Insomnia',aka:['insomnia disorder','insomnia'],cat:'Sleep-wake disorders',
 summary:'Insomnia disorder is ongoing trouble falling asleep, staying asleep or waking too early, at least three nights a week for three months, despite enough opportunity to sleep, causing daytime problems.',
 symptoms:['Trouble falling or staying asleep','Waking too early','Daytime fatigue','Poor concentration and mood','Worry about sleep'],
 causes:'A state of hyperarousal, stress, irregular schedules, anxiety and depression, pain, and learned links between the bed and wakefulness.',
 brain:[['lateralhyp','s','Arousal systems such as orexin remain too active'],['thalamus','s','Reduced deactivation at sleep onset'],['acc','s','Heightened activity linked to a racing mind'],['amygdala','s','Heightened emotional arousal']],
 treatment:'Cognitive behavioral therapy for insomnia (CBT-I) is the first-line treatment and outperforms sleeping pills over the long term. Medications are generally for short-term use.',
 prevalence:'About 10% of adults have chronic insomnia; about a third have occasional symptoms.'},
{id:'narcolepsy',name:'Narcolepsy',short:'Narcolepsy',aka:['narcolepsy'],cat:'Sleep-wake disorders',
 summary:'Narcolepsy is a chronic neurological sleep disorder in which the brain cannot properly regulate sleep and wakefulness. It causes overwhelming daytime sleepiness, and in type 1, cataplexy: sudden muscle weakness triggered by emotions like laughter.',
 symptoms:['Excessive daytime sleepiness and sudden sleep attacks','Cataplexy (type 1)','Sleep paralysis','Vivid hallucinations when falling asleep or waking','Fragmented nighttime sleep'],
 causes:'Type 1 is caused by loss of the orexin-producing neurons, probably through an autoimmune attack in genetically susceptible people.',
 brain:[['lateralhyp','p','Loss of orexin (hypocretin) neurons in type 1'],['pons','s','REM sleep muscle paralysis intrudes into waking, causing cataplexy'],['amygdala','s','Emotional triggers set off cataplexy']],
 treatment:'Modafinil, solriamfetol, pitolisant and stimulants for sleepiness; sodium oxybate for sleepiness and cataplexy; scheduled naps.',
 prevalence:'About 1 in 2,000 people.'},
/* ===== Substance & addictive ===== */
{id:'aud',name:'Alcohol use disorder',short:'Alcohol use disorder',aka:['alcohol use disorder','alcoholism','alcohol addiction'],cat:'Substance-related & addictive disorders',
 summary:'Alcohol use disorder is a problematic pattern of drinking with loss of control, craving and continued use despite harm. It ranges from mild to severe and involves lasting changes in brain reward, stress and self-control circuits.',
 symptoms:['Drinking more or longer than intended','Unsuccessful efforts to cut down','Craving','Tolerance','Withdrawal symptoms like shaking, sweating and anxiety','Continuing despite social, health or work problems'],
 causes:'Genetics (about 50% heritable), early first use, stress, trauma, mental health conditions and social environment.',
 brain:[['nacc','p','Reward circuit adapts to alcohol and drives craving'],['vta','p','Alcohol increases dopamine release from VTA neurons'],['dlpfc','p','Weakened top-down control over drinking'],['antinsula','s','Bodily craving signals'],['ofc','s','Altered valuation of alcohol versus other rewards'],['vermis','s','Long-term heavy use shrinks the cerebellum, causing unsteady gait'],['hippocampus','s','Memory blackouts and reduced volume'],['mammillary','s','Thiamine deficiency can cause Wernicke-Korsakoff syndrome']],
 treatment:'Medications such as naltrexone, acamprosate and disulfiram; counseling, CBT and motivational interviewing; mutual-help groups. Withdrawal from heavy, long-term drinking can be dangerous and may need medical supervision.',
 prevalence:'About 1 in 10 US adults in a given year.'},
{id:'oud',name:'Opioid use disorder',short:'Opioid use disorder',aka:['opioid use disorder','opioid addiction'],cat:'Substance-related & addictive disorders',
 summary:'Opioid use disorder is a chronic condition involving compulsive use of opioids such as heroin, fentanyl or prescription painkillers despite harm. It carries a high risk of fatal overdose.',
 symptoms:['Strong cravings','Tolerance','Withdrawal: aches, sweating, diarrhea, anxiety and insomnia','Loss of control over use','Continued use despite harm'],
 causes:'Exposure to opioids, genetics, chronic pain, trauma, mental health conditions and social factors.',
 brain:[['vta','p','Opioids disinhibit VTA dopamine neurons, producing reward'],['nacc','p','Reward and craving circuitry'],['lc','s','Rebound overactivity drives many withdrawal symptoms'],['medulla','s','Overdose suppresses the breathing centers'],['antinsula','s','Craving'],['ofc','s','Altered decision-making']],
 treatment:'Medications for opioid use disorder (buprenorphine, methadone and extended-release naltrexone) cut overdose deaths substantially. Naloxone reverses overdoses. Counseling and recovery support help.',
 prevalence:'Several million people in the US.'},
{id:'stimulant',name:'Stimulant use disorder',short:'Stimulant use disorder',aka:['stimulant use disorder','cocaine addiction','methamphetamine addiction'],cat:'Substance-related & addictive disorders',
 summary:'Stimulant use disorder involves problematic use of cocaine, methamphetamine or other stimulants, with craving, loss of control and continued use despite harm.',
 symptoms:['Binge patterns of use','Intense craving','Paranoia or psychosis with heavy use','A "crash" of exhaustion and low mood after use','Weight loss and sleep disruption'],
 causes:'Genetics, early exposure, trauma, mental health conditions and environment.',
 brain:[['nacc','p','Stimulants flood the reward hub with dopamine'],['vta','p','Dopamine circuitry adapts with repeated use'],['caudate','s','Shift toward habit-driven use'],['ofc','s','Reduced activity during withdrawal and altered valuation'],['acc','s','Weaker error monitoring and control']],
 treatment:'Contingency management, which gives rewards for drug-free tests, has the strongest evidence. CBT also helps. There are no FDA-approved medications yet.',
 prevalence:'Several million people in the US.'},
{id:'gambling',name:'Gambling disorder',short:'Gambling disorder',aka:['gambling disorder','gambling addiction'],cat:'Substance-related & addictive disorders',
 summary:'Gambling disorder is persistent, problematic gambling that causes significant distress or harm. It is the only behavioral addiction in the main DSM-5 diagnostic section.',
 symptoms:['Needing to bet more to feel excitement','Restlessness when trying to stop','Chasing losses','Lying to hide gambling','Jeopardizing relationships or work'],
 causes:"Genetics, impulsivity, early wins, easy access, and, rarely, dopamine agonist medications used for Parkinson's disease.",
 brain:[['nacc','p','Reward response to wins and to near-misses'],['vmpfc','s','Altered valuation of risky choices'],['ofc','s','Altered decision-making'],['antinsula','s','Near-miss effects activate the insula']],
 treatment:'CBT is the best-supported treatment. Naltrexone has some evidence. Self-exclusion programs and support groups help.',
 prevalence:'About 0.5–1% of adults.'},
/* ===== Personality ===== */
{id:'bpd',name:'Borderline personality disorder',short:'BPD',aka:['borderline personality disorder','bpd','emotionally unstable personality disorder'],cat:'Personality disorders',
 summary:'Borderline personality disorder is a long-standing pattern of intense, unstable emotions, unstable relationships and self-image, and impulsivity. Emotions rise fast, run hot and take a long time to settle. It usually emerges in adolescence or early adulthood, and many people improve substantially with treatment.',
 symptoms:['Intense fear of abandonment, real or imagined','Unstable, intense relationships swinging between idealizing and devaluing','Unstable sense of identity','Impulsive behaviors such as spending, substance use or reckless driving','Recurrent self-harm or suicidal behavior','Rapid mood shifts lasting hours to days','Chronic feelings of emptiness','Intense anger that is hard to control','Stress-related paranoia or dissociation'],
 causes:'A combination of biological emotional sensitivity (heritability about 40%) and an environment where emotions were invalidated, including childhood trauma, neglect or unstable attachments.',
 brain:[['amygdala','p','Hyperreactive to emotional and social cues, and slow to return to baseline'],['vlpfc','p','Reduced prefrontal regulation of emotional responses'],['acc','p','Reduced activity and volume, linked to difficulty regulating emotion and impulses'],['ofc','s','Altered activity linked to impulsivity'],['hippocampus','s','Smaller volume, often associated with early trauma'],['antinsula','s','Heightened sensitivity to social exclusion']],
 treatment:'Dialectical behavior therapy (DBT), which teaches emotion regulation, distress tolerance, mindfulness and relationship skills, has the strongest evidence. Mentalization-based treatment, schema therapy and transference-focused psychotherapy also work. Medication can help specific symptoms but is not a primary treatment.',
 prevalence:'About 1.5–2% of adults; much more common in clinical settings.',
 fact:'Outcomes are better than once thought: in long-term studies, most people with BPD no longer meet the diagnostic criteria after 10 years.'},
{id:'aspd',name:'Antisocial personality disorder',short:'ASPD',aka:['antisocial personality disorder','aspd','sociopathy'],cat:'Personality disorders',
 summary:'Antisocial personality disorder is a long-standing pattern of disregarding and violating the rights of others, starting with conduct problems before age 15. Psychopathy, a related research concept, adds shallow emotion and a lack of empathy and remorse.',
 symptoms:['Repeated rule- or law-breaking','Deceitfulness and manipulation','Impulsivity and failure to plan','Irritability and aggression','Reckless disregard for safety','Irresponsibility','Lack of remorse'],
 causes:'Genetics, childhood conduct disorder, abuse or neglect, and harsh or inconsistent parenting.',
 brain:[['amygdala','p',"Reduced response to fear and others' distress, especially with psychopathic traits"],['vmpfc','p','Reduced activity and volume, linked to poor moral decision-making'],['ofc','p','Reduced gray matter, linked to impulsivity'],['acc','s','Weaker error monitoring'],['nacc','s','Heightened reward sensitivity']],
 treatment:'Difficult to treat. Approaches focus on co-occurring substance use, anger management and CBT-based programs. Early intervention for childhood conduct problems is most promising.',
 prevalence:'About 1–3% of adults; more common in men.'},
{id:'npd',name:'Narcissistic personality disorder',short:'NPD',aka:['narcissistic personality disorder','npd'],cat:'Personality disorders',
 summary:'Narcissistic personality disorder is a pervasive pattern of grandiosity, need for admiration and lack of empathy. Beneath the confident surface, self-esteem is often fragile and highly sensitive to criticism.',
 symptoms:['Inflated sense of importance','Fantasies of success or power','Need for excessive admiration','Sense of entitlement','Exploiting others','Lack of empathy','Envy and arrogance'],
 causes:'Genetics and childhood experiences, including both excessive praise and harsh criticism.',
 brain:[['antinsula','p','Reduced gray matter in the left anterior insula, linked to lower empathy'],['dmpfc','s','Altered self-related processing'],['acc','s','Altered response to social exclusion']],
 treatment:'Long-term psychotherapy such as transference-focused psychotherapy or schema therapy.',
 prevalence:'Around 1% of people; estimates vary widely.'},
{id:'avpd',name:'Avoidant personality disorder',short:'Avoidant PD',aka:['avoidant personality disorder'],cat:'Personality disorders',
 summary:'Avoidant personality disorder is a pervasive pattern of social inhibition, feelings of inadequacy and extreme sensitivity to criticism, leading to avoidance of social contact despite wanting it.',
 symptoms:['Avoiding jobs or activities involving people','Unwilling to engage unless sure of being liked','Restraint in close relationships','Preoccupation with rejection','Feeling inferior'],
 causes:'Shy temperament, genetics and experiences of rejection.',
 brain:[['amygdala','p','Heightened threat response to social cues, overlapping with social anxiety'],['antinsula','s','Heightened social pain'],['dmpfc','s','Self-focused evaluation']],
 treatment:'CBT and schema therapy; SSRIs may help with anxiety.',
 prevalence:'About 2% of people.'},
{id:'ocpd',name:'Obsessive-compulsive personality disorder',short:'OCPD',aka:['obsessive-compulsive personality disorder','ocpd'],cat:'Personality disorders',
 summary:'OCPD is a pervasive preoccupation with orderliness, perfectionism and control at the expense of flexibility and efficiency. Unlike OCD, there are usually no true obsessions or compulsions, and the person sees their standards as correct.',
 symptoms:['Preoccupation with details, rules and lists','Perfectionism that stops tasks being finished','Excessive devotion to work','Rigid morals','Reluctance to delegate','Stubbornness'],
 causes:'Genetics and temperament; it often runs in families.',
 brain:[['dlpfc','s','Altered cognitive control (limited research)'],['caudate','s','Some overlap with OCD circuitry has been proposed'],['ofc','s','Rigid valuation (limited research)']],
 treatment:'CBT and psychodynamic therapy.',
 prevalence:'About 2–8% of people; one of the most common personality disorders.'},
{id:'stpd',name:'Schizotypal personality disorder',short:'Schizotypal PD',aka:['schizotypal personality disorder'],cat:'Personality disorders',
 summary:'Schizotypal personality disorder involves social and interpersonal deficits, acute discomfort in close relationships, and odd beliefs, perceptions or behavior. It is genetically related to schizophrenia but without sustained psychosis.',
 symptoms:['Ideas of reference','Odd beliefs or magical thinking','Unusual perceptions','Odd speech and suspiciousness','Few close friends','Social anxiety that does not fade with familiarity'],
 causes:'Shares genetic risk with schizophrenia.',
 brain:[['stg','s','Smaller left superior temporal gyrus, similar to schizophrenia'],['dlpfc','s','Mild working memory and prefrontal changes'],['latvent','s','Mild ventricular enlargement in some studies']],
 treatment:'Psychotherapy and social skills training; low-dose antipsychotics for some symptoms.',
 prevalence:'About 1–4% of people.'},
{id:'ppd',name:'Paranoid personality disorder',short:'Paranoid PD',aka:['paranoid personality disorder'],cat:'Personality disorders',
 summary:'Paranoid personality disorder is a pervasive distrust and suspiciousness of others, interpreting their motives as harmful, without the fixed delusions of psychosis.',
 symptoms:['Suspecting others of exploiting or deceiving','Doubting the loyalty of friends','Reluctance to confide','Reading threats into harmless remarks','Holding grudges'],
 causes:'Possible genetic links with schizophrenia, and early adversity.',
 brain:[['amygdala','s','Heightened threat detection is proposed; direct imaging research is limited']],
 treatment:'Psychotherapy focused on building trust.',
 prevalence:'About 2–4% of people.'},
{id:'szpd',name:'Schizoid personality disorder',short:'Schizoid PD',aka:['schizoid personality disorder'],cat:'Personality disorders',
 summary:'Schizoid personality disorder is a pervasive pattern of detachment from social relationships and a restricted range of emotional expression. People prefer solitary activities and seem indifferent to praise or criticism.',
 symptoms:['Little desire for close relationships','Choosing solitary activities','Little interest in sexual experiences with others','Taking pleasure in few activities','Emotional coldness or flatness'],
 causes:'Genetic links to the schizophrenia spectrum are suspected.',
 brain:[['nacc','s','Reduced social reward response is proposed; brain imaging research is very limited']],
 treatment:'People rarely seek treatment; psychotherapy can help when they do.',
 prevalence:'Less than 1–3% of people.'},
{id:'hpd',name:'Histrionic personality disorder',short:'Histrionic PD',aka:['histrionic personality disorder'],cat:'Personality disorders',
 summary:'Histrionic personality disorder is a pattern of excessive emotionality and attention-seeking, with a need to be the center of attention.',
 symptoms:['Discomfort when not the center of attention','Rapidly shifting, shallow emotions','Using appearance to draw attention','Dramatic, theatrical expression','Being easily influenced'],
 causes:'Genetics and early experiences; little research exists.',
 brain:[['amygdala','s','Heightened emotional reactivity is proposed; almost no imaging research exists']],
 treatment:'Psychotherapy.',
 prevalence:'About 1–2% of people.'},
{id:'dpd',name:'Dependent personality disorder',short:'Dependent PD',aka:['dependent personality disorder'],cat:'Personality disorders',
 summary:'Dependent personality disorder is a pervasive, excessive need to be taken care of, leading to submissive, clinging behavior and fear of separation.',
 symptoms:['Difficulty making everyday decisions without reassurance','Needing others to take responsibility','Difficulty disagreeing','Urgently seeking a new relationship when one ends','Fear of being left to care for oneself'],
 causes:'Overprotective or authoritarian parenting, anxious temperament and chronic illness in childhood.',
 brain:[['amygdala','s','Heightened anxiety about separation is proposed; imaging research is very limited']],
 treatment:'Psychotherapy focused on building independence and assertiveness.',
 prevalence:'Less than 1% of people.'},
/* ===== Disruptive ===== */
{id:'conduct',name:'Conduct disorder',short:'Conduct disorder',aka:['conduct disorder'],cat:'Disruptive, impulse-control & conduct disorders',
 summary:'Conduct disorder is a repetitive pattern in children or teens of violating the basic rights of others or major social rules, such as aggression to people or animals, destroying property, deceit and serious rule-breaking.',
 symptoms:['Aggression, bullying or fighting','Destroying property','Lying and stealing','Serious rule violations such as running away','In some, callous-unemotional traits: little guilt or empathy'],
 causes:'Genetics, harsh or inconsistent parenting, abuse, neighborhood violence and peer influence.',
 brain:[['amygdala','p',"Reduced response to others' distress, especially with callous-unemotional traits"],['vmpfc','s','Reduced activity during decision-making'],['antinsula','s','Altered empathy and emotional awareness'],['ofc','s','Reduced sensitivity to punishment']],
 treatment:'Parent management training, multisystemic therapy and school-based programs work best when started early.',
 prevalence:'About 2–10% of children and adolescents.'},
{id:'ied',name:'Intermittent explosive disorder',short:'IED',aka:['intermittent explosive disorder'],cat:'Disruptive, impulse-control & conduct disorders',
 summary:'Intermittent explosive disorder involves recurrent, impulsive outbursts of verbal or physical aggression that are far out of proportion to the trigger and are not planned.',
 symptoms:['Sudden rage outbursts','Verbal or physical aggression','Feeling relief then regret afterward'],
 causes:'Genetics, exposure to violence in childhood and serotonin system differences.',
 brain:[['amygdala','p','Overactive to angry faces and provocation'],['ofc','p','Reduced regulation of anger responses'],['acc','s','Weaker control over impulsive reactions']],
 treatment:'CBT focused on anger regulation; SSRIs.',
 prevalence:'About 2–3% of adults in a given year.'},
/* ===== Neurocognitive ===== */
{id:'delirium',name:'Delirium',short:'Delirium',aka:['delirium'],cat:'Neurocognitive disorders',
 summary:'Delirium is an acute, fluctuating disturbance in attention and awareness that develops over hours to days, usually caused by a medical condition, infection, surgery, medication or substance withdrawal. It is a medical emergency.',
 symptoms:['Inability to focus or shift attention','Confusion and disorientation','Fluctuating alertness','Hallucinations','Disturbed sleep–wake cycle'],
 causes:'Infection, surgery, dehydration, medications, alcohol withdrawal and organ failure. Older age and dementia raise risk.',
 brain:[['thalamus','s','Disrupted arousal and attention gating'],['dlpfc','s','Disrupted attention networks'],['pcc','s','Altered default mode network connectivity']],
 treatment:'Find and treat the cause; keep the person oriented, mobile and sleeping well; avoid unnecessary sedatives.',
 prevalence:'Affects up to a third or more of older hospitalized patients.'}
];
